kb_index_header(index_header{count:4,digest:'98d6449201fc4d5775eff3560a2f1ba5cf6f54ab4b4640a5404983e5f999a438',normalizedDigest:'8d684d6935bdfd1a96ace917766d4cdc8655433a4bec75cb26f65a4cc4a306af',normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/learned-knowledge/learned-action-model.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/learned-knowledge/learned-action-model.krf',sourceHash:b2ea6ca4ef92a8e81b9c23b7f83fe7be5239ded2aeb89cea396fbe32eed5ffe1}).
kb_index_data(index{constants:[-('x_<==',2),-(x_AggregateQuantityFn,1),-(x_CollectionSubsetFn,1),-(x_DecisionFn,2),-('x_FC-Terrain-DeepOcean',1),-('x_FC-Terrain-Lake',1),-('x_FC-Terrain-Ocean',1),-('x_FC-Unit-Settlers',1),-('x_FreeCiv-City',1),-(x_PreconditionOfFn,1),-(x_TheSetOf,1),-(x_achieve,1),-('x_actionEntailsDecision-TypeType',2),-(x_actionPositivelyAffectsQuantity,1),-(x_and,1),-(x_cityOwner,1),-(x_cityPopulation,1),-(x_complexTaskAchieves,1),-(x_currentPlayer,1),-(x_currentlyBuilding,1),-(x_currentlyResearching,1),-(x_different,1),-(x_doBuildCity,2),-(x_doChangeProduction,1),-(x_doResearch,1),-(x_fcObjectAt,1),-(x_knowsValue,1),-(x_numAnswers,1),-(x_potentialCityAt,1),-(x_terrainAt,1),-(x_unitOwner,1),-(x_unitType,1)],entries:[entry(a65b134e02aeea,signature('x_<==',1),x_ActionModelMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/learned-knowledge/learned-action-model.krf',7,['x_<==',x_PreconditionOfFn,x_achieve,x_complexTaskAchieves,x_doBuildCity]),entry(a65b134e02aeeb,signature('x_<==',11),x_ActionModelMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/learned-knowledge/learned-action-model.krf',12,['x_<==',x_AggregateQuantityFn,x_CollectionSubsetFn,'x_FC-Terrain-DeepOcean','x_FC-Terrain-Lake','x_FC-Terrain-Ocean','x_FC-Unit-Settlers','x_FreeCiv-City',x_TheSetOf,x_actionPositivelyAffectsQuantity,x_and,x_cityOwner,x_cityPopulation,x_currentPlayer,x_different,x_doBuildCity,x_fcObjectAt,x_knowsValue,x_numAnswers,x_potentialCityAt,x_terrainAt,x_unitOwner,x_unitType]),entry(a65b134e02aeec,signature('x_actionEntailsDecision-TypeType',2),x_ActionModelMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/learned-knowledge/learned-action-model.krf',30,[x_DecisionFn,'x_actionEntailsDecision-TypeType',x_currentlyBuilding,x_doChangeProduction]),entry(a65b134e02aeed,signature('x_actionEntailsDecision-TypeType',2),x_ActionModelMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/learned-knowledge/learned-action-model.krf',32,[x_DecisionFn,'x_actionEntailsDecision-TypeType',x_currentlyResearching,x_doResearch])],predicates:[-(signature('x_<==',1),1),-(signature('x_<==',11),1),-(signature('x_actionEntailsDecision-TypeType',2),2)],rankedConstants:[-(2,x_doBuildCity),-(2,'x_actionEntailsDecision-TypeType'),-(2,x_DecisionFn),-(2,'x_<=='),-(1,x_unitType),-(1,x_unitOwner),-(1,x_terrainAt),-(1,x_potentialCityAt),-(1,x_numAnswers),-(1,x_knowsValue),-(1,x_fcObjectAt),-(1,x_doResearch),-(1,x_doChangeProduction),-(1,x_different),-(1,x_currentlyResearching),-(1,x_currentlyBuilding),-(1,x_currentPlayer),-(1,x_complexTaskAchieves),-(1,x_cityPopulation),-(1,x_cityOwner),-(1,x_and),-(1,x_actionPositivelyAffectsQuantity),-(1,x_achieve),-(1,x_TheSetOf),-(1,x_PreconditionOfFn),-(1,'x_FreeCiv-City'),-(1,'x_FC-Unit-Settlers'),-(1,'x_FC-Terrain-Ocean'),-(1,'x_FC-Terrain-Lake'),-(1,'x_FC-Terrain-DeepOcean'),-(1,x_CollectionSubsetFn),-(1,x_AggregateQuantityFn)],rankedPredicates:[-(2,signature('x_actionEntailsDecision-TypeType',2)),-(1,signature('x_<==',11)),-(1,signature('x_<==',1))],source:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/learned-knowledge/learned-action-model.krf'}).
xc_indexed_constant(a65b134e02aeea,'x_<==').
xc_indexed_constant(a65b134e02aeea,x_PreconditionOfFn).
xc_indexed_constant(a65b134e02aeea,x_achieve).
xc_indexed_constant(a65b134e02aeea,x_complexTaskAchieves).
xc_indexed_constant(a65b134e02aeea,x_doBuildCity).
xc_indexed_constant(a65b134e02aeeb,'x_<==').
xc_indexed_constant(a65b134e02aeeb,x_AggregateQuantityFn).
xc_indexed_constant(a65b134e02aeeb,x_CollectionSubsetFn).
xc_indexed_constant(a65b134e02aeeb,'x_FC-Terrain-DeepOcean').
xc_indexed_constant(a65b134e02aeeb,'x_FC-Terrain-Lake').
xc_indexed_constant(a65b134e02aeeb,'x_FC-Terrain-Ocean').
xc_indexed_constant(a65b134e02aeeb,'x_FC-Unit-Settlers').
xc_indexed_constant(a65b134e02aeeb,'x_FreeCiv-City').
xc_indexed_constant(a65b134e02aeeb,x_TheSetOf).
xc_indexed_constant(a65b134e02aeeb,x_actionPositivelyAffectsQuantity).
xc_indexed_constant(a65b134e02aeeb,x_and).
xc_indexed_constant(a65b134e02aeeb,x_cityOwner).
xc_indexed_constant(a65b134e02aeeb,x_cityPopulation).
xc_indexed_constant(a65b134e02aeeb,x_currentPlayer).
xc_indexed_constant(a65b134e02aeeb,x_different).
xc_indexed_constant(a65b134e02aeeb,x_doBuildCity).
xc_indexed_constant(a65b134e02aeeb,x_fcObjectAt).
xc_indexed_constant(a65b134e02aeeb,x_knowsValue).
xc_indexed_constant(a65b134e02aeeb,x_numAnswers).
xc_indexed_constant(a65b134e02aeeb,x_potentialCityAt).
xc_indexed_constant(a65b134e02aeeb,x_terrainAt).
xc_indexed_constant(a65b134e02aeeb,x_unitOwner).
xc_indexed_constant(a65b134e02aeeb,x_unitType).
xc_indexed_constant(a65b134e02aeec,x_DecisionFn).
xc_indexed_constant(a65b134e02aeec,'x_actionEntailsDecision-TypeType').
xc_indexed_constant(a65b134e02aeec,x_currentlyBuilding).
xc_indexed_constant(a65b134e02aeec,x_doChangeProduction).
xc_indexed_constant(a65b134e02aeed,x_DecisionFn).
xc_indexed_constant(a65b134e02aeed,'x_actionEntailsDecision-TypeType').
xc_indexed_constant(a65b134e02aeed,x_currentlyResearching).
xc_indexed_constant(a65b134e02aeed,x_doResearch).
kb_index_footer(4,'98d6449201fc4d5775eff3560a2f1ba5cf6f54ab4b4640a5404983e5f999a438','9132ca211d26cefc57c89c81fcbccaab05661173496e72b83b626a647fe56964').
