kb_index_header(index_header{count:106,digest:bb04651645714c53cf8d64ffe689505d3029b213b570f8c524a338993159a2f1,normalizedDigest:baafb55f2807e7aa7851efd468757f5537660fc7dd2b726f709893c9c5ebb4d7,normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',sourceHash:a115bc6aed51ed27e74a3721933f9ed1616e835adbacf726ece087d6706b7e40}).
kb_index_data(index{constants:[-(x_AccomplishentType,1),-(x_AccomplishmentType,1),-(x_AilmentCondition,1),-(x_Airplane,1),-(x_Assembling,1),-(x_Attachment,1),-(x_Backpack,1),-(x_Backpacking,3),-(x_Baking,2),-(x_Breath,3),-(x_Breathing,2),-(x_BrideAndGroomStandBeforeOfficiant,1),-(x_Campfire,13),-(x_Camping,25),-(x_CampingStove,1),-(x_Campsite,2),-(x_Canvas,1),-(x_CeramicGlaze,2),-(x_CeremonialExchangeOfWeddingRings,1),-(x_ChoosingACampsite,7),-('x_Clay-Wet',2),-('x_Clothing-Bottom',8),-(x_CoatingDeposition,1),-('x_Coffee-Beverage',1),-(x_CoffeeBreak,1),-(x_CollectionIntersection2Fn,2),-(x_CollectionSubsetFn,1),-(x_CompetitionEventTypeFn,1),-(x_Compressing,1),-(x_CookingFood,4),-('x_DecaffeinatedCoffee-Beverage',1),-(x_Defecating,6),-(x_DrinkingDecaf,1),-(x_DrinkingEvent,1),-('x_DriversLicense-LicenseAgreement',1),-(x_DurativeEventType,1),-(x_EquipmentTypeForEventTypeFn,4),-('x_Exhaling-BreathingOut',2),-(x_Firewood,3),-(x_FirstOrderCollection,2),-(x_FlushingAToilet,4),-(x_FlyingLicense,1),-(x_Folding,1),-(x_GaseousTangibleThing,1),-(x_GoingToTheBathroom,23),-(x_Halitosis,3),-(x_HavingAMeal,3),-(x_HumanChild,1),-('x_Inhaling-BreathingIn',1),-(x_InteriorsOfTypeFn,1),-(x_JumpRope,2),-(x_JumpingOverSomething,1),-(x_JumpingRope,3),-(x_JumpingUpAndDown,1),-(x_Kiln,2),-('x_LightingUp-SettingSomethingOnFire',2),-(x_MakinFn,1),-(x_MakingFn,10),-(x_MakingPottery,4),-('x_Movement-TranslationEvent',4),-(x_PaperAirplane,1),-('x_PartsFn-Device',1),-(x_PhysicalCollectionEvent,2),-(x_PhysiologicalConditionType,1),-(x_PitchingATent,8),-(x_PlanetEarth,1),-('x_Pole-Rod',1),-(x_PrecipitationProcess,1),-(x_ReplacingSomething,4),-(x_Restroom,4),-(x_RoadVehicle,1),-('x_Rotation-Periodic',1),-(x_SelectingSomething,1),-(x_SeparatePhysicalPartOfObject,1),-(x_ShapingSomething,1),-(x_SheetOfPaper,1),-(x_ShelteringArtifact,1),-(x_SittingOnSomething,5),-(x_SkilledActivityType,3),-(x_Sleeping,7),-(x_SleepingBag,2),-(x_SnowMob,1),-(x_Snowball,1),-(x_Spelling,1),-(x_SpellingBee,6),-(x_Stake,2),-(x_Student,1),-(x_SubcollectionOfWithRelationToFn,4),-(x_SubcollectionOfWithRelationToTypeFn,28),-(x_SupportingSomething,1),-(x_Tarp,1),-(x_TemporalStuffType,1),-('x_Tending-TakingCare-Handling-Management',3),-(x_Tent,12),-(x_TentPole,3),-(x_TheSetOf,1),-(x_ToiletSeat,5),-('x_Train-TransportationDevice',1),-(x_TrainEngineerLicense,1),-(x_TransportViaFn,3),-(x_Undressing,4),-(x_WalkingDownTheAisle,1),-(x_WashingHands,3),-(x_WeddingCeremony,4),-('x_WeddingEvent-Entire',2),-(x_WeddingReception,1),-(x_WoodedArea,1),-(x_and,1),-(x_assemblyInputs,1),-(x_characteristicEssentialProperSubEventTypes,1),-(x_comment,2),-(x_competingAgents,1),-(x_connectorInAttachment,1),-(x_deviceUsed,2),-(x_doneBy,7),-(x_endsAfterEndOfInSituationType,1),-(x_eventOccursAt,1),-(x_eventTypeHasCloselyAssociatedObjectTypes,4),-(x_firstProperSubSituationTypes,1),-(x_focalProperSubsituationTypes,1),-(x_genls,7),-(x_heatTransferSource,1),-(x_inheritRolePlayers,7),-(x_isa,15),-(x_licenseFor,3),-(x_objectActedOn,6),-(x_objectFolded,1),-(x_objectHurdled,1),-(x_objectRemoved,4),-(x_objectRotating,1),-('x_objectSelected-TypeType',1),-(x_objectTakenCareOf,3),-(x_objectTypeReplaced,4),-(x_objectTypesCollected,2),-('x_outputsCreated-TypeType',2),-('x_parts-Device',3),-(x_properSubEventTypes,33),-(x_relationAllAll,2),-(x_relationAllOnly,1),-(x_relationExistsMost,3),-(x_seat,5),-(x_seated,1),-(x_startTogetherInSituationType,1),-(x_startsAfterEndOfInSituationType,10),-(x_startsAfterStartOfInSituationType,5),-(x_stuffExhaled,1),-(x_stuffSpread,1),-(x_subEventTypes,1),-(x_supportedObject,1),-(x_supportingObject,1),-(x_thingAttached,1),-(x_thingAttachedTo,1),-(x_thingsConsumed,2),-(x_toLocation,4),-(x_typePrimaryFunction,5),-(x_typeProvidesShelterDuringType,1)],entries:[entry(a65b126a21e483,signature(x_isa,2),x_UniversalVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',26,[x_Breath,x_FirstOrderCollection,x_isa]),entry(a65b126a21e484,signature(x_genls,2),x_UniversalVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',27,[x_Breath,x_GaseousTangibleThing,x_genls]),entry(a65b126a21e485,signature(x_relationAllAll,3),x_UniversalVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',28,[x_Breath,'x_Exhaling-BreathingOut',x_relationAllAll,x_stuffExhaled]),entry(a65b126a21e486,signature(x_isa,2),x_UniversalVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',30,[x_Halitosis,x_PhysiologicalConditionType,x_isa]),entry(a65b126a21e487,signature(x_genls,2),x_UniversalVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',31,[x_AilmentCondition,x_Halitosis,x_genls]),entry(a65b126a21e488,signature(x_comment,2),x_UniversalVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',32,[x_Halitosis,x_comment]),entry(a65b126a21e489,signature(x_properSubEventTypes,2),x_AnimalActivitiesMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',40,[x_Breathing,'x_Inhaling-BreathingIn',x_properSubEventTypes]),entry(a65b126a21e48a,signature(x_properSubEventTypes,2),x_AnimalActivitiesMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',41,[x_Breathing,'x_Exhaling-BreathingOut',x_properSubEventTypes]),entry(a65b126a21e48b,signature(x_subEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',45,['x_Coffee-Beverage',x_CoffeeBreak,x_DrinkingEvent,x_SubcollectionOfWithRelationToTypeFn,x_subEventTypes,x_thingsConsumed]),entry(a65b126a21e48c,signature(x_relationAllAll,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',54,['x_DecaffeinatedCoffee-Beverage',x_DrinkingDecaf,x_relationAllAll,x_thingsConsumed]),entry(a65b126a21e48d,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',60,[x_Camping,x_EquipmentTypeForEventTypeFn,x_Tent,x_isa]),entry(a65b126a21e48e,signature(x_genls,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',61,[x_ShelteringArtifact,x_Tent,x_genls]),entry(a65b126a21e48f,signature(x_typeProvidesShelterDuringType,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',62,[x_PrecipitationProcess,x_Tent,x_typeProvidesShelterDuringType]),entry(a65b126a21e490,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',63,[x_Camping,x_EquipmentTypeForEventTypeFn,x_SleepingBag,x_isa]),entry(a65b126a21e491,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',64,[x_Camping,x_CampingStove,x_EquipmentTypeForEventTypeFn,x_isa]),entry(a65b126a21e492,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',65,[x_Backpack,x_Backpacking,x_EquipmentTypeForEventTypeFn,x_isa]),entry(a65b126a21e493,signature(x_typePrimaryFunction,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',66,[x_Campsite,x_Sleeping,x_eventOccursAt,x_typePrimaryFunction]),entry(a65b126a21e494,signature(x_typePrimaryFunction,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',67,[x_Campfire,x_CookingFood,x_heatTransferSource,x_typePrimaryFunction]),entry(a65b126a21e495,signature(x_typePrimaryFunction,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',68,[x_InteriorsOfTypeFn,x_Sleeping,x_Tent,x_typePrimaryFunction]),entry(a65b126a21e496,signature(x_eventTypeHasCloselyAssociatedObjectTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',69,[x_Camping,x_Tent,x_eventTypeHasCloselyAssociatedObjectTypes]),entry(a65b126a21e497,signature(x_eventTypeHasCloselyAssociatedObjectTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',70,[x_Campfire,x_Camping,x_eventTypeHasCloselyAssociatedObjectTypes]),entry(a65b126a21e498,signature(x_eventTypeHasCloselyAssociatedObjectTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',71,[x_Camping,x_SleepingBag,x_eventTypeHasCloselyAssociatedObjectTypes]),entry(a65b126a21e499,signature(x_eventTypeHasCloselyAssociatedObjectTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',72,[x_Camping,x_WoodedArea,x_eventTypeHasCloselyAssociatedObjectTypes]),entry(a65b126a21e49a,signature(x_characteristicEssentialProperSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',73,[x_Camping,x_Sleeping,x_characteristicEssentialProperSubEventTypes]),entry(a65b126a21e49b,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',77,[x_AccomplishmentType,x_ChoosingACampsite,x_isa]),entry(a65b126a21e49c,signature(x_genls,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',78,[x_ChoosingACampsite,x_SelectingSomething,x_genls]),entry(a65b126a21e49d,signature('x_objectSelected-TypeType',2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',79,[x_Campsite,x_ChoosingACampsite,'x_objectSelected-TypeType']),entry(a65b126a21e49e,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',81,[x_Campfire,x_MakingFn,x_SkilledActivityType,x_isa]),entry(a65b126a21e49f,signature('x_outputsCreated-TypeType',2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',82,[x_Campfire,x_MakingFn,'x_outputsCreated-TypeType']),entry(a65b126a21e4a0,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',83,[x_Campfire,x_SkilledActivityType,x_SubcollectionOfWithRelationToTypeFn,'x_Tending-TakingCare-Handling-Management',x_isa,x_objectTakenCareOf]),entry(a65b126a21e4a1,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',86,[x_AccomplishentType,x_PitchingATent,x_isa]),entry(a65b126a21e4a2,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',87,[x_PitchingATent,x_SkilledActivityType,x_isa]),entry(a65b126a21e4a3,signature(x_genls,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',88,[x_Assembling,'x_PartsFn-Device',x_PitchingATent,x_SubcollectionOfWithRelationToTypeFn,x_Tent,x_assemblyInputs,x_genls]),entry(a65b126a21e4a4,signature('x_outputsCreated-TypeType',2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',91,[x_PitchingATent,x_Tent,'x_outputsCreated-TypeType']),entry(a65b126a21e4a5,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',93,[x_Backpacking,x_Camping,x_properSubEventTypes]),entry(a65b126a21e4a6,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',94,[x_Camping,x_ChoosingACampsite,x_properSubEventTypes]),entry(a65b126a21e4a7,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',95,[x_Camping,x_PitchingATent,x_properSubEventTypes]),entry(a65b126a21e4a8,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',96,[x_Campfire,x_Camping,x_MakingFn,x_properSubEventTypes]),entry(a65b126a21e4a9,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',97,[x_Campfire,x_Camping,x_SubcollectionOfWithRelationToTypeFn,'x_Tending-TakingCare-Handling-Management',x_objectTakenCareOf,x_properSubEventTypes]),entry(a65b126a21e4aa,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',99,[x_Camping,x_CookingFood,x_properSubEventTypes]),entry(a65b126a21e4ab,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',100,[x_Camping,x_HavingAMeal,x_properSubEventTypes]),entry(a65b126a21e4ac,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',101,[x_Camping,x_Sleeping,x_properSubEventTypes]),entry(a65b126a21e4ad,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',106,[x_Campfire,x_Firewood,x_MakingFn,x_PhysicalCollectionEvent,x_SubcollectionOfWithRelationToTypeFn,x_objectTypesCollected,x_properSubEventTypes]),entry(a65b126a21e4ae,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',108,[x_Campfire,x_Firewood,'x_LightingUp-SettingSomethingOnFire',x_MakingFn,x_SubcollectionOfWithRelationToTypeFn,x_objectActedOn,x_properSubEventTypes]),entry(a65b126a21e4af,signature('x_parts-Device',2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',111,[x_Tent,x_TentPole,'x_parts-Device']),entry(a65b126a21e4b0,signature('x_parts-Device',3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',112,[x_Canvas,x_CollectionIntersection2Fn,x_SeparatePhysicalPartOfObject,x_Tarp,x_Tent,'x_parts-Device']),entry(a65b126a21e4b1,signature('x_parts-Device',2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',113,[x_Stake,x_Tent,'x_parts-Device']),entry(a65b126a21e4b2,signature(x_typePrimaryFunction,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',115,[x_Attachment,x_CollectionSubsetFn,x_PlanetEarth,x_Stake,x_Tent,x_TheSetOf,x_and,x_connectorInAttachment,x_isa,x_thingAttached,x_thingAttachedTo,x_typePrimaryFunction]),entry(a65b126a21e4b3,signature(x_genls,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',124,['x_Pole-Rod',x_TentPole,x_genls]),entry(a65b126a21e4b4,signature(x_typePrimaryFunction,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',125,[x_SubcollectionOfWithRelationToTypeFn,x_SupportingSomething,x_Tent,x_TentPole,x_supportedObject,x_supportingObject,x_typePrimaryFunction]),entry(a65b126a21e4b5,signature(x_startsAfterStartOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',129,[x_Backpacking,x_Camping,x_ChoosingACampsite,x_startsAfterStartOfInSituationType]),entry(a65b126a21e4b6,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',130,[x_Camping,x_ChoosingACampsite,x_PitchingATent,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4b7,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',131,[x_Campfire,x_Camping,x_ChoosingACampsite,x_MakinFn,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4b8,signature(x_startTogetherInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',132,[x_Campfire,x_Camping,x_MakingFn,x_SubcollectionOfWithRelationToTypeFn,'x_Tending-TakingCare-Handling-Management',x_objectTakenCareOf,x_startTogetherInSituationType]),entry(a65b126a21e4b9,signature(x_startsAfterStartOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',135,[x_Campfire,x_Camping,x_CookingFood,x_MakingFn,x_startsAfterStartOfInSituationType]),entry(a65b126a21e4ba,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',136,[x_Camping,x_PitchingATent,x_Sleeping,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4bb,signature(x_startsAfterStartOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',137,[x_Campfire,x_Firewood,'x_LightingUp-SettingSomethingOnFire',x_MakingFn,x_PhysicalCollectionEvent,x_SubcollectionOfWithRelationToTypeFn,x_objectActedOn,x_objectTypesCollected,x_startsAfterStartOfInSituationType]),entry(a65b126a21e4bc,signature(x_startsAfterStartOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',140,[x_Camping,x_CookingFood,x_HavingAMeal,x_startsAfterStartOfInSituationType]),entry(a65b126a21e4bd,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',141,[x_Camping,x_HavingAMeal,x_Sleeping,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4be,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',142,[x_Camping,x_PitchingATent,x_Sleeping,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4bf,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',149,['x_Clay-Wet',x_MakingPottery,x_ShapingSomething,x_SubcollectionOfWithRelationToTypeFn,x_objectActedOn,x_properSubEventTypes]),entry(a65b126a21e4c0,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',151,[x_Baking,'x_Clay-Wet',x_Kiln,x_MakingPottery,x_SubcollectionOfWithRelationToTypeFn,x_deviceUsed,x_objectActedOn,x_properSubEventTypes]),entry(a65b126a21e4c1,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',153,[x_CeramicGlaze,x_CoatingDeposition,x_MakingPottery,x_SubcollectionOfWithRelationToTypeFn,x_properSubEventTypes,x_stuffSpread]),entry(a65b126a21e4c2,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',155,[x_Baking,x_CeramicGlaze,x_Kiln,x_MakingPottery,x_SubcollectionOfWithRelationToTypeFn,x_deviceUsed,x_objectActedOn,x_properSubEventTypes]),entry(a65b126a21e4c3,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',163,[x_GoingToTheBathroom,'x_Movement-TranslationEvent',x_Restroom,x_SubcollectionOfWithRelationToTypeFn,x_properSubEventTypes,x_toLocation]),entry(a65b126a21e4c4,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',164,['x_Clothing-Bottom',x_GoingToTheBathroom,x_SubcollectionOfWithRelationToTypeFn,x_Undressing,x_objectRemoved,x_properSubEventTypes]),entry(a65b126a21e4c5,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',165,[x_GoingToTheBathroom,x_SittingOnSomething,x_SubcollectionOfWithRelationToTypeFn,x_ToiletSeat,x_properSubEventTypes,x_seat]),entry(a65b126a21e4c6,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',166,[x_Defecating,x_GoingToTheBathroom,x_properSubEventTypes]),entry(a65b126a21e4c7,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',167,[x_FlushingAToilet,x_GoingToTheBathroom,x_properSubEventTypes]),entry(a65b126a21e4c8,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',168,['x_Clothing-Bottom',x_GoingToTheBathroom,x_ReplacingSomething,x_SubcollectionOfWithRelationToFn,x_objectTypeReplaced,x_properSubEventTypes]),entry(a65b126a21e4c9,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',169,[x_GoingToTheBathroom,x_WashingHands,x_properSubEventTypes]),entry(a65b126a21e4ca,signature(x_firstProperSubSituationTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',171,[x_GoingToTheBathroom,'x_Movement-TranslationEvent',x_Restroom,x_SubcollectionOfWithRelationToTypeFn,x_firstProperSubSituationTypes,x_toLocation]),entry(a65b126a21e4cb,signature(x_focalProperSubsituationTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',172,[x_Defecating,x_GoingToTheBathroom,x_focalProperSubsituationTypes]),entry(a65b126a21e4cc,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',174,['x_Clothing-Bottom',x_GoingToTheBathroom,'x_Movement-TranslationEvent',x_Restroom,x_SubcollectionOfWithRelationToTypeFn,x_Undressing,x_objectRemoved,x_startsAfterEndOfInSituationType,x_toLocation]),entry(a65b126a21e4cd,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',177,['x_Clothing-Bottom',x_GoingToTheBathroom,x_SittingOnSomething,x_SubcollectionOfWithRelationToTypeFn,x_ToiletSeat,x_Undressing,x_objectRemoved,x_seat,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4ce,signature(x_startsAfterStartOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',180,[x_Defecating,x_GoingToTheBathroom,x_SittingOnSomething,x_SubcollectionOfWithRelationToTypeFn,x_ToiletSeat,x_seat,x_startsAfterStartOfInSituationType]),entry(a65b126a21e4cf,signature(x_endsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',183,[x_Defecating,x_GoingToTheBathroom,x_SittingOnSomething,x_SubcollectionOfWithRelationToTypeFn,x_ToiletSeat,x_endsAfterEndOfInSituationType,x_seat]),entry(a65b126a21e4d0,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',186,[x_Defecating,x_FlushingAToilet,x_GoingToTheBathroom,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4d1,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',190,['x_Clothing-Bottom',x_FlushingAToilet,x_GoingToTheBathroom,x_ReplacingSomething,x_SubcollectionOfWithRelationToFn,x_objectTypeReplaced,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4d2,signature(x_startsAfterEndOfInSituationType,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',193,['x_Clothing-Bottom',x_GoingToTheBathroom,x_ReplacingSomething,x_SubcollectionOfWithRelationToFn,x_WashingHands,x_objectTypeReplaced,x_startsAfterEndOfInSituationType]),entry(a65b126a21e4d3,signature(x_inheritRolePlayers,5),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',197,[x_GoingToTheBathroom,'x_Movement-TranslationEvent',x_Restroom,x_SubcollectionOfWithRelationToTypeFn,x_doneBy,x_inheritRolePlayers,x_toLocation]),entry(a65b126a21e4d4,signature(x_inheritRolePlayers,5),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',202,['x_Clothing-Bottom',x_GoingToTheBathroom,x_SubcollectionOfWithRelationToTypeFn,x_Undressing,x_doneBy,x_inheritRolePlayers,x_objectRemoved]),entry(a65b126a21e4d5,signature(x_inheritRolePlayers,5),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',207,[x_GoingToTheBathroom,x_SittingOnSomething,x_SubcollectionOfWithRelationToTypeFn,x_ToiletSeat,x_doneBy,x_inheritRolePlayers,x_seat,x_seated]),entry(a65b126a21e4d6,signature(x_inheritRolePlayers,5),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',212,[x_Defecating,x_GoingToTheBathroom,x_doneBy,x_inheritRolePlayers]),entry(a65b126a21e4d7,signature(x_inheritRolePlayers,5),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',213,[x_FlushingAToilet,x_GoingToTheBathroom,x_doneBy,x_inheritRolePlayers]),entry(a65b126a21e4d8,signature(x_inheritRolePlayers,5),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',215,['x_Clothing-Bottom',x_GoingToTheBathroom,x_ReplacingSomething,x_SubcollectionOfWithRelationToFn,x_doneBy,x_inheritRolePlayers,x_objectTypeReplaced]),entry(a65b126a21e4d9,signature(x_inheritRolePlayers,5),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',220,[x_GoingToTheBathroom,x_WashingHands,x_doneBy,x_inheritRolePlayers]),entry(a65b126a21e4da,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',232,[x_Folding,x_MakingFn,x_PaperAirplane,x_SheetOfPaper,x_SubcollectionOfWithRelationToTypeFn,x_objectFolded,x_properSubEventTypes]),entry(a65b126a21e4db,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',233,[x_Compressing,x_MakingFn,x_SnowMob,x_Snowball,x_SubcollectionOfWithRelationToTypeFn,x_objectActedOn,x_properSubEventTypes]),entry(a65b126a21e4dc,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',237,[x_JumpingRope,x_JumpingUpAndDown,x_properSubEventTypes]),entry(a65b126a21e4dd,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',238,[x_JumpRope,x_JumpingRope,'x_Rotation-Periodic',x_SubcollectionOfWithRelationToTypeFn,x_objectRotating,x_properSubEventTypes]),entry(a65b126a21e4de,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',239,[x_JumpRope,x_JumpingOverSomething,x_JumpingRope,x_SubcollectionOfWithRelationToTypeFn,x_objectHurdled,x_properSubEventTypes]),entry(a65b126a21e4df,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',248,[x_FirstOrderCollection,x_SpellingBee,x_isa]),entry(a65b126a21e4e0,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',249,[x_SpellingBee,x_TemporalStuffType,x_isa]),entry(a65b126a21e4e1,signature(x_isa,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',250,[x_DurativeEventType,x_SpellingBee,x_isa]),entry(a65b126a21e4e2,signature(x_genls,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',251,[x_CompetitionEventTypeFn,x_Spelling,x_SpellingBee,x_genls]),entry(a65b126a21e4e3,signature(x_relationAllOnly,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',253,[x_CollectionIntersection2Fn,x_HumanChild,x_SpellingBee,x_Student,x_competingAgents,x_relationAllOnly]),entry(a65b126a21e4e4,signature(x_comment,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',255,[x_SpellingBee,x_comment]),entry(a65b126a21e4e5,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',261,[x_WeddingCeremony,'x_WeddingEvent-Entire',x_properSubEventTypes]),entry(a65b126a21e4e6,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',262,[x_WalkingDownTheAisle,x_WeddingCeremony,x_properSubEventTypes]),entry(a65b126a21e4e7,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',263,[x_BrideAndGroomStandBeforeOfficiant,x_WeddingCeremony,x_properSubEventTypes]),entry(a65b126a21e4e8,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',264,[x_CeremonialExchangeOfWeddingRings,x_WeddingCeremony,x_properSubEventTypes]),entry(a65b126a21e4e9,signature(x_properSubEventTypes,2),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',265,['x_WeddingEvent-Entire',x_WeddingReception,x_properSubEventTypes]),entry(a65b126a21e4ea,signature(x_relationExistsMost,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',289,['x_DriversLicense-LicenseAgreement',x_RoadVehicle,x_TransportViaFn,x_licenseFor,x_relationExistsMost]),entry(a65b126a21e4eb,signature(x_relationExistsMost,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',290,[x_Airplane,x_FlyingLicense,x_TransportViaFn,x_licenseFor,x_relationExistsMost]),entry(a65b126a21e4ec,signature(x_relationExistsMost,3),x_HumanSocialLifeMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf',291,['x_Train-TransportationDevice',x_TrainEngineerLicense,x_TransportViaFn,x_licenseFor,x_relationExistsMost])],predicates:[-(signature(x_characteristicEssentialProperSubEventTypes,2),1),-(signature(x_comment,2),2),-(signature(x_endsAfterEndOfInSituationType,3),1),-(signature(x_eventTypeHasCloselyAssociatedObjectTypes,2),4),-(signature(x_firstProperSubSituationTypes,2),1),-(signature(x_focalProperSubsituationTypes,2),1),-(signature(x_genls,2),7),-(signature(x_inheritRolePlayers,5),7),-(signature(x_isa,2),14),-(signature('x_objectSelected-TypeType',2),1),-(signature('x_outputsCreated-TypeType',2),2),-(signature('x_parts-Device',2),2),-(signature('x_parts-Device',3),1),-(signature(x_properSubEventTypes,2),33),-(signature(x_relationAllAll,3),2),-(signature(x_relationAllOnly,3),1),-(signature(x_relationExistsMost,3),3),-(signature(x_startTogetherInSituationType,3),1),-(signature(x_startsAfterEndOfInSituationType,3),10),-(signature(x_startsAfterStartOfInSituationType,3),5),-(signature(x_subEventTypes,2),1),-(signature(x_typePrimaryFunction,2),1),-(signature(x_typePrimaryFunction,3),4),-(signature(x_typeProvidesShelterDuringType,2),1)],rankedConstants:[-(33,x_properSubEventTypes),-(28,x_SubcollectionOfWithRelationToTypeFn),-(25,x_Camping),-(23,x_GoingToTheBathroom),-(15,x_isa),-(13,x_Campfire),-(12,x_Tent),-(10,x_startsAfterEndOfInSituationType),-(10,x_MakingFn),-(8,x_PitchingATent),-(8,'x_Clothing-Bottom'),-(7,x_inheritRolePlayers),-(7,x_genls),-(7,x_doneBy),-(7,x_Sleeping),-(7,x_ChoosingACampsite),-(6,x_objectActedOn),-(6,x_SpellingBee),-(6,x_Defecating),-(5,x_typePrimaryFunction),-(5,x_startsAfterStartOfInSituationType),-(5,x_seat),-(5,x_ToiletSeat),-(5,x_SittingOnSomething),-(4,x_toLocation),-(4,x_objectTypeReplaced),-(4,x_objectRemoved),-(4,x_eventTypeHasCloselyAssociatedObjectTypes),-(4,x_WeddingCeremony),-(4,x_Undressing),-(4,x_SubcollectionOfWithRelationToFn),-(4,x_Restroom),-(4,x_ReplacingSomething),-(4,'x_Movement-TranslationEvent'),-(4,x_MakingPottery),-(4,x_FlushingAToilet),-(4,x_EquipmentTypeForEventTypeFn),-(4,x_CookingFood),-(3,x_relationExistsMost),-(3,'x_parts-Device'),-(3,x_objectTakenCareOf),-(3,x_licenseFor),-(3,x_WashingHands),-(3,x_TransportViaFn),-(3,x_TentPole),-(3,'x_Tending-TakingCare-Handling-Management'),-(3,x_SkilledActivityType),-(3,x_JumpingRope),-(3,x_HavingAMeal),-(3,x_Halitosis),-(3,x_Firewood),-(3,x_Breath),-(3,x_Backpacking),-(2,x_thingsConsumed),-(2,x_relationAllAll),-(2,'x_outputsCreated-TypeType'),-(2,x_objectTypesCollected),-(2,x_deviceUsed),-(2,x_comment),-(2,'x_WeddingEvent-Entire'),-(2,x_Stake),-(2,x_SleepingBag),-(2,x_PhysicalCollectionEvent),-(2,'x_LightingUp-SettingSomethingOnFire'),-(2,x_Kiln),-(2,x_JumpRope),-(2,x_FirstOrderCollection),-(2,'x_Exhaling-BreathingOut'),-(2,x_CollectionIntersection2Fn),-(2,'x_Clay-Wet'),-(2,x_CeramicGlaze),-(2,x_Campsite),-(2,x_Breathing),-(2,x_Baking),-(1,x_typeProvidesShelterDuringType),-(1,x_thingAttachedTo),-(1,x_thingAttached),-(1,x_supportingObject),-(1,x_supportedObject),-(1,x_subEventTypes),-(1,x_stuffSpread),-(1,x_stuffExhaled),-(1,x_startTogetherInSituationType),-(1,x_seated),-(1,x_relationAllOnly),-(1,'x_objectSelected-TypeType'),-(1,x_objectRotating),-(1,x_objectHurdled),-(1,x_objectFolded),-(1,x_heatTransferSource),-(1,x_focalProperSubsituationTypes),-(1,x_firstProperSubSituationTypes),-(1,x_eventOccursAt),-(1,x_endsAfterEndOfInSituationType),-(1,x_connectorInAttachment),-(1,x_competingAgents),-(1,x_characteristicEssentialProperSubEventTypes),-(1,x_assemblyInputs),-(1,x_and),-(1,x_WoodedArea),-(1,x_WeddingReception),-(1,x_WalkingDownTheAisle),-(1,x_TrainEngineerLicense),-(1,'x_Train-TransportationDevice'),-(1,x_TheSetOf),-(1,x_TemporalStuffType),-(1,x_Tarp),-(1,x_SupportingSomething),-(1,x_Student),-(1,x_Spelling),-(1,x_Snowball),-(1,x_SnowMob),-(1,x_ShelteringArtifact),-(1,x_SheetOfPaper),-(1,x_ShapingSomething),-(1,x_SeparatePhysicalPartOfObject),-(1,x_SelectingSomething),-(1,'x_Rotation-Periodic'),-(1,x_RoadVehicle),-(1,x_PrecipitationProcess),-(1,'x_Pole-Rod'),-(1,x_PlanetEarth),-(1,x_PhysiologicalConditionType),-(1,'x_PartsFn-Device'),-(1,x_PaperAirplane),-(1,x_MakinFn),-(1,x_JumpingUpAndDown),-(1,x_JumpingOverSomething),-(1,x_InteriorsOfTypeFn),-(1,'x_Inhaling-BreathingIn'),-(1,x_HumanChild),-(1,x_GaseousTangibleThing),-(1,x_Folding),-(1,x_FlyingLicense),-(1,x_DurativeEventType),-(1,'x_DriversLicense-LicenseAgreement'),-(1,x_DrinkingEvent),-(1,x_DrinkingDecaf),-(1,'x_DecaffeinatedCoffee-Beverage'),-(1,x_Compressing),-(1,x_CompetitionEventTypeFn),-(1,x_CollectionSubsetFn),-(1,x_CoffeeBreak),-(1,'x_Coffee-Beverage'),-(1,x_CoatingDeposition),-(1,x_CeremonialExchangeOfWeddingRings),-(1,x_Canvas),-(1,x_CampingStove),-(1,x_BrideAndGroomStandBeforeOfficiant),-(1,x_Backpack),-(1,x_Attachment),-(1,x_Assembling),-(1,x_Airplane),-(1,x_AilmentCondition),-(1,x_AccomplishmentType),-(1,x_AccomplishentType)],rankedPredicates:[-(33,signature(x_properSubEventTypes,2)),-(14,signature(x_isa,2)),-(10,signature(x_startsAfterEndOfInSituationType,3)),-(7,signature(x_inheritRolePlayers,5)),-(7,signature(x_genls,2)),-(5,signature(x_startsAfterStartOfInSituationType,3)),-(4,signature(x_typePrimaryFunction,3)),-(4,signature(x_eventTypeHasCloselyAssociatedObjectTypes,2)),-(3,signature(x_relationExistsMost,3)),-(2,signature(x_relationAllAll,3)),-(2,signature('x_parts-Device',2)),-(2,signature('x_outputsCreated-TypeType',2)),-(2,signature(x_comment,2)),-(1,signature(x_typeProvidesShelterDuringType,2)),-(1,signature(x_typePrimaryFunction,2)),-(1,signature(x_subEventTypes,2)),-(1,signature(x_startTogetherInSituationType,3)),-(1,signature(x_relationAllOnly,3)),-(1,signature('x_parts-Device',3)),-(1,signature('x_objectSelected-TypeType',2)),-(1,signature(x_focalProperSubsituationTypes,2)),-(1,signature(x_firstProperSubSituationTypes,2)),-(1,signature(x_endsAfterEndOfInSituationType,3)),-(1,signature(x_characteristicEssentialProperSubEventTypes,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/NWU/background-knowledge/scripts.krf'}).
xc_indexed_constant(a65b126a21e483,x_Breath).
xc_indexed_constant(a65b126a21e483,x_FirstOrderCollection).
xc_indexed_constant(a65b126a21e483,x_isa).
xc_indexed_constant(a65b126a21e484,x_Breath).
xc_indexed_constant(a65b126a21e484,x_GaseousTangibleThing).
xc_indexed_constant(a65b126a21e484,x_genls).
xc_indexed_constant(a65b126a21e485,x_Breath).
xc_indexed_constant(a65b126a21e485,'x_Exhaling-BreathingOut').
xc_indexed_constant(a65b126a21e485,x_relationAllAll).
xc_indexed_constant(a65b126a21e485,x_stuffExhaled).
xc_indexed_constant(a65b126a21e486,x_Halitosis).
xc_indexed_constant(a65b126a21e486,x_PhysiologicalConditionType).
xc_indexed_constant(a65b126a21e486,x_isa).
xc_indexed_constant(a65b126a21e487,x_AilmentCondition).
xc_indexed_constant(a65b126a21e487,x_Halitosis).
xc_indexed_constant(a65b126a21e487,x_genls).
xc_indexed_constant(a65b126a21e488,x_Halitosis).
xc_indexed_constant(a65b126a21e488,x_comment).
xc_indexed_constant(a65b126a21e489,x_Breathing).
xc_indexed_constant(a65b126a21e489,'x_Inhaling-BreathingIn').
xc_indexed_constant(a65b126a21e489,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e48a,x_Breathing).
xc_indexed_constant(a65b126a21e48a,'x_Exhaling-BreathingOut').
xc_indexed_constant(a65b126a21e48a,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e48b,'x_Coffee-Beverage').
xc_indexed_constant(a65b126a21e48b,x_CoffeeBreak).
xc_indexed_constant(a65b126a21e48b,x_DrinkingEvent).
xc_indexed_constant(a65b126a21e48b,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e48b,x_subEventTypes).
xc_indexed_constant(a65b126a21e48b,x_thingsConsumed).
xc_indexed_constant(a65b126a21e48c,'x_DecaffeinatedCoffee-Beverage').
xc_indexed_constant(a65b126a21e48c,x_DrinkingDecaf).
xc_indexed_constant(a65b126a21e48c,x_relationAllAll).
xc_indexed_constant(a65b126a21e48c,x_thingsConsumed).
xc_indexed_constant(a65b126a21e48d,x_Camping).
xc_indexed_constant(a65b126a21e48d,x_EquipmentTypeForEventTypeFn).
xc_indexed_constant(a65b126a21e48d,x_Tent).
xc_indexed_constant(a65b126a21e48d,x_isa).
xc_indexed_constant(a65b126a21e48e,x_ShelteringArtifact).
xc_indexed_constant(a65b126a21e48e,x_Tent).
xc_indexed_constant(a65b126a21e48e,x_genls).
xc_indexed_constant(a65b126a21e48f,x_PrecipitationProcess).
xc_indexed_constant(a65b126a21e48f,x_Tent).
xc_indexed_constant(a65b126a21e48f,x_typeProvidesShelterDuringType).
xc_indexed_constant(a65b126a21e490,x_Camping).
xc_indexed_constant(a65b126a21e490,x_EquipmentTypeForEventTypeFn).
xc_indexed_constant(a65b126a21e490,x_SleepingBag).
xc_indexed_constant(a65b126a21e490,x_isa).
xc_indexed_constant(a65b126a21e491,x_Camping).
xc_indexed_constant(a65b126a21e491,x_CampingStove).
xc_indexed_constant(a65b126a21e491,x_EquipmentTypeForEventTypeFn).
xc_indexed_constant(a65b126a21e491,x_isa).
xc_indexed_constant(a65b126a21e492,x_Backpack).
xc_indexed_constant(a65b126a21e492,x_Backpacking).
xc_indexed_constant(a65b126a21e492,x_EquipmentTypeForEventTypeFn).
xc_indexed_constant(a65b126a21e492,x_isa).
xc_indexed_constant(a65b126a21e493,x_Campsite).
xc_indexed_constant(a65b126a21e493,x_Sleeping).
xc_indexed_constant(a65b126a21e493,x_eventOccursAt).
xc_indexed_constant(a65b126a21e493,x_typePrimaryFunction).
xc_indexed_constant(a65b126a21e494,x_Campfire).
xc_indexed_constant(a65b126a21e494,x_CookingFood).
xc_indexed_constant(a65b126a21e494,x_heatTransferSource).
xc_indexed_constant(a65b126a21e494,x_typePrimaryFunction).
xc_indexed_constant(a65b126a21e495,x_InteriorsOfTypeFn).
xc_indexed_constant(a65b126a21e495,x_Sleeping).
xc_indexed_constant(a65b126a21e495,x_Tent).
xc_indexed_constant(a65b126a21e495,x_typePrimaryFunction).
xc_indexed_constant(a65b126a21e496,x_Camping).
xc_indexed_constant(a65b126a21e496,x_Tent).
xc_indexed_constant(a65b126a21e496,x_eventTypeHasCloselyAssociatedObjectTypes).
xc_indexed_constant(a65b126a21e497,x_Campfire).
xc_indexed_constant(a65b126a21e497,x_Camping).
xc_indexed_constant(a65b126a21e497,x_eventTypeHasCloselyAssociatedObjectTypes).
xc_indexed_constant(a65b126a21e498,x_Camping).
xc_indexed_constant(a65b126a21e498,x_SleepingBag).
xc_indexed_constant(a65b126a21e498,x_eventTypeHasCloselyAssociatedObjectTypes).
xc_indexed_constant(a65b126a21e499,x_Camping).
xc_indexed_constant(a65b126a21e499,x_WoodedArea).
xc_indexed_constant(a65b126a21e499,x_eventTypeHasCloselyAssociatedObjectTypes).
xc_indexed_constant(a65b126a21e49a,x_Camping).
xc_indexed_constant(a65b126a21e49a,x_Sleeping).
xc_indexed_constant(a65b126a21e49a,x_characteristicEssentialProperSubEventTypes).
xc_indexed_constant(a65b126a21e49b,x_AccomplishmentType).
xc_indexed_constant(a65b126a21e49b,x_ChoosingACampsite).
xc_indexed_constant(a65b126a21e49b,x_isa).
xc_indexed_constant(a65b126a21e49c,x_ChoosingACampsite).
xc_indexed_constant(a65b126a21e49c,x_SelectingSomething).
xc_indexed_constant(a65b126a21e49c,x_genls).
xc_indexed_constant(a65b126a21e49d,x_Campsite).
xc_indexed_constant(a65b126a21e49d,x_ChoosingACampsite).
xc_indexed_constant(a65b126a21e49d,'x_objectSelected-TypeType').
xc_indexed_constant(a65b126a21e49e,x_Campfire).
xc_indexed_constant(a65b126a21e49e,x_MakingFn).
xc_indexed_constant(a65b126a21e49e,x_SkilledActivityType).
xc_indexed_constant(a65b126a21e49e,x_isa).
xc_indexed_constant(a65b126a21e49f,x_Campfire).
xc_indexed_constant(a65b126a21e49f,x_MakingFn).
xc_indexed_constant(a65b126a21e49f,'x_outputsCreated-TypeType').
xc_indexed_constant(a65b126a21e4a0,x_Campfire).
xc_indexed_constant(a65b126a21e4a0,x_SkilledActivityType).
xc_indexed_constant(a65b126a21e4a0,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4a0,'x_Tending-TakingCare-Handling-Management').
xc_indexed_constant(a65b126a21e4a0,x_isa).
xc_indexed_constant(a65b126a21e4a0,x_objectTakenCareOf).
xc_indexed_constant(a65b126a21e4a1,x_AccomplishentType).
xc_indexed_constant(a65b126a21e4a1,x_PitchingATent).
xc_indexed_constant(a65b126a21e4a1,x_isa).
xc_indexed_constant(a65b126a21e4a2,x_PitchingATent).
xc_indexed_constant(a65b126a21e4a2,x_SkilledActivityType).
xc_indexed_constant(a65b126a21e4a2,x_isa).
xc_indexed_constant(a65b126a21e4a3,x_Assembling).
xc_indexed_constant(a65b126a21e4a3,'x_PartsFn-Device').
xc_indexed_constant(a65b126a21e4a3,x_PitchingATent).
xc_indexed_constant(a65b126a21e4a3,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4a3,x_Tent).
xc_indexed_constant(a65b126a21e4a3,x_assemblyInputs).
xc_indexed_constant(a65b126a21e4a3,x_genls).
xc_indexed_constant(a65b126a21e4a4,x_PitchingATent).
xc_indexed_constant(a65b126a21e4a4,x_Tent).
xc_indexed_constant(a65b126a21e4a4,'x_outputsCreated-TypeType').
xc_indexed_constant(a65b126a21e4a5,x_Backpacking).
xc_indexed_constant(a65b126a21e4a5,x_Camping).
xc_indexed_constant(a65b126a21e4a5,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4a6,x_Camping).
xc_indexed_constant(a65b126a21e4a6,x_ChoosingACampsite).
xc_indexed_constant(a65b126a21e4a6,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4a7,x_Camping).
xc_indexed_constant(a65b126a21e4a7,x_PitchingATent).
xc_indexed_constant(a65b126a21e4a7,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4a8,x_Campfire).
xc_indexed_constant(a65b126a21e4a8,x_Camping).
xc_indexed_constant(a65b126a21e4a8,x_MakingFn).
xc_indexed_constant(a65b126a21e4a8,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4a9,x_Campfire).
xc_indexed_constant(a65b126a21e4a9,x_Camping).
xc_indexed_constant(a65b126a21e4a9,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4a9,'x_Tending-TakingCare-Handling-Management').
xc_indexed_constant(a65b126a21e4a9,x_objectTakenCareOf).
xc_indexed_constant(a65b126a21e4a9,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4aa,x_Camping).
xc_indexed_constant(a65b126a21e4aa,x_CookingFood).
xc_indexed_constant(a65b126a21e4aa,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4ab,x_Camping).
xc_indexed_constant(a65b126a21e4ab,x_HavingAMeal).
xc_indexed_constant(a65b126a21e4ab,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4ac,x_Camping).
xc_indexed_constant(a65b126a21e4ac,x_Sleeping).
xc_indexed_constant(a65b126a21e4ac,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4ad,x_Campfire).
xc_indexed_constant(a65b126a21e4ad,x_Firewood).
xc_indexed_constant(a65b126a21e4ad,x_MakingFn).
xc_indexed_constant(a65b126a21e4ad,x_PhysicalCollectionEvent).
xc_indexed_constant(a65b126a21e4ad,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4ad,x_objectTypesCollected).
xc_indexed_constant(a65b126a21e4ad,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4ae,x_Campfire).
xc_indexed_constant(a65b126a21e4ae,x_Firewood).
xc_indexed_constant(a65b126a21e4ae,'x_LightingUp-SettingSomethingOnFire').
xc_indexed_constant(a65b126a21e4ae,x_MakingFn).
xc_indexed_constant(a65b126a21e4ae,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4ae,x_objectActedOn).
xc_indexed_constant(a65b126a21e4ae,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4af,x_Tent).
xc_indexed_constant(a65b126a21e4af,x_TentPole).
xc_indexed_constant(a65b126a21e4af,'x_parts-Device').
xc_indexed_constant(a65b126a21e4b0,x_Canvas).
xc_indexed_constant(a65b126a21e4b0,x_CollectionIntersection2Fn).
xc_indexed_constant(a65b126a21e4b0,x_SeparatePhysicalPartOfObject).
xc_indexed_constant(a65b126a21e4b0,x_Tarp).
xc_indexed_constant(a65b126a21e4b0,x_Tent).
xc_indexed_constant(a65b126a21e4b0,'x_parts-Device').
xc_indexed_constant(a65b126a21e4b1,x_Stake).
xc_indexed_constant(a65b126a21e4b1,x_Tent).
xc_indexed_constant(a65b126a21e4b1,'x_parts-Device').
xc_indexed_constant(a65b126a21e4b2,x_Attachment).
xc_indexed_constant(a65b126a21e4b2,x_CollectionSubsetFn).
xc_indexed_constant(a65b126a21e4b2,x_PlanetEarth).
xc_indexed_constant(a65b126a21e4b2,x_Stake).
xc_indexed_constant(a65b126a21e4b2,x_Tent).
xc_indexed_constant(a65b126a21e4b2,x_TheSetOf).
xc_indexed_constant(a65b126a21e4b2,x_and).
xc_indexed_constant(a65b126a21e4b2,x_connectorInAttachment).
xc_indexed_constant(a65b126a21e4b2,x_isa).
xc_indexed_constant(a65b126a21e4b2,x_thingAttached).
xc_indexed_constant(a65b126a21e4b2,x_thingAttachedTo).
xc_indexed_constant(a65b126a21e4b2,x_typePrimaryFunction).
xc_indexed_constant(a65b126a21e4b3,'x_Pole-Rod').
xc_indexed_constant(a65b126a21e4b3,x_TentPole).
xc_indexed_constant(a65b126a21e4b3,x_genls).
xc_indexed_constant(a65b126a21e4b4,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4b4,x_SupportingSomething).
xc_indexed_constant(a65b126a21e4b4,x_Tent).
xc_indexed_constant(a65b126a21e4b4,x_TentPole).
xc_indexed_constant(a65b126a21e4b4,x_supportedObject).
xc_indexed_constant(a65b126a21e4b4,x_supportingObject).
xc_indexed_constant(a65b126a21e4b4,x_typePrimaryFunction).
xc_indexed_constant(a65b126a21e4b5,x_Backpacking).
xc_indexed_constant(a65b126a21e4b5,x_Camping).
xc_indexed_constant(a65b126a21e4b5,x_ChoosingACampsite).
xc_indexed_constant(a65b126a21e4b5,x_startsAfterStartOfInSituationType).
xc_indexed_constant(a65b126a21e4b6,x_Camping).
xc_indexed_constant(a65b126a21e4b6,x_ChoosingACampsite).
xc_indexed_constant(a65b126a21e4b6,x_PitchingATent).
xc_indexed_constant(a65b126a21e4b6,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4b7,x_Campfire).
xc_indexed_constant(a65b126a21e4b7,x_Camping).
xc_indexed_constant(a65b126a21e4b7,x_ChoosingACampsite).
xc_indexed_constant(a65b126a21e4b7,x_MakinFn).
xc_indexed_constant(a65b126a21e4b7,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4b8,x_Campfire).
xc_indexed_constant(a65b126a21e4b8,x_Camping).
xc_indexed_constant(a65b126a21e4b8,x_MakingFn).
xc_indexed_constant(a65b126a21e4b8,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4b8,'x_Tending-TakingCare-Handling-Management').
xc_indexed_constant(a65b126a21e4b8,x_objectTakenCareOf).
xc_indexed_constant(a65b126a21e4b8,x_startTogetherInSituationType).
xc_indexed_constant(a65b126a21e4b9,x_Campfire).
xc_indexed_constant(a65b126a21e4b9,x_Camping).
xc_indexed_constant(a65b126a21e4b9,x_CookingFood).
xc_indexed_constant(a65b126a21e4b9,x_MakingFn).
xc_indexed_constant(a65b126a21e4b9,x_startsAfterStartOfInSituationType).
xc_indexed_constant(a65b126a21e4ba,x_Camping).
xc_indexed_constant(a65b126a21e4ba,x_PitchingATent).
xc_indexed_constant(a65b126a21e4ba,x_Sleeping).
xc_indexed_constant(a65b126a21e4ba,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4bb,x_Campfire).
xc_indexed_constant(a65b126a21e4bb,x_Firewood).
xc_indexed_constant(a65b126a21e4bb,'x_LightingUp-SettingSomethingOnFire').
xc_indexed_constant(a65b126a21e4bb,x_MakingFn).
xc_indexed_constant(a65b126a21e4bb,x_PhysicalCollectionEvent).
xc_indexed_constant(a65b126a21e4bb,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4bb,x_objectActedOn).
xc_indexed_constant(a65b126a21e4bb,x_objectTypesCollected).
xc_indexed_constant(a65b126a21e4bb,x_startsAfterStartOfInSituationType).
xc_indexed_constant(a65b126a21e4bc,x_Camping).
xc_indexed_constant(a65b126a21e4bc,x_CookingFood).
xc_indexed_constant(a65b126a21e4bc,x_HavingAMeal).
xc_indexed_constant(a65b126a21e4bc,x_startsAfterStartOfInSituationType).
xc_indexed_constant(a65b126a21e4bd,x_Camping).
xc_indexed_constant(a65b126a21e4bd,x_HavingAMeal).
xc_indexed_constant(a65b126a21e4bd,x_Sleeping).
xc_indexed_constant(a65b126a21e4bd,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4be,x_Camping).
xc_indexed_constant(a65b126a21e4be,x_PitchingATent).
xc_indexed_constant(a65b126a21e4be,x_Sleeping).
xc_indexed_constant(a65b126a21e4be,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4bf,'x_Clay-Wet').
xc_indexed_constant(a65b126a21e4bf,x_MakingPottery).
xc_indexed_constant(a65b126a21e4bf,x_ShapingSomething).
xc_indexed_constant(a65b126a21e4bf,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4bf,x_objectActedOn).
xc_indexed_constant(a65b126a21e4bf,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c0,x_Baking).
xc_indexed_constant(a65b126a21e4c0,'x_Clay-Wet').
xc_indexed_constant(a65b126a21e4c0,x_Kiln).
xc_indexed_constant(a65b126a21e4c0,x_MakingPottery).
xc_indexed_constant(a65b126a21e4c0,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4c0,x_deviceUsed).
xc_indexed_constant(a65b126a21e4c0,x_objectActedOn).
xc_indexed_constant(a65b126a21e4c0,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c1,x_CeramicGlaze).
xc_indexed_constant(a65b126a21e4c1,x_CoatingDeposition).
xc_indexed_constant(a65b126a21e4c1,x_MakingPottery).
xc_indexed_constant(a65b126a21e4c1,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4c1,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c1,x_stuffSpread).
xc_indexed_constant(a65b126a21e4c2,x_Baking).
xc_indexed_constant(a65b126a21e4c2,x_CeramicGlaze).
xc_indexed_constant(a65b126a21e4c2,x_Kiln).
xc_indexed_constant(a65b126a21e4c2,x_MakingPottery).
xc_indexed_constant(a65b126a21e4c2,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4c2,x_deviceUsed).
xc_indexed_constant(a65b126a21e4c2,x_objectActedOn).
xc_indexed_constant(a65b126a21e4c2,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c3,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4c3,'x_Movement-TranslationEvent').
xc_indexed_constant(a65b126a21e4c3,x_Restroom).
xc_indexed_constant(a65b126a21e4c3,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4c3,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c3,x_toLocation).
xc_indexed_constant(a65b126a21e4c4,'x_Clothing-Bottom').
xc_indexed_constant(a65b126a21e4c4,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4c4,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4c4,x_Undressing).
xc_indexed_constant(a65b126a21e4c4,x_objectRemoved).
xc_indexed_constant(a65b126a21e4c4,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c5,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4c5,x_SittingOnSomething).
xc_indexed_constant(a65b126a21e4c5,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4c5,x_ToiletSeat).
xc_indexed_constant(a65b126a21e4c5,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c5,x_seat).
xc_indexed_constant(a65b126a21e4c6,x_Defecating).
xc_indexed_constant(a65b126a21e4c6,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4c6,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c7,x_FlushingAToilet).
xc_indexed_constant(a65b126a21e4c7,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4c7,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c8,'x_Clothing-Bottom').
xc_indexed_constant(a65b126a21e4c8,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4c8,x_ReplacingSomething).
xc_indexed_constant(a65b126a21e4c8,x_SubcollectionOfWithRelationToFn).
xc_indexed_constant(a65b126a21e4c8,x_objectTypeReplaced).
xc_indexed_constant(a65b126a21e4c8,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4c9,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4c9,x_WashingHands).
xc_indexed_constant(a65b126a21e4c9,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4ca,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4ca,'x_Movement-TranslationEvent').
xc_indexed_constant(a65b126a21e4ca,x_Restroom).
xc_indexed_constant(a65b126a21e4ca,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4ca,x_firstProperSubSituationTypes).
xc_indexed_constant(a65b126a21e4ca,x_toLocation).
xc_indexed_constant(a65b126a21e4cb,x_Defecating).
xc_indexed_constant(a65b126a21e4cb,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4cb,x_focalProperSubsituationTypes).
xc_indexed_constant(a65b126a21e4cc,'x_Clothing-Bottom').
xc_indexed_constant(a65b126a21e4cc,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4cc,'x_Movement-TranslationEvent').
xc_indexed_constant(a65b126a21e4cc,x_Restroom).
xc_indexed_constant(a65b126a21e4cc,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4cc,x_Undressing).
xc_indexed_constant(a65b126a21e4cc,x_objectRemoved).
xc_indexed_constant(a65b126a21e4cc,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4cc,x_toLocation).
xc_indexed_constant(a65b126a21e4cd,'x_Clothing-Bottom').
xc_indexed_constant(a65b126a21e4cd,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4cd,x_SittingOnSomething).
xc_indexed_constant(a65b126a21e4cd,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4cd,x_ToiletSeat).
xc_indexed_constant(a65b126a21e4cd,x_Undressing).
xc_indexed_constant(a65b126a21e4cd,x_objectRemoved).
xc_indexed_constant(a65b126a21e4cd,x_seat).
xc_indexed_constant(a65b126a21e4cd,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4ce,x_Defecating).
xc_indexed_constant(a65b126a21e4ce,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4ce,x_SittingOnSomething).
xc_indexed_constant(a65b126a21e4ce,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4ce,x_ToiletSeat).
xc_indexed_constant(a65b126a21e4ce,x_seat).
xc_indexed_constant(a65b126a21e4ce,x_startsAfterStartOfInSituationType).
xc_indexed_constant(a65b126a21e4cf,x_Defecating).
xc_indexed_constant(a65b126a21e4cf,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4cf,x_SittingOnSomething).
xc_indexed_constant(a65b126a21e4cf,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4cf,x_ToiletSeat).
xc_indexed_constant(a65b126a21e4cf,x_endsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4cf,x_seat).
xc_indexed_constant(a65b126a21e4d0,x_Defecating).
xc_indexed_constant(a65b126a21e4d0,x_FlushingAToilet).
xc_indexed_constant(a65b126a21e4d0,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d0,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4d1,'x_Clothing-Bottom').
xc_indexed_constant(a65b126a21e4d1,x_FlushingAToilet).
xc_indexed_constant(a65b126a21e4d1,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d1,x_ReplacingSomething).
xc_indexed_constant(a65b126a21e4d1,x_SubcollectionOfWithRelationToFn).
xc_indexed_constant(a65b126a21e4d1,x_objectTypeReplaced).
xc_indexed_constant(a65b126a21e4d1,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4d2,'x_Clothing-Bottom').
xc_indexed_constant(a65b126a21e4d2,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d2,x_ReplacingSomething).
xc_indexed_constant(a65b126a21e4d2,x_SubcollectionOfWithRelationToFn).
xc_indexed_constant(a65b126a21e4d2,x_WashingHands).
xc_indexed_constant(a65b126a21e4d2,x_objectTypeReplaced).
xc_indexed_constant(a65b126a21e4d2,x_startsAfterEndOfInSituationType).
xc_indexed_constant(a65b126a21e4d3,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d3,'x_Movement-TranslationEvent').
xc_indexed_constant(a65b126a21e4d3,x_Restroom).
xc_indexed_constant(a65b126a21e4d3,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4d3,x_doneBy).
xc_indexed_constant(a65b126a21e4d3,x_inheritRolePlayers).
xc_indexed_constant(a65b126a21e4d3,x_toLocation).
xc_indexed_constant(a65b126a21e4d4,'x_Clothing-Bottom').
xc_indexed_constant(a65b126a21e4d4,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d4,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4d4,x_Undressing).
xc_indexed_constant(a65b126a21e4d4,x_doneBy).
xc_indexed_constant(a65b126a21e4d4,x_inheritRolePlayers).
xc_indexed_constant(a65b126a21e4d4,x_objectRemoved).
xc_indexed_constant(a65b126a21e4d5,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d5,x_SittingOnSomething).
xc_indexed_constant(a65b126a21e4d5,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4d5,x_ToiletSeat).
xc_indexed_constant(a65b126a21e4d5,x_doneBy).
xc_indexed_constant(a65b126a21e4d5,x_inheritRolePlayers).
xc_indexed_constant(a65b126a21e4d5,x_seat).
xc_indexed_constant(a65b126a21e4d5,x_seated).
xc_indexed_constant(a65b126a21e4d6,x_Defecating).
xc_indexed_constant(a65b126a21e4d6,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d6,x_doneBy).
xc_indexed_constant(a65b126a21e4d6,x_inheritRolePlayers).
xc_indexed_constant(a65b126a21e4d7,x_FlushingAToilet).
xc_indexed_constant(a65b126a21e4d7,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d7,x_doneBy).
xc_indexed_constant(a65b126a21e4d7,x_inheritRolePlayers).
xc_indexed_constant(a65b126a21e4d8,'x_Clothing-Bottom').
xc_indexed_constant(a65b126a21e4d8,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d8,x_ReplacingSomething).
xc_indexed_constant(a65b126a21e4d8,x_SubcollectionOfWithRelationToFn).
xc_indexed_constant(a65b126a21e4d8,x_doneBy).
xc_indexed_constant(a65b126a21e4d8,x_inheritRolePlayers).
xc_indexed_constant(a65b126a21e4d8,x_objectTypeReplaced).
xc_indexed_constant(a65b126a21e4d9,x_GoingToTheBathroom).
xc_indexed_constant(a65b126a21e4d9,x_WashingHands).
xc_indexed_constant(a65b126a21e4d9,x_doneBy).
xc_indexed_constant(a65b126a21e4d9,x_inheritRolePlayers).
xc_indexed_constant(a65b126a21e4da,x_Folding).
xc_indexed_constant(a65b126a21e4da,x_MakingFn).
xc_indexed_constant(a65b126a21e4da,x_PaperAirplane).
xc_indexed_constant(a65b126a21e4da,x_SheetOfPaper).
xc_indexed_constant(a65b126a21e4da,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4da,x_objectFolded).
xc_indexed_constant(a65b126a21e4da,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4db,x_Compressing).
xc_indexed_constant(a65b126a21e4db,x_MakingFn).
xc_indexed_constant(a65b126a21e4db,x_SnowMob).
xc_indexed_constant(a65b126a21e4db,x_Snowball).
xc_indexed_constant(a65b126a21e4db,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4db,x_objectActedOn).
xc_indexed_constant(a65b126a21e4db,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4dc,x_JumpingRope).
xc_indexed_constant(a65b126a21e4dc,x_JumpingUpAndDown).
xc_indexed_constant(a65b126a21e4dc,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4dd,x_JumpRope).
xc_indexed_constant(a65b126a21e4dd,x_JumpingRope).
xc_indexed_constant(a65b126a21e4dd,'x_Rotation-Periodic').
xc_indexed_constant(a65b126a21e4dd,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4dd,x_objectRotating).
xc_indexed_constant(a65b126a21e4dd,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4de,x_JumpRope).
xc_indexed_constant(a65b126a21e4de,x_JumpingOverSomething).
xc_indexed_constant(a65b126a21e4de,x_JumpingRope).
xc_indexed_constant(a65b126a21e4de,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b126a21e4de,x_objectHurdled).
xc_indexed_constant(a65b126a21e4de,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4df,x_FirstOrderCollection).
xc_indexed_constant(a65b126a21e4df,x_SpellingBee).
xc_indexed_constant(a65b126a21e4df,x_isa).
xc_indexed_constant(a65b126a21e4e0,x_SpellingBee).
xc_indexed_constant(a65b126a21e4e0,x_TemporalStuffType).
xc_indexed_constant(a65b126a21e4e0,x_isa).
xc_indexed_constant(a65b126a21e4e1,x_DurativeEventType).
xc_indexed_constant(a65b126a21e4e1,x_SpellingBee).
xc_indexed_constant(a65b126a21e4e1,x_isa).
xc_indexed_constant(a65b126a21e4e2,x_CompetitionEventTypeFn).
xc_indexed_constant(a65b126a21e4e2,x_Spelling).
xc_indexed_constant(a65b126a21e4e2,x_SpellingBee).
xc_indexed_constant(a65b126a21e4e2,x_genls).
xc_indexed_constant(a65b126a21e4e3,x_CollectionIntersection2Fn).
xc_indexed_constant(a65b126a21e4e3,x_HumanChild).
xc_indexed_constant(a65b126a21e4e3,x_SpellingBee).
xc_indexed_constant(a65b126a21e4e3,x_Student).
xc_indexed_constant(a65b126a21e4e3,x_competingAgents).
xc_indexed_constant(a65b126a21e4e3,x_relationAllOnly).
xc_indexed_constant(a65b126a21e4e4,x_SpellingBee).
xc_indexed_constant(a65b126a21e4e4,x_comment).
xc_indexed_constant(a65b126a21e4e5,x_WeddingCeremony).
xc_indexed_constant(a65b126a21e4e5,'x_WeddingEvent-Entire').
xc_indexed_constant(a65b126a21e4e5,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4e6,x_WalkingDownTheAisle).
xc_indexed_constant(a65b126a21e4e6,x_WeddingCeremony).
xc_indexed_constant(a65b126a21e4e6,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4e7,x_BrideAndGroomStandBeforeOfficiant).
xc_indexed_constant(a65b126a21e4e7,x_WeddingCeremony).
xc_indexed_constant(a65b126a21e4e7,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4e8,x_CeremonialExchangeOfWeddingRings).
xc_indexed_constant(a65b126a21e4e8,x_WeddingCeremony).
xc_indexed_constant(a65b126a21e4e8,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4e9,'x_WeddingEvent-Entire').
xc_indexed_constant(a65b126a21e4e9,x_WeddingReception).
xc_indexed_constant(a65b126a21e4e9,x_properSubEventTypes).
xc_indexed_constant(a65b126a21e4ea,'x_DriversLicense-LicenseAgreement').
xc_indexed_constant(a65b126a21e4ea,x_RoadVehicle).
xc_indexed_constant(a65b126a21e4ea,x_TransportViaFn).
xc_indexed_constant(a65b126a21e4ea,x_licenseFor).
xc_indexed_constant(a65b126a21e4ea,x_relationExistsMost).
xc_indexed_constant(a65b126a21e4eb,x_Airplane).
xc_indexed_constant(a65b126a21e4eb,x_FlyingLicense).
xc_indexed_constant(a65b126a21e4eb,x_TransportViaFn).
xc_indexed_constant(a65b126a21e4eb,x_licenseFor).
xc_indexed_constant(a65b126a21e4eb,x_relationExistsMost).
xc_indexed_constant(a65b126a21e4ec,'x_Train-TransportationDevice').
xc_indexed_constant(a65b126a21e4ec,x_TrainEngineerLicense).
xc_indexed_constant(a65b126a21e4ec,x_TransportViaFn).
xc_indexed_constant(a65b126a21e4ec,x_licenseFor).
xc_indexed_constant(a65b126a21e4ec,x_relationExistsMost).
kb_index_footer(106,bb04651645714c53cf8d64ffe689505d3029b213b570f8c524a338993159a2f1,'9080e4b076c84e5d676dab0decd28a378b8f84dfbc3bd60640942c194965e905').
