kb_index_header(index_header{count:56,digest:'26f1396e1dd1259919c7789c4ddd7cb29a2356d57aa8959269beb6daa383ea7c',normalizedDigest:'0a32fb812630256442183d5cef03fa851ac83aaa8961bed69711203d1f01ede0',normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',sourceHash:'66eab3294bb56c5e5644ffbc6c01b31400a00f7c9cc46ecfd1dda021c9a2d725'}).
kb_index_data(index{constants:[-(x_BlueColor,4),-('x_BrilliantBlue-Color',4),-('x_BrilliantGreen-Color',4),-('x_BrilliantOrange-Color',4),-('x_BrilliantPurple-Color',4),-('x_BrilliantViolet-Color',4),-('x_BrilliantYellow-Color',4),-(x_ChromaticColor,1),-(x_GreenColor,4),-(x_MappingDisplayColor,16),-(x_OrangeColor,5),-('x_PaleGreen-Color',4),-('x_PalePink-Color',4),-('x_PaleYellow-Color',4),-(x_PurpleColor,4),-(x_SecondOrderCollection,1),-(x_colorHasRGBBlueValue,13),-(x_colorHasRGBGreenValue,13),-(x_colorHasRGBRedValue,14),-(x_comment,1),-(x_genls,1),-(x_isa,14)],entries:[entry(a65b125c8aa140,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',18,[x_MappingDisplayColor,x_SecondOrderCollection,x_isa]),entry(a65b125c8aa141,signature(x_genls,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',19,[x_ChromaticColor,x_MappingDisplayColor,x_genls]),entry(a65b125c8aa142,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',20,[x_MappingDisplayColor,x_comment]),entry(a65b125c8aa143,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',24,[x_MappingDisplayColor,x_OrangeColor,x_isa]),entry(a65b125c8aa144,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',25,[x_GreenColor,x_MappingDisplayColor,x_isa]),entry(a65b125c8aa145,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',26,[x_BlueColor,x_MappingDisplayColor,x_isa]),entry(a65b125c8aa146,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',27,[x_MappingDisplayColor,x_PurpleColor,x_isa]),entry(a65b125c8aa147,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',28,['x_BrilliantBlue-Color',x_MappingDisplayColor,x_isa]),entry(a65b125c8aa148,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',29,['x_BrilliantGreen-Color',x_MappingDisplayColor,x_isa]),entry(a65b125c8aa149,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',30,['x_BrilliantYellow-Color',x_MappingDisplayColor,x_isa]),entry(a65b125c8aa14a,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',31,['x_BrilliantViolet-Color',x_MappingDisplayColor,x_isa]),entry(a65b125c8aa14b,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',32,['x_BrilliantOrange-Color',x_MappingDisplayColor,x_isa]),entry(a65b125c8aa14c,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',33,['x_BrilliantPurple-Color',x_MappingDisplayColor,x_isa]),entry(a65b125c8aa14d,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',34,[x_MappingDisplayColor,'x_PaleGreen-Color',x_isa]),entry(a65b125c8aa14e,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',35,[x_MappingDisplayColor,'x_PalePink-Color',x_isa]),entry(a65b125c8aa14f,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',36,[x_MappingDisplayColor,'x_PaleYellow-Color',x_isa]),entry(a65b125c8aa150,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',42,[x_OrangeColor,x_colorHasRGBGreenValue]),entry(a65b125c8aa151,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',43,[x_GreenColor,x_colorHasRGBGreenValue]),entry(a65b125c8aa152,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',44,[x_BlueColor,x_colorHasRGBGreenValue]),entry(a65b125c8aa153,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',45,[x_PurpleColor,x_colorHasRGBGreenValue]),entry(a65b125c8aa154,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',46,['x_BrilliantBlue-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa155,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',47,['x_BrilliantGreen-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa156,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',48,['x_BrilliantYellow-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa157,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',49,['x_BrilliantViolet-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa158,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',50,['x_BrilliantOrange-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa159,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',51,['x_BrilliantPurple-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa15a,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',52,['x_PaleGreen-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa15b,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',53,['x_PalePink-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa15c,signature(x_colorHasRGBGreenValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',54,['x_PaleYellow-Color',x_colorHasRGBGreenValue]),entry(a65b125c8aa15d,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',56,['x_PaleYellow-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa15e,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',57,['x_PalePink-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa15f,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',58,['x_PaleGreen-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa160,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',59,['x_BrilliantPurple-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa161,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',60,['x_BrilliantOrange-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa162,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',61,['x_BrilliantViolet-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa163,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',62,['x_BrilliantYellow-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa164,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',63,['x_BrilliantGreen-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa165,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',64,['x_BrilliantBlue-Color',x_colorHasRGBRedValue]),entry(a65b125c8aa166,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',65,[x_PurpleColor,x_colorHasRGBRedValue]),entry(a65b125c8aa167,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',66,[x_BlueColor,x_colorHasRGBRedValue]),entry(a65b125c8aa168,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',67,[x_GreenColor,x_colorHasRGBRedValue]),entry(a65b125c8aa169,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',68,[x_OrangeColor,x_colorHasRGBRedValue]),entry(a65b125c8aa16a,signature(x_colorHasRGBRedValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',70,[x_OrangeColor,x_colorHasRGBRedValue]),entry(a65b125c8aa16b,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',70,['x_PaleYellow-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa16c,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',71,['x_PalePink-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa16d,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',72,['x_PaleGreen-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa16e,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',73,['x_BrilliantPurple-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa16f,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',74,['x_BrilliantOrange-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa170,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',75,['x_BrilliantViolet-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa171,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',76,['x_BrilliantYellow-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa172,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',77,['x_BrilliantGreen-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa173,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',78,['x_BrilliantBlue-Color',x_colorHasRGBBlueValue]),entry(a65b125c8aa174,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',79,[x_PurpleColor,x_colorHasRGBBlueValue]),entry(a65b125c8aa175,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',80,[x_BlueColor,x_colorHasRGBBlueValue]),entry(a65b125c8aa176,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',81,[x_GreenColor,x_colorHasRGBBlueValue]),entry(a65b125c8aa177,signature(x_colorHasRGBBlueValue,2),x_NaivePhysicsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf',82,[x_OrangeColor,x_colorHasRGBBlueValue])],predicates:[-(signature(x_colorHasRGBBlueValue,2),13),-(signature(x_colorHasRGBGreenValue,2),13),-(signature(x_colorHasRGBRedValue,2),14),-(signature(x_comment,2),1),-(signature(x_genls,2),1),-(signature(x_isa,2),14)],rankedConstants:[-(16,x_MappingDisplayColor),-(14,x_isa),-(14,x_colorHasRGBRedValue),-(13,x_colorHasRGBGreenValue),-(13,x_colorHasRGBBlueValue),-(5,x_OrangeColor),-(4,x_PurpleColor),-(4,'x_PaleYellow-Color'),-(4,'x_PalePink-Color'),-(4,'x_PaleGreen-Color'),-(4,x_GreenColor),-(4,'x_BrilliantYellow-Color'),-(4,'x_BrilliantViolet-Color'),-(4,'x_BrilliantPurple-Color'),-(4,'x_BrilliantOrange-Color'),-(4,'x_BrilliantGreen-Color'),-(4,'x_BrilliantBlue-Color'),-(4,x_BlueColor),-(1,x_genls),-(1,x_comment),-(1,x_SecondOrderCollection),-(1,x_ChromaticColor)],rankedPredicates:[-(14,signature(x_isa,2)),-(14,signature(x_colorHasRGBRedValue,2)),-(13,signature(x_colorHasRGBGreenValue,2)),-(13,signature(x_colorHasRGBBlueValue,2)),-(1,signature(x_genls,2)),-(1,signature(x_comment,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/colors.krf'}).
xc_indexed_constant(a65b125c8aa140,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa140,x_SecondOrderCollection).
xc_indexed_constant(a65b125c8aa140,x_isa).
xc_indexed_constant(a65b125c8aa141,x_ChromaticColor).
xc_indexed_constant(a65b125c8aa141,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa141,x_genls).
xc_indexed_constant(a65b125c8aa142,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa142,x_comment).
xc_indexed_constant(a65b125c8aa143,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa143,x_OrangeColor).
xc_indexed_constant(a65b125c8aa143,x_isa).
xc_indexed_constant(a65b125c8aa144,x_GreenColor).
xc_indexed_constant(a65b125c8aa144,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa144,x_isa).
xc_indexed_constant(a65b125c8aa145,x_BlueColor).
xc_indexed_constant(a65b125c8aa145,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa145,x_isa).
xc_indexed_constant(a65b125c8aa146,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa146,x_PurpleColor).
xc_indexed_constant(a65b125c8aa146,x_isa).
xc_indexed_constant(a65b125c8aa147,'x_BrilliantBlue-Color').
xc_indexed_constant(a65b125c8aa147,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa147,x_isa).
xc_indexed_constant(a65b125c8aa148,'x_BrilliantGreen-Color').
xc_indexed_constant(a65b125c8aa148,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa148,x_isa).
xc_indexed_constant(a65b125c8aa149,'x_BrilliantYellow-Color').
xc_indexed_constant(a65b125c8aa149,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa149,x_isa).
xc_indexed_constant(a65b125c8aa14a,'x_BrilliantViolet-Color').
xc_indexed_constant(a65b125c8aa14a,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa14a,x_isa).
xc_indexed_constant(a65b125c8aa14b,'x_BrilliantOrange-Color').
xc_indexed_constant(a65b125c8aa14b,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa14b,x_isa).
xc_indexed_constant(a65b125c8aa14c,'x_BrilliantPurple-Color').
xc_indexed_constant(a65b125c8aa14c,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa14c,x_isa).
xc_indexed_constant(a65b125c8aa14d,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa14d,'x_PaleGreen-Color').
xc_indexed_constant(a65b125c8aa14d,x_isa).
xc_indexed_constant(a65b125c8aa14e,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa14e,'x_PalePink-Color').
xc_indexed_constant(a65b125c8aa14e,x_isa).
xc_indexed_constant(a65b125c8aa14f,x_MappingDisplayColor).
xc_indexed_constant(a65b125c8aa14f,'x_PaleYellow-Color').
xc_indexed_constant(a65b125c8aa14f,x_isa).
xc_indexed_constant(a65b125c8aa150,x_OrangeColor).
xc_indexed_constant(a65b125c8aa150,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa151,x_GreenColor).
xc_indexed_constant(a65b125c8aa151,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa152,x_BlueColor).
xc_indexed_constant(a65b125c8aa152,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa153,x_PurpleColor).
xc_indexed_constant(a65b125c8aa153,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa154,'x_BrilliantBlue-Color').
xc_indexed_constant(a65b125c8aa154,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa155,'x_BrilliantGreen-Color').
xc_indexed_constant(a65b125c8aa155,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa156,'x_BrilliantYellow-Color').
xc_indexed_constant(a65b125c8aa156,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa157,'x_BrilliantViolet-Color').
xc_indexed_constant(a65b125c8aa157,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa158,'x_BrilliantOrange-Color').
xc_indexed_constant(a65b125c8aa158,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa159,'x_BrilliantPurple-Color').
xc_indexed_constant(a65b125c8aa159,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa15a,'x_PaleGreen-Color').
xc_indexed_constant(a65b125c8aa15a,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa15b,'x_PalePink-Color').
xc_indexed_constant(a65b125c8aa15b,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa15c,'x_PaleYellow-Color').
xc_indexed_constant(a65b125c8aa15c,x_colorHasRGBGreenValue).
xc_indexed_constant(a65b125c8aa15d,'x_PaleYellow-Color').
xc_indexed_constant(a65b125c8aa15d,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa15e,'x_PalePink-Color').
xc_indexed_constant(a65b125c8aa15e,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa15f,'x_PaleGreen-Color').
xc_indexed_constant(a65b125c8aa15f,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa160,'x_BrilliantPurple-Color').
xc_indexed_constant(a65b125c8aa160,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa161,'x_BrilliantOrange-Color').
xc_indexed_constant(a65b125c8aa161,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa162,'x_BrilliantViolet-Color').
xc_indexed_constant(a65b125c8aa162,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa163,'x_BrilliantYellow-Color').
xc_indexed_constant(a65b125c8aa163,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa164,'x_BrilliantGreen-Color').
xc_indexed_constant(a65b125c8aa164,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa165,'x_BrilliantBlue-Color').
xc_indexed_constant(a65b125c8aa165,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa166,x_PurpleColor).
xc_indexed_constant(a65b125c8aa166,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa167,x_BlueColor).
xc_indexed_constant(a65b125c8aa167,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa168,x_GreenColor).
xc_indexed_constant(a65b125c8aa168,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa169,x_OrangeColor).
xc_indexed_constant(a65b125c8aa169,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa16a,x_OrangeColor).
xc_indexed_constant(a65b125c8aa16a,x_colorHasRGBRedValue).
xc_indexed_constant(a65b125c8aa16b,'x_PaleYellow-Color').
xc_indexed_constant(a65b125c8aa16b,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa16c,'x_PalePink-Color').
xc_indexed_constant(a65b125c8aa16c,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa16d,'x_PaleGreen-Color').
xc_indexed_constant(a65b125c8aa16d,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa16e,'x_BrilliantPurple-Color').
xc_indexed_constant(a65b125c8aa16e,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa16f,'x_BrilliantOrange-Color').
xc_indexed_constant(a65b125c8aa16f,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa170,'x_BrilliantViolet-Color').
xc_indexed_constant(a65b125c8aa170,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa171,'x_BrilliantYellow-Color').
xc_indexed_constant(a65b125c8aa171,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa172,'x_BrilliantGreen-Color').
xc_indexed_constant(a65b125c8aa172,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa173,'x_BrilliantBlue-Color').
xc_indexed_constant(a65b125c8aa173,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa174,x_PurpleColor).
xc_indexed_constant(a65b125c8aa174,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa175,x_BlueColor).
xc_indexed_constant(a65b125c8aa175,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa176,x_GreenColor).
xc_indexed_constant(a65b125c8aa176,x_colorHasRGBBlueValue).
xc_indexed_constant(a65b125c8aa177,x_OrangeColor).
xc_indexed_constant(a65b125c8aa177,x_colorHasRGBBlueValue).
kb_index_footer(56,'26f1396e1dd1259919c7789c4ddd7cb29a2356d57aa8959269beb6daa383ea7c','07e908a74bff0449d2e0df676ad23f5506c3e80d84363c0f2117320b1b28d5cc').
