kb_index_header(index_header{count:154,digest:'86fa5caef647582a759fa409a6ff8005ba9fb8b559214805deda096ca192e1a9',normalizedDigest:'8f63e97974ecf605be8bf6322146b58d4b68ce0df267b5a8e86f9ec383241e56',normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',sourceHash:dca3ae04687b80d569f70e27469518860fbb09142235e80f9083eb05b08df5f6}).
kb_index_data(index{constants:[-(x_2DQDirection,1),-('x_<==',4),-(x_BinaryPredicate,1),-(x_Collection,1),-(x_DynamicUpdatePredicate,7),-(x_Glyph,2),-(x_InformationStore,1),-(x_InkPartitionRegion,10),-(x_List,1),-(x_NuSketchGlyph,22),-(x_NuSketchLayer,4),-(x_Number,1),-(x_Predicate,9),-(x_ProperNameString,1),-(x_QuaternaryPredicate,3),-(x_Relation,6),-('x_Set-Mathematical',1),-(x_SpatialThing,9),-(x_SubSketch,1),-(x_SubSketchGroup,1),-(x_SymmetricBinaryPredicate,1),-(x_TernaryPredicate,1),-(x_TextString,1),-(x_Thing,3),-(x_UnaryPredicate,5),-(x_annotationGlyphRepresentsObject,7),-(x_arg1Isa,26),-(x_arg2Isa,18),-(x_arg3Isa,7),-(x_arg4Isa,3),-(x_arity,26),-(x_collectionsForGlyphCreatedByInkPartitionRegion,6),-(x_comment,27),-(x_conceptualGroupGlyph,5),-(x_currentlyHighlightedGlyph,5),-(x_currentlyInvisibleSketchComponent,5),-(x_currentlyPartiallyVisibleSketchComponent,5),-(x_currentlySelectedGlyph,5),-(x_currentlyVisibleSketchComponent,5),-(x_destinationLayerForInkPartitionRegion,6),-(x_genlPreds,1),-(x_genls,1),-(x_glyphAnnotatedBy,5),-(x_glyphCreatedByInkPartitionRegion,7),-(x_glyphFromGlyphDifference,8),-(x_glyphFromGlyphIntersection,9),-(x_glyphFromGlyphUnion,8),-(x_glyphFromInkContents,6),-(x_glyphFromVisibleGlyphPartInDrawpane,7),-(x_glyphRepresentsObject,2),-(x_includeInkPartitionBoundsInGlyphCreated,4),-(x_isa,34),-(x_lookupOnly,1),-(x_makeVoronoiSensitive,4),-(x_namestringForGlyphCreatedByInkPartitionRegion,6),-(x_notForAnalogy,6),-(x_nuSketchBusyMsg,6),-(x_polyOpAdjacent,6),-(x_prettyString,1),-(x_resampleGlyph,5),-(x_sameObject,5),-(x_sourceForInkPartitionRegion,6),-(x_surfaceContactDirection,6),-(x_visibleSketchComponentsInDrawpane,5)],entries:[entry(a65b125c9ba241,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',18,[x_Predicate,x_conceptualGroupGlyph,x_isa]),entry(a65b125c9ba242,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',19,[x_arity,x_conceptualGroupGlyph]),entry(a65b125c9ba243,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',20,[x_comment,x_conceptualGroupGlyph]),entry(a65b125c9ba244,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',22,[x_NuSketchGlyph,x_arg1Isa,x_conceptualGroupGlyph]),entry(a65b125c9ba245,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',23,[x_NuSketchGlyph,x_arg2Isa,x_conceptualGroupGlyph]),entry(a65b125c9ba246,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',26,[x_Predicate,x_glyphAnnotatedBy,x_isa]),entry(a65b125c9ba247,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',27,[x_arity,x_glyphAnnotatedBy]),entry(a65b125c9ba248,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',28,[x_comment,x_glyphAnnotatedBy]),entry(a65b125c9ba249,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',30,[x_NuSketchGlyph,x_arg1Isa,x_glyphAnnotatedBy]),entry(a65b125c9ba24a,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',31,[x_NuSketchGlyph,x_arg2Isa,x_glyphAnnotatedBy]),entry(a65b125c9ba24b,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',33,[x_Predicate,x_annotationGlyphRepresentsObject,x_isa]),entry(a65b125c9ba24c,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',34,[x_annotationGlyphRepresentsObject,x_arity]),entry(a65b125c9ba24d,signature(x_genlPreds,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',35,[x_annotationGlyphRepresentsObject,x_genlPreds,x_glyphRepresentsObject]),entry(a65b125c9ba24e,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',36,[x_annotationGlyphRepresentsObject,x_comment]),entry(a65b125c9ba24f,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',38,[x_NuSketchGlyph,x_annotationGlyphRepresentsObject,x_arg1Isa]),entry(a65b125c9ba250,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',39,[x_Thing,x_annotationGlyphRepresentsObject,x_arg2Isa]),entry(a65b125c9ba251,signature('x_<==',2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',41,['x_<==',x_annotationGlyphRepresentsObject,x_glyphRepresentsObject]),entry(a65b125c9ba252,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',47,[x_Predicate,x_isa,x_sameObject]),entry(a65b125c9ba253,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',48,[x_arity,x_sameObject]),entry(a65b125c9ba254,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',49,[x_Thing,x_arg1Isa,x_sameObject]),entry(a65b125c9ba255,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',50,[x_Thing,x_arg2Isa,x_sameObject]),entry(a65b125c9ba256,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',51,[x_comment,x_sameObject]),entry(a65b125c9ba257,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',59,[x_comment,x_currentlySelectedGlyph]),entry(a65b125c9ba258,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',61,[x_DynamicUpdatePredicate,x_currentlySelectedGlyph,x_isa]),entry(a65b125c9ba259,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',62,[x_UnaryPredicate,x_currentlySelectedGlyph,x_isa]),entry(a65b125c9ba25a,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',63,[x_arity,x_currentlySelectedGlyph]),entry(a65b125c9ba25b,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',64,[x_Glyph,x_arg1Isa,x_currentlySelectedGlyph]),entry(a65b125c9ba25c,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',66,[x_comment,x_currentlyHighlightedGlyph]),entry(a65b125c9ba25d,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',68,[x_DynamicUpdatePredicate,x_currentlyHighlightedGlyph,x_isa]),entry(a65b125c9ba25e,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',69,[x_UnaryPredicate,x_currentlyHighlightedGlyph,x_isa]),entry(a65b125c9ba25f,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',70,[x_arity,x_currentlyHighlightedGlyph]),entry(a65b125c9ba260,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',71,[x_Glyph,x_arg1Isa,x_currentlyHighlightedGlyph]),entry(a65b125c9ba261,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',73,[x_comment,x_currentlyVisibleSketchComponent]),entry(a65b125c9ba262,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',75,[x_DynamicUpdatePredicate,x_currentlyVisibleSketchComponent,x_isa]),entry(a65b125c9ba263,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',76,[x_UnaryPredicate,x_currentlyVisibleSketchComponent,x_isa]),entry(a65b125c9ba264,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',77,[x_arity,x_currentlyVisibleSketchComponent]),entry(a65b125c9ba265,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',78,[x_SpatialThing,x_arg1Isa,x_currentlyVisibleSketchComponent]),entry(a65b125c9ba266,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',80,[x_comment,x_currentlyInvisibleSketchComponent]),entry(a65b125c9ba267,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',82,[x_DynamicUpdatePredicate,x_currentlyInvisibleSketchComponent,x_isa]),entry(a65b125c9ba268,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',83,[x_UnaryPredicate,x_currentlyInvisibleSketchComponent,x_isa]),entry(a65b125c9ba269,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',84,[x_arity,x_currentlyInvisibleSketchComponent]),entry(a65b125c9ba26a,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',85,[x_SpatialThing,x_arg1Isa,x_currentlyInvisibleSketchComponent]),entry(a65b125c9ba26b,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',87,[x_comment,x_currentlyPartiallyVisibleSketchComponent]),entry(a65b125c9ba26c,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',89,[x_DynamicUpdatePredicate,x_currentlyPartiallyVisibleSketchComponent,x_isa]),entry(a65b125c9ba26d,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',90,[x_UnaryPredicate,x_currentlyPartiallyVisibleSketchComponent,x_isa]),entry(a65b125c9ba26e,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',91,[x_arity,x_currentlyPartiallyVisibleSketchComponent]),entry(a65b125c9ba26f,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',92,[x_SpatialThing,x_arg1Isa,x_currentlyPartiallyVisibleSketchComponent]),entry(a65b125c9ba270,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',94,[x_BinaryPredicate,x_isa,x_nuSketchBusyMsg]),entry(a65b125c9ba271,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',95,[x_arity,x_nuSketchBusyMsg]),entry(a65b125c9ba272,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',96,[x_TextString,x_arg1Isa,x_nuSketchBusyMsg]),entry(a65b125c9ba273,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',97,[x_List,x_arg2Isa,x_nuSketchBusyMsg]),entry(a65b125c9ba274,signature(x_notForAnalogy,1),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',98,[x_notForAnalogy,x_nuSketchBusyMsg]),entry(a65b125c9ba275,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',99,[x_comment,x_nuSketchBusyMsg]),entry(a65b125c9ba276,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',109,[x_comment,x_glyphFromGlyphIntersection]),entry(a65b125c9ba277,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',111,[x_QuaternaryPredicate,x_glyphFromGlyphIntersection,x_isa]),entry(a65b125c9ba278,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',112,[x_arity,x_glyphFromGlyphIntersection]),entry(a65b125c9ba279,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',113,[x_NuSketchGlyph,x_arg1Isa,x_glyphFromGlyphIntersection]),entry(a65b125c9ba27a,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',114,[x_NuSketchGlyph,x_arg2Isa,x_glyphFromGlyphIntersection]),entry(a65b125c9ba27b,signature(x_arg3Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',115,[x_NuSketchLayer,x_arg3Isa,x_glyphFromGlyphIntersection]),entry(a65b125c9ba27c,signature(x_arg4Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',116,[x_NuSketchGlyph,x_arg4Isa,x_glyphFromGlyphIntersection]),entry(a65b125c9ba27d,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',118,[x_comment,x_glyphFromGlyphDifference]),entry(a65b125c9ba27e,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',120,[x_QuaternaryPredicate,x_glyphFromGlyphDifference,x_isa]),entry(a65b125c9ba27f,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',121,[x_arity,x_glyphFromGlyphDifference]),entry(a65b125c9ba280,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',122,[x_NuSketchGlyph,x_arg1Isa,x_glyphFromGlyphDifference]),entry(a65b125c9ba281,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',123,[x_NuSketchGlyph,x_arg2Isa,x_glyphFromGlyphDifference]),entry(a65b125c9ba282,signature(x_arg3Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',124,[x_NuSketchLayer,x_arg3Isa,x_glyphFromGlyphDifference]),entry(a65b125c9ba283,signature(x_arg4Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',125,[x_NuSketchGlyph,x_arg4Isa,x_glyphFromGlyphDifference]),entry(a65b125c9ba284,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',127,[x_comment,x_glyphFromGlyphUnion]),entry(a65b125c9ba285,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',129,[x_QuaternaryPredicate,x_glyphFromGlyphUnion,x_isa]),entry(a65b125c9ba286,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',130,[x_arity,x_glyphFromGlyphUnion]),entry(a65b125c9ba287,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',131,[x_NuSketchGlyph,x_arg1Isa,x_glyphFromGlyphUnion]),entry(a65b125c9ba288,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',132,[x_NuSketchGlyph,x_arg2Isa,x_glyphFromGlyphUnion]),entry(a65b125c9ba289,signature(x_arg3Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',133,[x_NuSketchLayer,x_arg3Isa,x_glyphFromGlyphUnion]),entry(a65b125c9ba28a,signature(x_arg4Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',134,[x_NuSketchGlyph,x_arg4Isa,x_glyphFromGlyphUnion]),entry(a65b125c9ba28b,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',136,[x_comment,x_glyphFromVisibleGlyphPartInDrawpane]),entry(a65b125c9ba28c,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',138,[x_Predicate,x_glyphFromVisibleGlyphPartInDrawpane,x_isa]),entry(a65b125c9ba28d,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',139,[x_DynamicUpdatePredicate,x_glyphFromVisibleGlyphPartInDrawpane,x_isa]),entry(a65b125c9ba28e,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',140,[x_arity,x_glyphFromVisibleGlyphPartInDrawpane]),entry(a65b125c9ba28f,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',141,[x_NuSketchGlyph,x_arg1Isa,x_glyphFromVisibleGlyphPartInDrawpane]),entry(a65b125c9ba290,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',142,[x_NuSketchLayer,x_arg2Isa,x_glyphFromVisibleGlyphPartInDrawpane]),entry(a65b125c9ba291,signature(x_arg3Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',143,[x_NuSketchGlyph,x_arg3Isa,x_glyphFromVisibleGlyphPartInDrawpane]),entry(a65b125c9ba292,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',145,[x_comment,x_visibleSketchComponentsInDrawpane]),entry(a65b125c9ba293,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',147,[x_Predicate,x_isa,x_visibleSketchComponentsInDrawpane]),entry(a65b125c9ba294,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',148,[x_DynamicUpdatePredicate,x_isa,x_visibleSketchComponentsInDrawpane]),entry(a65b125c9ba295,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',149,[x_arity,x_visibleSketchComponentsInDrawpane]),entry(a65b125c9ba296,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',150,[x_SpatialThing,x_arg1Isa,x_visibleSketchComponentsInDrawpane]),entry(a65b125c9ba297,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',153,[x_comment,x_glyphFromInkContents]),entry(a65b125c9ba298,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',155,[x_TernaryPredicate,x_glyphFromInkContents,x_isa]),entry(a65b125c9ba299,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',156,[x_arity,x_glyphFromInkContents]),entry(a65b125c9ba29a,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',157,[x_SpatialThing,x_arg1Isa,x_glyphFromInkContents]),entry(a65b125c9ba29b,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',158,[x_SpatialThing,x_arg2Isa,x_glyphFromInkContents]),entry(a65b125c9ba29c,signature(x_arg3Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',159,[x_NuSketchGlyph,x_arg3Isa,x_glyphFromInkContents]),entry(a65b125c9ba29d,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',161,[x_Collection,x_InkPartitionRegion,x_isa]),entry(a65b125c9ba29e,signature(x_genls,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',162,[x_InkPartitionRegion,x_SpatialThing,x_genls]),entry(a65b125c9ba29f,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',163,[x_InkPartitionRegion,x_comment]),entry(a65b125c9ba2a0,signature(x_prettyString,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',168,[x_InkPartitionRegion,x_prettyString]),entry(a65b125c9ba2a1,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',170,[x_Relation,x_isa,x_sourceForInkPartitionRegion]),entry(a65b125c9ba2a2,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',171,[x_arity,x_sourceForInkPartitionRegion]),entry(a65b125c9ba2a3,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',172,[x_InkPartitionRegion,x_arg1Isa,x_sourceForInkPartitionRegion]),entry(a65b125c9ba2a4,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',173,[x_InformationStore,x_arg2Isa,x_sourceForInkPartitionRegion]),entry(a65b125c9ba2a5,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',174,[x_comment,x_sourceForInkPartitionRegion]),entry(a65b125c9ba2a6,signature(x_notForAnalogy,1),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',179,[x_notForAnalogy,x_sourceForInkPartitionRegion]),entry(a65b125c9ba2a7,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',181,[x_Relation,x_destinationLayerForInkPartitionRegion,x_isa]),entry(a65b125c9ba2a8,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',182,[x_arity,x_destinationLayerForInkPartitionRegion]),entry(a65b125c9ba2a9,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',183,[x_InkPartitionRegion,x_arg1Isa,x_destinationLayerForInkPartitionRegion]),entry(a65b125c9ba2aa,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',184,[x_SubSketch,x_arg2Isa,x_destinationLayerForInkPartitionRegion]),entry(a65b125c9ba2ab,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',185,[x_comment,x_destinationLayerForInkPartitionRegion]),entry(a65b125c9ba2ac,signature(x_notForAnalogy,1),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',188,[x_destinationLayerForInkPartitionRegion,x_notForAnalogy]),entry(a65b125c9ba2ad,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',190,[x_Relation,x_collectionsForGlyphCreatedByInkPartitionRegion,x_isa]),entry(a65b125c9ba2ae,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',191,[x_arity,x_collectionsForGlyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2af,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',192,[x_InkPartitionRegion,x_arg1Isa,x_collectionsForGlyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2b0,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',193,['x_Set-Mathematical',x_arg2Isa,x_collectionsForGlyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2b1,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',194,[x_collectionsForGlyphCreatedByInkPartitionRegion,x_comment]),entry(a65b125c9ba2b2,signature(x_notForAnalogy,1),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',197,[x_collectionsForGlyphCreatedByInkPartitionRegion,x_notForAnalogy]),entry(a65b125c9ba2b3,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',199,[x_Relation,x_isa,x_namestringForGlyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2b4,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',200,[x_arity,x_namestringForGlyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2b5,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',201,[x_InkPartitionRegion,x_arg1Isa,x_namestringForGlyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2b6,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',202,[x_ProperNameString,x_arg2Isa,x_namestringForGlyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2b7,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',203,[x_comment,x_namestringForGlyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2b8,signature(x_notForAnalogy,1),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',206,[x_namestringForGlyphCreatedByInkPartitionRegion,x_notForAnalogy]),entry(a65b125c9ba2b9,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',208,[x_Relation,x_glyphCreatedByInkPartitionRegion,x_isa]),entry(a65b125c9ba2ba,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',209,[x_arity,x_glyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2bb,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',210,[x_InkPartitionRegion,x_arg1Isa,x_glyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2bc,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',211,[x_SubSketchGroup,x_arg2Isa,x_glyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2bd,signature(x_arg3Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',212,[x_NuSketchGlyph,x_arg3Isa,x_glyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2be,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',213,[x_comment,x_glyphCreatedByInkPartitionRegion]),entry(a65b125c9ba2bf,signature(x_notForAnalogy,1),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',218,[x_glyphCreatedByInkPartitionRegion,x_notForAnalogy]),entry(a65b125c9ba2c0,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',220,[x_Relation,x_includeInkPartitionBoundsInGlyphCreated,x_isa]),entry(a65b125c9ba2c1,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',221,[x_arity,x_includeInkPartitionBoundsInGlyphCreated]),entry(a65b125c9ba2c2,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',222,[x_InkPartitionRegion,x_arg1Isa,x_includeInkPartitionBoundsInGlyphCreated]),entry(a65b125c9ba2c3,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',223,[x_comment,x_includeInkPartitionBoundsInGlyphCreated]),entry(a65b125c9ba2c4,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',228,[x_comment,x_resampleGlyph]),entry(a65b125c9ba2c5,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',230,[x_Predicate,x_isa,x_resampleGlyph]),entry(a65b125c9ba2c6,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',231,[x_arity,x_resampleGlyph]),entry(a65b125c9ba2c7,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',232,[x_NuSketchGlyph,x_arg1Isa,x_resampleGlyph]),entry(a65b125c9ba2c8,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',233,[x_Number,x_arg2Isa,x_resampleGlyph]),entry(a65b125c9ba2c9,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',235,[x_comment,x_makeVoronoiSensitive]),entry(a65b125c9ba2ca,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',237,[x_Predicate,x_isa,x_makeVoronoiSensitive]),entry(a65b125c9ba2cb,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',238,[x_arity,x_makeVoronoiSensitive]),entry(a65b125c9ba2cc,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',239,[x_NuSketchGlyph,x_arg1Isa,x_makeVoronoiSensitive]),entry(a65b125c9ba2cd,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',241,[x_comment,x_surfaceContactDirection]),entry(a65b125c9ba2ce,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',243,[x_Predicate,x_isa,x_surfaceContactDirection]),entry(a65b125c9ba2cf,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',244,[x_arity,x_surfaceContactDirection]),entry(a65b125c9ba2d0,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',245,[x_SpatialThing,x_arg1Isa,x_surfaceContactDirection]),entry(a65b125c9ba2d1,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',246,[x_SpatialThing,x_arg2Isa,x_surfaceContactDirection]),entry(a65b125c9ba2d2,signature(x_arg3Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',247,[x_2DQDirection,x_arg3Isa,x_surfaceContactDirection]),entry(a65b125c9ba2d3,signature(x_comment,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',249,[x_comment,x_polyOpAdjacent]),entry(a65b125c9ba2d4,signature(x_isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',251,[x_SymmetricBinaryPredicate,x_isa,x_polyOpAdjacent]),entry(a65b125c9ba2d5,signature(x_arity,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',252,[x_arity,x_polyOpAdjacent]),entry(a65b125c9ba2d6,signature(x_arg1Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',253,[x_NuSketchGlyph,x_arg1Isa,x_polyOpAdjacent]),entry(a65b125c9ba2d7,signature(x_arg2Isa,2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',254,[x_NuSketchGlyph,x_arg2Isa,x_polyOpAdjacent]),entry(a65b125c9ba2d8,signature('x_<==',2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',256,['x_<==',x_glyphFromGlyphIntersection]),entry(a65b125c9ba2d9,signature('x_<==',2),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',259,['x_<==',x_glyphFromGlyphUnion]),entry(a65b125c9ba2da,signature('x_<==',3),x_NuSketchMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf',262,['x_<==',x_glyphFromGlyphDifference,x_glyphFromGlyphIntersection,x_lookupOnly,x_polyOpAdjacent])],predicates:[-(signature('x_<==',2),3),-(signature('x_<==',3),1),-(signature(x_arg1Isa,2),26),-(signature(x_arg2Isa,2),18),-(signature(x_arg3Isa,2),7),-(signature(x_arg4Isa,2),3),-(signature(x_arity,2),26),-(signature(x_comment,2),27),-(signature(x_genlPreds,2),1),-(signature(x_genls,2),1),-(signature(x_isa,2),34),-(signature(x_notForAnalogy,1),6),-(signature(x_prettyString,2),1)],rankedConstants:[-(34,x_isa),-(27,x_comment),-(26,x_arity),-(26,x_arg1Isa),-(22,x_NuSketchGlyph),-(18,x_arg2Isa),-(10,x_InkPartitionRegion),-(9,x_glyphFromGlyphIntersection),-(9,x_SpatialThing),-(9,x_Predicate),-(8,x_glyphFromGlyphUnion),-(8,x_glyphFromGlyphDifference),-(7,x_glyphFromVisibleGlyphPartInDrawpane),-(7,x_glyphCreatedByInkPartitionRegion),-(7,x_arg3Isa),-(7,x_annotationGlyphRepresentsObject),-(7,x_DynamicUpdatePredicate),-(6,x_surfaceContactDirection),-(6,x_sourceForInkPartitionRegion),-(6,x_polyOpAdjacent),-(6,x_nuSketchBusyMsg),-(6,x_notForAnalogy),-(6,x_namestringForGlyphCreatedByInkPartitionRegion),-(6,x_glyphFromInkContents),-(6,x_destinationLayerForInkPartitionRegion),-(6,x_collectionsForGlyphCreatedByInkPartitionRegion),-(6,x_Relation),-(5,x_visibleSketchComponentsInDrawpane),-(5,x_sameObject),-(5,x_resampleGlyph),-(5,x_glyphAnnotatedBy),-(5,x_currentlyVisibleSketchComponent),-(5,x_currentlySelectedGlyph),-(5,x_currentlyPartiallyVisibleSketchComponent),-(5,x_currentlyInvisibleSketchComponent),-(5,x_currentlyHighlightedGlyph),-(5,x_conceptualGroupGlyph),-(5,x_UnaryPredicate),-(4,x_makeVoronoiSensitive),-(4,x_includeInkPartitionBoundsInGlyphCreated),-(4,x_NuSketchLayer),-(4,'x_<=='),-(3,x_arg4Isa),-(3,x_Thing),-(3,x_QuaternaryPredicate),-(2,x_glyphRepresentsObject),-(2,x_Glyph),-(1,x_prettyString),-(1,x_lookupOnly),-(1,x_genls),-(1,x_genlPreds),-(1,x_TextString),-(1,x_TernaryPredicate),-(1,x_SymmetricBinaryPredicate),-(1,x_SubSketchGroup),-(1,x_SubSketch),-(1,'x_Set-Mathematical'),-(1,x_ProperNameString),-(1,x_Number),-(1,x_List),-(1,x_InformationStore),-(1,x_Collection),-(1,x_BinaryPredicate),-(1,x_2DQDirection)],rankedPredicates:[-(34,signature(x_isa,2)),-(27,signature(x_comment,2)),-(26,signature(x_arity,2)),-(26,signature(x_arg1Isa,2)),-(18,signature(x_arg2Isa,2)),-(7,signature(x_arg3Isa,2)),-(6,signature(x_notForAnalogy,1)),-(3,signature(x_arg4Isa,2)),-(3,signature('x_<==',2)),-(1,signature(x_prettyString,2)),-(1,signature(x_genls,2)),-(1,signature(x_genlPreds,2)),-(1,signature('x_<==',3))],source:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/misc-relations.krf'}).
xc_indexed_constant(a65b125c9ba241,x_Predicate).
xc_indexed_constant(a65b125c9ba241,x_conceptualGroupGlyph).
xc_indexed_constant(a65b125c9ba241,x_isa).
xc_indexed_constant(a65b125c9ba242,x_arity).
xc_indexed_constant(a65b125c9ba242,x_conceptualGroupGlyph).
xc_indexed_constant(a65b125c9ba243,x_comment).
xc_indexed_constant(a65b125c9ba243,x_conceptualGroupGlyph).
xc_indexed_constant(a65b125c9ba244,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba244,x_arg1Isa).
xc_indexed_constant(a65b125c9ba244,x_conceptualGroupGlyph).
xc_indexed_constant(a65b125c9ba245,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba245,x_arg2Isa).
xc_indexed_constant(a65b125c9ba245,x_conceptualGroupGlyph).
xc_indexed_constant(a65b125c9ba246,x_Predicate).
xc_indexed_constant(a65b125c9ba246,x_glyphAnnotatedBy).
xc_indexed_constant(a65b125c9ba246,x_isa).
xc_indexed_constant(a65b125c9ba247,x_arity).
xc_indexed_constant(a65b125c9ba247,x_glyphAnnotatedBy).
xc_indexed_constant(a65b125c9ba248,x_comment).
xc_indexed_constant(a65b125c9ba248,x_glyphAnnotatedBy).
xc_indexed_constant(a65b125c9ba249,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba249,x_arg1Isa).
xc_indexed_constant(a65b125c9ba249,x_glyphAnnotatedBy).
xc_indexed_constant(a65b125c9ba24a,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba24a,x_arg2Isa).
xc_indexed_constant(a65b125c9ba24a,x_glyphAnnotatedBy).
xc_indexed_constant(a65b125c9ba24b,x_Predicate).
xc_indexed_constant(a65b125c9ba24b,x_annotationGlyphRepresentsObject).
xc_indexed_constant(a65b125c9ba24b,x_isa).
xc_indexed_constant(a65b125c9ba24c,x_annotationGlyphRepresentsObject).
xc_indexed_constant(a65b125c9ba24c,x_arity).
xc_indexed_constant(a65b125c9ba24d,x_annotationGlyphRepresentsObject).
xc_indexed_constant(a65b125c9ba24d,x_genlPreds).
xc_indexed_constant(a65b125c9ba24d,x_glyphRepresentsObject).
xc_indexed_constant(a65b125c9ba24e,x_annotationGlyphRepresentsObject).
xc_indexed_constant(a65b125c9ba24e,x_comment).
xc_indexed_constant(a65b125c9ba24f,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba24f,x_annotationGlyphRepresentsObject).
xc_indexed_constant(a65b125c9ba24f,x_arg1Isa).
xc_indexed_constant(a65b125c9ba250,x_Thing).
xc_indexed_constant(a65b125c9ba250,x_annotationGlyphRepresentsObject).
xc_indexed_constant(a65b125c9ba250,x_arg2Isa).
xc_indexed_constant(a65b125c9ba251,'x_<==').
xc_indexed_constant(a65b125c9ba251,x_annotationGlyphRepresentsObject).
xc_indexed_constant(a65b125c9ba251,x_glyphRepresentsObject).
xc_indexed_constant(a65b125c9ba252,x_Predicate).
xc_indexed_constant(a65b125c9ba252,x_isa).
xc_indexed_constant(a65b125c9ba252,x_sameObject).
xc_indexed_constant(a65b125c9ba253,x_arity).
xc_indexed_constant(a65b125c9ba253,x_sameObject).
xc_indexed_constant(a65b125c9ba254,x_Thing).
xc_indexed_constant(a65b125c9ba254,x_arg1Isa).
xc_indexed_constant(a65b125c9ba254,x_sameObject).
xc_indexed_constant(a65b125c9ba255,x_Thing).
xc_indexed_constant(a65b125c9ba255,x_arg2Isa).
xc_indexed_constant(a65b125c9ba255,x_sameObject).
xc_indexed_constant(a65b125c9ba256,x_comment).
xc_indexed_constant(a65b125c9ba256,x_sameObject).
xc_indexed_constant(a65b125c9ba257,x_comment).
xc_indexed_constant(a65b125c9ba257,x_currentlySelectedGlyph).
xc_indexed_constant(a65b125c9ba258,x_DynamicUpdatePredicate).
xc_indexed_constant(a65b125c9ba258,x_currentlySelectedGlyph).
xc_indexed_constant(a65b125c9ba258,x_isa).
xc_indexed_constant(a65b125c9ba259,x_UnaryPredicate).
xc_indexed_constant(a65b125c9ba259,x_currentlySelectedGlyph).
xc_indexed_constant(a65b125c9ba259,x_isa).
xc_indexed_constant(a65b125c9ba25a,x_arity).
xc_indexed_constant(a65b125c9ba25a,x_currentlySelectedGlyph).
xc_indexed_constant(a65b125c9ba25b,x_Glyph).
xc_indexed_constant(a65b125c9ba25b,x_arg1Isa).
xc_indexed_constant(a65b125c9ba25b,x_currentlySelectedGlyph).
xc_indexed_constant(a65b125c9ba25c,x_comment).
xc_indexed_constant(a65b125c9ba25c,x_currentlyHighlightedGlyph).
xc_indexed_constant(a65b125c9ba25d,x_DynamicUpdatePredicate).
xc_indexed_constant(a65b125c9ba25d,x_currentlyHighlightedGlyph).
xc_indexed_constant(a65b125c9ba25d,x_isa).
xc_indexed_constant(a65b125c9ba25e,x_UnaryPredicate).
xc_indexed_constant(a65b125c9ba25e,x_currentlyHighlightedGlyph).
xc_indexed_constant(a65b125c9ba25e,x_isa).
xc_indexed_constant(a65b125c9ba25f,x_arity).
xc_indexed_constant(a65b125c9ba25f,x_currentlyHighlightedGlyph).
xc_indexed_constant(a65b125c9ba260,x_Glyph).
xc_indexed_constant(a65b125c9ba260,x_arg1Isa).
xc_indexed_constant(a65b125c9ba260,x_currentlyHighlightedGlyph).
xc_indexed_constant(a65b125c9ba261,x_comment).
xc_indexed_constant(a65b125c9ba261,x_currentlyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba262,x_DynamicUpdatePredicate).
xc_indexed_constant(a65b125c9ba262,x_currentlyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba262,x_isa).
xc_indexed_constant(a65b125c9ba263,x_UnaryPredicate).
xc_indexed_constant(a65b125c9ba263,x_currentlyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba263,x_isa).
xc_indexed_constant(a65b125c9ba264,x_arity).
xc_indexed_constant(a65b125c9ba264,x_currentlyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba265,x_SpatialThing).
xc_indexed_constant(a65b125c9ba265,x_arg1Isa).
xc_indexed_constant(a65b125c9ba265,x_currentlyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba266,x_comment).
xc_indexed_constant(a65b125c9ba266,x_currentlyInvisibleSketchComponent).
xc_indexed_constant(a65b125c9ba267,x_DynamicUpdatePredicate).
xc_indexed_constant(a65b125c9ba267,x_currentlyInvisibleSketchComponent).
xc_indexed_constant(a65b125c9ba267,x_isa).
xc_indexed_constant(a65b125c9ba268,x_UnaryPredicate).
xc_indexed_constant(a65b125c9ba268,x_currentlyInvisibleSketchComponent).
xc_indexed_constant(a65b125c9ba268,x_isa).
xc_indexed_constant(a65b125c9ba269,x_arity).
xc_indexed_constant(a65b125c9ba269,x_currentlyInvisibleSketchComponent).
xc_indexed_constant(a65b125c9ba26a,x_SpatialThing).
xc_indexed_constant(a65b125c9ba26a,x_arg1Isa).
xc_indexed_constant(a65b125c9ba26a,x_currentlyInvisibleSketchComponent).
xc_indexed_constant(a65b125c9ba26b,x_comment).
xc_indexed_constant(a65b125c9ba26b,x_currentlyPartiallyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba26c,x_DynamicUpdatePredicate).
xc_indexed_constant(a65b125c9ba26c,x_currentlyPartiallyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba26c,x_isa).
xc_indexed_constant(a65b125c9ba26d,x_UnaryPredicate).
xc_indexed_constant(a65b125c9ba26d,x_currentlyPartiallyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba26d,x_isa).
xc_indexed_constant(a65b125c9ba26e,x_arity).
xc_indexed_constant(a65b125c9ba26e,x_currentlyPartiallyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba26f,x_SpatialThing).
xc_indexed_constant(a65b125c9ba26f,x_arg1Isa).
xc_indexed_constant(a65b125c9ba26f,x_currentlyPartiallyVisibleSketchComponent).
xc_indexed_constant(a65b125c9ba270,x_BinaryPredicate).
xc_indexed_constant(a65b125c9ba270,x_isa).
xc_indexed_constant(a65b125c9ba270,x_nuSketchBusyMsg).
xc_indexed_constant(a65b125c9ba271,x_arity).
xc_indexed_constant(a65b125c9ba271,x_nuSketchBusyMsg).
xc_indexed_constant(a65b125c9ba272,x_TextString).
xc_indexed_constant(a65b125c9ba272,x_arg1Isa).
xc_indexed_constant(a65b125c9ba272,x_nuSketchBusyMsg).
xc_indexed_constant(a65b125c9ba273,x_List).
xc_indexed_constant(a65b125c9ba273,x_arg2Isa).
xc_indexed_constant(a65b125c9ba273,x_nuSketchBusyMsg).
xc_indexed_constant(a65b125c9ba274,x_notForAnalogy).
xc_indexed_constant(a65b125c9ba274,x_nuSketchBusyMsg).
xc_indexed_constant(a65b125c9ba275,x_comment).
xc_indexed_constant(a65b125c9ba275,x_nuSketchBusyMsg).
xc_indexed_constant(a65b125c9ba276,x_comment).
xc_indexed_constant(a65b125c9ba276,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba277,x_QuaternaryPredicate).
xc_indexed_constant(a65b125c9ba277,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba277,x_isa).
xc_indexed_constant(a65b125c9ba278,x_arity).
xc_indexed_constant(a65b125c9ba278,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba279,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba279,x_arg1Isa).
xc_indexed_constant(a65b125c9ba279,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba27a,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba27a,x_arg2Isa).
xc_indexed_constant(a65b125c9ba27a,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba27b,x_NuSketchLayer).
xc_indexed_constant(a65b125c9ba27b,x_arg3Isa).
xc_indexed_constant(a65b125c9ba27b,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba27c,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba27c,x_arg4Isa).
xc_indexed_constant(a65b125c9ba27c,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba27d,x_comment).
xc_indexed_constant(a65b125c9ba27d,x_glyphFromGlyphDifference).
xc_indexed_constant(a65b125c9ba27e,x_QuaternaryPredicate).
xc_indexed_constant(a65b125c9ba27e,x_glyphFromGlyphDifference).
xc_indexed_constant(a65b125c9ba27e,x_isa).
xc_indexed_constant(a65b125c9ba27f,x_arity).
xc_indexed_constant(a65b125c9ba27f,x_glyphFromGlyphDifference).
xc_indexed_constant(a65b125c9ba280,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba280,x_arg1Isa).
xc_indexed_constant(a65b125c9ba280,x_glyphFromGlyphDifference).
xc_indexed_constant(a65b125c9ba281,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba281,x_arg2Isa).
xc_indexed_constant(a65b125c9ba281,x_glyphFromGlyphDifference).
xc_indexed_constant(a65b125c9ba282,x_NuSketchLayer).
xc_indexed_constant(a65b125c9ba282,x_arg3Isa).
xc_indexed_constant(a65b125c9ba282,x_glyphFromGlyphDifference).
xc_indexed_constant(a65b125c9ba283,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba283,x_arg4Isa).
xc_indexed_constant(a65b125c9ba283,x_glyphFromGlyphDifference).
xc_indexed_constant(a65b125c9ba284,x_comment).
xc_indexed_constant(a65b125c9ba284,x_glyphFromGlyphUnion).
xc_indexed_constant(a65b125c9ba285,x_QuaternaryPredicate).
xc_indexed_constant(a65b125c9ba285,x_glyphFromGlyphUnion).
xc_indexed_constant(a65b125c9ba285,x_isa).
xc_indexed_constant(a65b125c9ba286,x_arity).
xc_indexed_constant(a65b125c9ba286,x_glyphFromGlyphUnion).
xc_indexed_constant(a65b125c9ba287,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba287,x_arg1Isa).
xc_indexed_constant(a65b125c9ba287,x_glyphFromGlyphUnion).
xc_indexed_constant(a65b125c9ba288,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba288,x_arg2Isa).
xc_indexed_constant(a65b125c9ba288,x_glyphFromGlyphUnion).
xc_indexed_constant(a65b125c9ba289,x_NuSketchLayer).
xc_indexed_constant(a65b125c9ba289,x_arg3Isa).
xc_indexed_constant(a65b125c9ba289,x_glyphFromGlyphUnion).
xc_indexed_constant(a65b125c9ba28a,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba28a,x_arg4Isa).
xc_indexed_constant(a65b125c9ba28a,x_glyphFromGlyphUnion).
xc_indexed_constant(a65b125c9ba28b,x_comment).
xc_indexed_constant(a65b125c9ba28b,x_glyphFromVisibleGlyphPartInDrawpane).
xc_indexed_constant(a65b125c9ba28c,x_Predicate).
xc_indexed_constant(a65b125c9ba28c,x_glyphFromVisibleGlyphPartInDrawpane).
xc_indexed_constant(a65b125c9ba28c,x_isa).
xc_indexed_constant(a65b125c9ba28d,x_DynamicUpdatePredicate).
xc_indexed_constant(a65b125c9ba28d,x_glyphFromVisibleGlyphPartInDrawpane).
xc_indexed_constant(a65b125c9ba28d,x_isa).
xc_indexed_constant(a65b125c9ba28e,x_arity).
xc_indexed_constant(a65b125c9ba28e,x_glyphFromVisibleGlyphPartInDrawpane).
xc_indexed_constant(a65b125c9ba28f,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba28f,x_arg1Isa).
xc_indexed_constant(a65b125c9ba28f,x_glyphFromVisibleGlyphPartInDrawpane).
xc_indexed_constant(a65b125c9ba290,x_NuSketchLayer).
xc_indexed_constant(a65b125c9ba290,x_arg2Isa).
xc_indexed_constant(a65b125c9ba290,x_glyphFromVisibleGlyphPartInDrawpane).
xc_indexed_constant(a65b125c9ba291,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba291,x_arg3Isa).
xc_indexed_constant(a65b125c9ba291,x_glyphFromVisibleGlyphPartInDrawpane).
xc_indexed_constant(a65b125c9ba292,x_comment).
xc_indexed_constant(a65b125c9ba292,x_visibleSketchComponentsInDrawpane).
xc_indexed_constant(a65b125c9ba293,x_Predicate).
xc_indexed_constant(a65b125c9ba293,x_isa).
xc_indexed_constant(a65b125c9ba293,x_visibleSketchComponentsInDrawpane).
xc_indexed_constant(a65b125c9ba294,x_DynamicUpdatePredicate).
xc_indexed_constant(a65b125c9ba294,x_isa).
xc_indexed_constant(a65b125c9ba294,x_visibleSketchComponentsInDrawpane).
xc_indexed_constant(a65b125c9ba295,x_arity).
xc_indexed_constant(a65b125c9ba295,x_visibleSketchComponentsInDrawpane).
xc_indexed_constant(a65b125c9ba296,x_SpatialThing).
xc_indexed_constant(a65b125c9ba296,x_arg1Isa).
xc_indexed_constant(a65b125c9ba296,x_visibleSketchComponentsInDrawpane).
xc_indexed_constant(a65b125c9ba297,x_comment).
xc_indexed_constant(a65b125c9ba297,x_glyphFromInkContents).
xc_indexed_constant(a65b125c9ba298,x_TernaryPredicate).
xc_indexed_constant(a65b125c9ba298,x_glyphFromInkContents).
xc_indexed_constant(a65b125c9ba298,x_isa).
xc_indexed_constant(a65b125c9ba299,x_arity).
xc_indexed_constant(a65b125c9ba299,x_glyphFromInkContents).
xc_indexed_constant(a65b125c9ba29a,x_SpatialThing).
xc_indexed_constant(a65b125c9ba29a,x_arg1Isa).
xc_indexed_constant(a65b125c9ba29a,x_glyphFromInkContents).
xc_indexed_constant(a65b125c9ba29b,x_SpatialThing).
xc_indexed_constant(a65b125c9ba29b,x_arg2Isa).
xc_indexed_constant(a65b125c9ba29b,x_glyphFromInkContents).
xc_indexed_constant(a65b125c9ba29c,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba29c,x_arg3Isa).
xc_indexed_constant(a65b125c9ba29c,x_glyphFromInkContents).
xc_indexed_constant(a65b125c9ba29d,x_Collection).
xc_indexed_constant(a65b125c9ba29d,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba29d,x_isa).
xc_indexed_constant(a65b125c9ba29e,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba29e,x_SpatialThing).
xc_indexed_constant(a65b125c9ba29e,x_genls).
xc_indexed_constant(a65b125c9ba29f,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba29f,x_comment).
xc_indexed_constant(a65b125c9ba2a0,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a0,x_prettyString).
xc_indexed_constant(a65b125c9ba2a1,x_Relation).
xc_indexed_constant(a65b125c9ba2a1,x_isa).
xc_indexed_constant(a65b125c9ba2a1,x_sourceForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a2,x_arity).
xc_indexed_constant(a65b125c9ba2a2,x_sourceForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a3,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a3,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2a3,x_sourceForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a4,x_InformationStore).
xc_indexed_constant(a65b125c9ba2a4,x_arg2Isa).
xc_indexed_constant(a65b125c9ba2a4,x_sourceForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a5,x_comment).
xc_indexed_constant(a65b125c9ba2a5,x_sourceForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a6,x_notForAnalogy).
xc_indexed_constant(a65b125c9ba2a6,x_sourceForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a7,x_Relation).
xc_indexed_constant(a65b125c9ba2a7,x_destinationLayerForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a7,x_isa).
xc_indexed_constant(a65b125c9ba2a8,x_arity).
xc_indexed_constant(a65b125c9ba2a8,x_destinationLayerForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a9,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba2a9,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2a9,x_destinationLayerForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2aa,x_SubSketch).
xc_indexed_constant(a65b125c9ba2aa,x_arg2Isa).
xc_indexed_constant(a65b125c9ba2aa,x_destinationLayerForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2ab,x_comment).
xc_indexed_constant(a65b125c9ba2ab,x_destinationLayerForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2ac,x_destinationLayerForInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2ac,x_notForAnalogy).
xc_indexed_constant(a65b125c9ba2ad,x_Relation).
xc_indexed_constant(a65b125c9ba2ad,x_collectionsForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2ad,x_isa).
xc_indexed_constant(a65b125c9ba2ae,x_arity).
xc_indexed_constant(a65b125c9ba2ae,x_collectionsForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2af,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba2af,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2af,x_collectionsForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b0,'x_Set-Mathematical').
xc_indexed_constant(a65b125c9ba2b0,x_arg2Isa).
xc_indexed_constant(a65b125c9ba2b0,x_collectionsForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b1,x_collectionsForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b1,x_comment).
xc_indexed_constant(a65b125c9ba2b2,x_collectionsForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b2,x_notForAnalogy).
xc_indexed_constant(a65b125c9ba2b3,x_Relation).
xc_indexed_constant(a65b125c9ba2b3,x_isa).
xc_indexed_constant(a65b125c9ba2b3,x_namestringForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b4,x_arity).
xc_indexed_constant(a65b125c9ba2b4,x_namestringForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b5,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b5,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2b5,x_namestringForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b6,x_ProperNameString).
xc_indexed_constant(a65b125c9ba2b6,x_arg2Isa).
xc_indexed_constant(a65b125c9ba2b6,x_namestringForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b7,x_comment).
xc_indexed_constant(a65b125c9ba2b7,x_namestringForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b8,x_namestringForGlyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b8,x_notForAnalogy).
xc_indexed_constant(a65b125c9ba2b9,x_Relation).
xc_indexed_constant(a65b125c9ba2b9,x_glyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2b9,x_isa).
xc_indexed_constant(a65b125c9ba2ba,x_arity).
xc_indexed_constant(a65b125c9ba2ba,x_glyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2bb,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba2bb,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2bb,x_glyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2bc,x_SubSketchGroup).
xc_indexed_constant(a65b125c9ba2bc,x_arg2Isa).
xc_indexed_constant(a65b125c9ba2bc,x_glyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2bd,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba2bd,x_arg3Isa).
xc_indexed_constant(a65b125c9ba2bd,x_glyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2be,x_comment).
xc_indexed_constant(a65b125c9ba2be,x_glyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2bf,x_glyphCreatedByInkPartitionRegion).
xc_indexed_constant(a65b125c9ba2bf,x_notForAnalogy).
xc_indexed_constant(a65b125c9ba2c0,x_Relation).
xc_indexed_constant(a65b125c9ba2c0,x_includeInkPartitionBoundsInGlyphCreated).
xc_indexed_constant(a65b125c9ba2c0,x_isa).
xc_indexed_constant(a65b125c9ba2c1,x_arity).
xc_indexed_constant(a65b125c9ba2c1,x_includeInkPartitionBoundsInGlyphCreated).
xc_indexed_constant(a65b125c9ba2c2,x_InkPartitionRegion).
xc_indexed_constant(a65b125c9ba2c2,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2c2,x_includeInkPartitionBoundsInGlyphCreated).
xc_indexed_constant(a65b125c9ba2c3,x_comment).
xc_indexed_constant(a65b125c9ba2c3,x_includeInkPartitionBoundsInGlyphCreated).
xc_indexed_constant(a65b125c9ba2c4,x_comment).
xc_indexed_constant(a65b125c9ba2c4,x_resampleGlyph).
xc_indexed_constant(a65b125c9ba2c5,x_Predicate).
xc_indexed_constant(a65b125c9ba2c5,x_isa).
xc_indexed_constant(a65b125c9ba2c5,x_resampleGlyph).
xc_indexed_constant(a65b125c9ba2c6,x_arity).
xc_indexed_constant(a65b125c9ba2c6,x_resampleGlyph).
xc_indexed_constant(a65b125c9ba2c7,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba2c7,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2c7,x_resampleGlyph).
xc_indexed_constant(a65b125c9ba2c8,x_Number).
xc_indexed_constant(a65b125c9ba2c8,x_arg2Isa).
xc_indexed_constant(a65b125c9ba2c8,x_resampleGlyph).
xc_indexed_constant(a65b125c9ba2c9,x_comment).
xc_indexed_constant(a65b125c9ba2c9,x_makeVoronoiSensitive).
xc_indexed_constant(a65b125c9ba2ca,x_Predicate).
xc_indexed_constant(a65b125c9ba2ca,x_isa).
xc_indexed_constant(a65b125c9ba2ca,x_makeVoronoiSensitive).
xc_indexed_constant(a65b125c9ba2cb,x_arity).
xc_indexed_constant(a65b125c9ba2cb,x_makeVoronoiSensitive).
xc_indexed_constant(a65b125c9ba2cc,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba2cc,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2cc,x_makeVoronoiSensitive).
xc_indexed_constant(a65b125c9ba2cd,x_comment).
xc_indexed_constant(a65b125c9ba2cd,x_surfaceContactDirection).
xc_indexed_constant(a65b125c9ba2ce,x_Predicate).
xc_indexed_constant(a65b125c9ba2ce,x_isa).
xc_indexed_constant(a65b125c9ba2ce,x_surfaceContactDirection).
xc_indexed_constant(a65b125c9ba2cf,x_arity).
xc_indexed_constant(a65b125c9ba2cf,x_surfaceContactDirection).
xc_indexed_constant(a65b125c9ba2d0,x_SpatialThing).
xc_indexed_constant(a65b125c9ba2d0,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2d0,x_surfaceContactDirection).
xc_indexed_constant(a65b125c9ba2d1,x_SpatialThing).
xc_indexed_constant(a65b125c9ba2d1,x_arg2Isa).
xc_indexed_constant(a65b125c9ba2d1,x_surfaceContactDirection).
xc_indexed_constant(a65b125c9ba2d2,x_2DQDirection).
xc_indexed_constant(a65b125c9ba2d2,x_arg3Isa).
xc_indexed_constant(a65b125c9ba2d2,x_surfaceContactDirection).
xc_indexed_constant(a65b125c9ba2d3,x_comment).
xc_indexed_constant(a65b125c9ba2d3,x_polyOpAdjacent).
xc_indexed_constant(a65b125c9ba2d4,x_SymmetricBinaryPredicate).
xc_indexed_constant(a65b125c9ba2d4,x_isa).
xc_indexed_constant(a65b125c9ba2d4,x_polyOpAdjacent).
xc_indexed_constant(a65b125c9ba2d5,x_arity).
xc_indexed_constant(a65b125c9ba2d5,x_polyOpAdjacent).
xc_indexed_constant(a65b125c9ba2d6,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba2d6,x_arg1Isa).
xc_indexed_constant(a65b125c9ba2d6,x_polyOpAdjacent).
xc_indexed_constant(a65b125c9ba2d7,x_NuSketchGlyph).
xc_indexed_constant(a65b125c9ba2d7,x_arg2Isa).
xc_indexed_constant(a65b125c9ba2d7,x_polyOpAdjacent).
xc_indexed_constant(a65b125c9ba2d8,'x_<==').
xc_indexed_constant(a65b125c9ba2d8,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba2d9,'x_<==').
xc_indexed_constant(a65b125c9ba2d9,x_glyphFromGlyphUnion).
xc_indexed_constant(a65b125c9ba2da,'x_<==').
xc_indexed_constant(a65b125c9ba2da,x_glyphFromGlyphDifference).
xc_indexed_constant(a65b125c9ba2da,x_glyphFromGlyphIntersection).
xc_indexed_constant(a65b125c9ba2da,x_lookupOnly).
xc_indexed_constant(a65b125c9ba2da,x_polyOpAdjacent).
kb_index_footer(154,'86fa5caef647582a759fa409a6ff8005ba9fb8b559214805deda096ca192e1a9','4c3e734b20b36fd4a5d901a7584c86a8e7d5d1d06f8822e6b0372013260fd727').
