kb_index_header(index_header{count:66,digest:'1484e7aa5e8d29a5b0e2dd7936be8c717bd879cf98bf8e6713a7076929eaab3b',normalizedDigest:cafecb0075e8b237ec76308f66a18fd9a8f6a494306385f929da566eafaaac27,normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',sourceHash:f24ba4896291da91f23a57a1994fa0ee056a5f94a14351b99bac7e08f6470496}).
kb_index_data(index{constants:[-(x_BinaryPredicate,6),-(x_Collection,1),-(x_CycLSentence,1),-(x_Entity,4),-(x_Integer,7),-(x_List,4),-(x_NotForAnalogyPredicate,1),-(x_NuSketchCase,1),-(x_NuSketchSketch,1),-(x_NuSketchTutorialSketch,3),-(x_String,1),-(x_Thing,2),-(x_UnaryPredicate,8),-(x_arg1Isa,14),-(x_arg2Isa,6),-(x_arity,14),-(x_comment,2),-(x_feedbackRequestedOnTutorialStep,4),-(x_genls,1),-(x_glyphCreatedOnTutorialStep,4),-(x_glyphEditedOnTutorialStep,5),-(x_glyphSegmentedOnTutorialStep,5),-(x_holdsOnTutorialStep,5),-(x_isa,16),-(x_notForAnalogy,13),-(x_nuSketchTutorialAutorunDisabled,5),-(x_nuSketchTutorialAutorunDisabledForStep,4),-(x_nuSketchTutorialName,4),-(x_nuSketchTutorialStepActions,5),-(x_nuSketchTutorialStepConditions,5),-(x_nuSketchTutorialStepContent,5),-(x_nuSketchTutorialVarsToBind,4),-(x_sentenceAddedOnTutorialStep,4),-(x_subsketchCreatedOnTutorialStep,4)],entries:[entry(a65b125ca0ef92,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',19,[x_UnaryPredicate,x_isa,x_nuSketchTutorialAutorunDisabled]),entry(a65b125ca0ef93,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',20,[x_arity,x_nuSketchTutorialAutorunDisabled]),entry(a65b125ca0ef94,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',21,[x_NuSketchCase,x_arg1Isa,x_nuSketchTutorialAutorunDisabled]),entry(a65b125ca0ef95,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',22,[x_NotForAnalogyPredicate,x_isa,x_nuSketchTutorialAutorunDisabled]),entry(a65b125ca0ef96,signature(x_comment,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',23,[x_comment,x_nuSketchTutorialAutorunDisabled]),entry(a65b125ca0ef97,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',29,[x_UnaryPredicate,x_isa,x_nuSketchTutorialName]),entry(a65b125ca0ef98,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',30,[x_arity,x_nuSketchTutorialName]),entry(a65b125ca0ef99,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',31,[x_String,x_arg1Isa,x_nuSketchTutorialName]),entry(a65b125ca0ef9a,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',32,[x_notForAnalogy,x_nuSketchTutorialName]),entry(a65b125ca0ef9b,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',35,[x_UnaryPredicate,x_isa,x_nuSketchTutorialVarsToBind]),entry(a65b125ca0ef9c,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',36,[x_arity,x_nuSketchTutorialVarsToBind]),entry(a65b125ca0ef9d,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',37,[x_List,x_arg1Isa,x_nuSketchTutorialVarsToBind]),entry(a65b125ca0ef9e,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',38,[x_notForAnalogy,x_nuSketchTutorialVarsToBind]),entry(a65b125ca0ef9f,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',41,[x_Collection,x_NuSketchTutorialSketch,x_isa]),entry(a65b125ca0efa0,signature(x_genls,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',42,[x_NuSketchSketch,x_NuSketchTutorialSketch,x_genls]),entry(a65b125ca0efa1,signature(x_comment,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',43,[x_NuSketchTutorialSketch,x_comment]),entry(a65b125ca0efa2,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',51,[x_BinaryPredicate,x_isa,x_nuSketchTutorialStepContent]),entry(a65b125ca0efa3,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',52,[x_arity,x_nuSketchTutorialStepContent]),entry(a65b125ca0efa4,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',53,[x_Integer,x_arg1Isa,x_nuSketchTutorialStepContent]),entry(a65b125ca0efa5,signature(x_arg2Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',54,[x_List,x_arg2Isa,x_nuSketchTutorialStepContent]),entry(a65b125ca0efa6,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',55,[x_notForAnalogy,x_nuSketchTutorialStepContent]),entry(a65b125ca0efa7,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',58,[x_UnaryPredicate,x_isa,x_nuSketchTutorialAutorunDisabledForStep]),entry(a65b125ca0efa8,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',59,[x_arity,x_nuSketchTutorialAutorunDisabledForStep]),entry(a65b125ca0efa9,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',60,[x_Integer,x_arg1Isa,x_nuSketchTutorialAutorunDisabledForStep]),entry(a65b125ca0efaa,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',61,[x_notForAnalogy,x_nuSketchTutorialAutorunDisabledForStep]),entry(a65b125ca0efab,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',68,[x_BinaryPredicate,x_isa,x_nuSketchTutorialStepActions]),entry(a65b125ca0efac,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',69,[x_arity,x_nuSketchTutorialStepActions]),entry(a65b125ca0efad,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',70,[x_Integer,x_arg1Isa,x_nuSketchTutorialStepActions]),entry(a65b125ca0efae,signature(x_arg2Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',71,[x_List,x_arg2Isa,x_nuSketchTutorialStepActions]),entry(a65b125ca0efaf,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',72,[x_notForAnalogy,x_nuSketchTutorialStepActions]),entry(a65b125ca0efb0,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',79,[x_BinaryPredicate,x_isa,x_nuSketchTutorialStepConditions]),entry(a65b125ca0efb1,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',80,[x_arity,x_nuSketchTutorialStepConditions]),entry(a65b125ca0efb2,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',81,[x_Integer,x_arg1Isa,x_nuSketchTutorialStepConditions]),entry(a65b125ca0efb3,signature(x_arg2Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',82,[x_List,x_arg2Isa,x_nuSketchTutorialStepConditions]),entry(a65b125ca0efb4,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',83,[x_notForAnalogy,x_nuSketchTutorialStepConditions]),entry(a65b125ca0efb5,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',90,[x_UnaryPredicate,x_glyphCreatedOnTutorialStep,x_isa]),entry(a65b125ca0efb6,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',91,[x_arity,x_glyphCreatedOnTutorialStep]),entry(a65b125ca0efb7,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',92,[x_Entity,x_arg1Isa,x_glyphCreatedOnTutorialStep]),entry(a65b125ca0efb8,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',93,[x_glyphCreatedOnTutorialStep,x_notForAnalogy]),entry(a65b125ca0efb9,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',95,[x_UnaryPredicate,x_isa,x_subsketchCreatedOnTutorialStep]),entry(a65b125ca0efba,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',96,[x_arity,x_subsketchCreatedOnTutorialStep]),entry(a65b125ca0efbb,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',97,[x_Entity,x_arg1Isa,x_subsketchCreatedOnTutorialStep]),entry(a65b125ca0efbc,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',98,[x_notForAnalogy,x_subsketchCreatedOnTutorialStep]),entry(a65b125ca0efbd,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',100,[x_UnaryPredicate,x_isa,x_sentenceAddedOnTutorialStep]),entry(a65b125ca0efbe,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',101,[x_arity,x_sentenceAddedOnTutorialStep]),entry(a65b125ca0efbf,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',102,[x_Entity,x_arg1Isa,x_sentenceAddedOnTutorialStep]),entry(a65b125ca0efc0,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',103,[x_notForAnalogy,x_sentenceAddedOnTutorialStep]),entry(a65b125ca0efc1,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',105,[x_UnaryPredicate,x_feedbackRequestedOnTutorialStep,x_isa]),entry(a65b125ca0efc2,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',106,[x_arity,x_feedbackRequestedOnTutorialStep]),entry(a65b125ca0efc3,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',107,[x_Entity,x_arg1Isa,x_feedbackRequestedOnTutorialStep]),entry(a65b125ca0efc4,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',108,[x_feedbackRequestedOnTutorialStep,x_notForAnalogy]),entry(a65b125ca0efc5,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',110,[x_BinaryPredicate,x_glyphEditedOnTutorialStep,x_isa]),entry(a65b125ca0efc6,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',111,[x_arity,x_glyphEditedOnTutorialStep]),entry(a65b125ca0efc7,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',112,[x_Thing,x_arg1Isa,x_glyphEditedOnTutorialStep]),entry(a65b125ca0efc8,signature(x_arg2Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',113,[x_Integer,x_arg2Isa,x_glyphEditedOnTutorialStep]),entry(a65b125ca0efc9,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',114,[x_glyphEditedOnTutorialStep,x_notForAnalogy]),entry(a65b125ca0efca,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',116,[x_BinaryPredicate,x_glyphSegmentedOnTutorialStep,x_isa]),entry(a65b125ca0efcb,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',117,[x_arity,x_glyphSegmentedOnTutorialStep]),entry(a65b125ca0efcc,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',118,[x_Thing,x_arg1Isa,x_glyphSegmentedOnTutorialStep]),entry(a65b125ca0efcd,signature(x_arg2Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',119,[x_Integer,x_arg2Isa,x_glyphSegmentedOnTutorialStep]),entry(a65b125ca0efce,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',120,[x_glyphSegmentedOnTutorialStep,x_notForAnalogy]),entry(a65b125ca0efcf,signature(x_isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',122,[x_BinaryPredicate,x_holdsOnTutorialStep,x_isa]),entry(a65b125ca0efd0,signature(x_arity,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',123,[x_arity,x_holdsOnTutorialStep]),entry(a65b125ca0efd1,signature(x_arg1Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',124,[x_Integer,x_arg1Isa,x_holdsOnTutorialStep]),entry(a65b125ca0efd2,signature(x_arg2Isa,2),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',125,[x_CycLSentence,x_arg2Isa,x_holdsOnTutorialStep]),entry(a65b125ca0efd3,signature(x_notForAnalogy,1),x_NuSketchTutorialsMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf',126,[x_holdsOnTutorialStep,x_notForAnalogy])],predicates:[-(signature(x_arg1Isa,2),14),-(signature(x_arg2Isa,2),6),-(signature(x_arity,2),14),-(signature(x_comment,2),2),-(signature(x_genls,2),1),-(signature(x_isa,2),16),-(signature(x_notForAnalogy,1),13)],rankedConstants:[-(16,x_isa),-(14,x_arity),-(14,x_arg1Isa),-(13,x_notForAnalogy),-(8,x_UnaryPredicate),-(7,x_Integer),-(6,x_arg2Isa),-(6,x_BinaryPredicate),-(5,x_nuSketchTutorialStepContent),-(5,x_nuSketchTutorialStepConditions),-(5,x_nuSketchTutorialStepActions),-(5,x_nuSketchTutorialAutorunDisabled),-(5,x_holdsOnTutorialStep),-(5,x_glyphSegmentedOnTutorialStep),-(5,x_glyphEditedOnTutorialStep),-(4,x_subsketchCreatedOnTutorialStep),-(4,x_sentenceAddedOnTutorialStep),-(4,x_nuSketchTutorialVarsToBind),-(4,x_nuSketchTutorialName),-(4,x_nuSketchTutorialAutorunDisabledForStep),-(4,x_glyphCreatedOnTutorialStep),-(4,x_feedbackRequestedOnTutorialStep),-(4,x_List),-(4,x_Entity),-(3,x_NuSketchTutorialSketch),-(2,x_comment),-(2,x_Thing),-(1,x_genls),-(1,x_String),-(1,x_NuSketchSketch),-(1,x_NuSketchCase),-(1,x_NotForAnalogyPredicate),-(1,x_CycLSentence),-(1,x_Collection)],rankedPredicates:[-(16,signature(x_isa,2)),-(14,signature(x_arity,2)),-(14,signature(x_arg1Isa,2)),-(13,signature(x_notForAnalogy,1)),-(6,signature(x_arg2Isa,2)),-(2,signature(x_comment,2)),-(1,signature(x_genls,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/nusketch/tutorials.krf'}).
xc_indexed_constant(a65b125ca0ef92,x_UnaryPredicate).
xc_indexed_constant(a65b125ca0ef92,x_isa).
xc_indexed_constant(a65b125ca0ef92,x_nuSketchTutorialAutorunDisabled).
xc_indexed_constant(a65b125ca0ef93,x_arity).
xc_indexed_constant(a65b125ca0ef93,x_nuSketchTutorialAutorunDisabled).
xc_indexed_constant(a65b125ca0ef94,x_NuSketchCase).
xc_indexed_constant(a65b125ca0ef94,x_arg1Isa).
xc_indexed_constant(a65b125ca0ef94,x_nuSketchTutorialAutorunDisabled).
xc_indexed_constant(a65b125ca0ef95,x_NotForAnalogyPredicate).
xc_indexed_constant(a65b125ca0ef95,x_isa).
xc_indexed_constant(a65b125ca0ef95,x_nuSketchTutorialAutorunDisabled).
xc_indexed_constant(a65b125ca0ef96,x_comment).
xc_indexed_constant(a65b125ca0ef96,x_nuSketchTutorialAutorunDisabled).
xc_indexed_constant(a65b125ca0ef97,x_UnaryPredicate).
xc_indexed_constant(a65b125ca0ef97,x_isa).
xc_indexed_constant(a65b125ca0ef97,x_nuSketchTutorialName).
xc_indexed_constant(a65b125ca0ef98,x_arity).
xc_indexed_constant(a65b125ca0ef98,x_nuSketchTutorialName).
xc_indexed_constant(a65b125ca0ef99,x_String).
xc_indexed_constant(a65b125ca0ef99,x_arg1Isa).
xc_indexed_constant(a65b125ca0ef99,x_nuSketchTutorialName).
xc_indexed_constant(a65b125ca0ef9a,x_notForAnalogy).
xc_indexed_constant(a65b125ca0ef9a,x_nuSketchTutorialName).
xc_indexed_constant(a65b125ca0ef9b,x_UnaryPredicate).
xc_indexed_constant(a65b125ca0ef9b,x_isa).
xc_indexed_constant(a65b125ca0ef9b,x_nuSketchTutorialVarsToBind).
xc_indexed_constant(a65b125ca0ef9c,x_arity).
xc_indexed_constant(a65b125ca0ef9c,x_nuSketchTutorialVarsToBind).
xc_indexed_constant(a65b125ca0ef9d,x_List).
xc_indexed_constant(a65b125ca0ef9d,x_arg1Isa).
xc_indexed_constant(a65b125ca0ef9d,x_nuSketchTutorialVarsToBind).
xc_indexed_constant(a65b125ca0ef9e,x_notForAnalogy).
xc_indexed_constant(a65b125ca0ef9e,x_nuSketchTutorialVarsToBind).
xc_indexed_constant(a65b125ca0ef9f,x_Collection).
xc_indexed_constant(a65b125ca0ef9f,x_NuSketchTutorialSketch).
xc_indexed_constant(a65b125ca0ef9f,x_isa).
xc_indexed_constant(a65b125ca0efa0,x_NuSketchSketch).
xc_indexed_constant(a65b125ca0efa0,x_NuSketchTutorialSketch).
xc_indexed_constant(a65b125ca0efa0,x_genls).
xc_indexed_constant(a65b125ca0efa1,x_NuSketchTutorialSketch).
xc_indexed_constant(a65b125ca0efa1,x_comment).
xc_indexed_constant(a65b125ca0efa2,x_BinaryPredicate).
xc_indexed_constant(a65b125ca0efa2,x_isa).
xc_indexed_constant(a65b125ca0efa2,x_nuSketchTutorialStepContent).
xc_indexed_constant(a65b125ca0efa3,x_arity).
xc_indexed_constant(a65b125ca0efa3,x_nuSketchTutorialStepContent).
xc_indexed_constant(a65b125ca0efa4,x_Integer).
xc_indexed_constant(a65b125ca0efa4,x_arg1Isa).
xc_indexed_constant(a65b125ca0efa4,x_nuSketchTutorialStepContent).
xc_indexed_constant(a65b125ca0efa5,x_List).
xc_indexed_constant(a65b125ca0efa5,x_arg2Isa).
xc_indexed_constant(a65b125ca0efa5,x_nuSketchTutorialStepContent).
xc_indexed_constant(a65b125ca0efa6,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efa6,x_nuSketchTutorialStepContent).
xc_indexed_constant(a65b125ca0efa7,x_UnaryPredicate).
xc_indexed_constant(a65b125ca0efa7,x_isa).
xc_indexed_constant(a65b125ca0efa7,x_nuSketchTutorialAutorunDisabledForStep).
xc_indexed_constant(a65b125ca0efa8,x_arity).
xc_indexed_constant(a65b125ca0efa8,x_nuSketchTutorialAutorunDisabledForStep).
xc_indexed_constant(a65b125ca0efa9,x_Integer).
xc_indexed_constant(a65b125ca0efa9,x_arg1Isa).
xc_indexed_constant(a65b125ca0efa9,x_nuSketchTutorialAutorunDisabledForStep).
xc_indexed_constant(a65b125ca0efaa,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efaa,x_nuSketchTutorialAutorunDisabledForStep).
xc_indexed_constant(a65b125ca0efab,x_BinaryPredicate).
xc_indexed_constant(a65b125ca0efab,x_isa).
xc_indexed_constant(a65b125ca0efab,x_nuSketchTutorialStepActions).
xc_indexed_constant(a65b125ca0efac,x_arity).
xc_indexed_constant(a65b125ca0efac,x_nuSketchTutorialStepActions).
xc_indexed_constant(a65b125ca0efad,x_Integer).
xc_indexed_constant(a65b125ca0efad,x_arg1Isa).
xc_indexed_constant(a65b125ca0efad,x_nuSketchTutorialStepActions).
xc_indexed_constant(a65b125ca0efae,x_List).
xc_indexed_constant(a65b125ca0efae,x_arg2Isa).
xc_indexed_constant(a65b125ca0efae,x_nuSketchTutorialStepActions).
xc_indexed_constant(a65b125ca0efaf,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efaf,x_nuSketchTutorialStepActions).
xc_indexed_constant(a65b125ca0efb0,x_BinaryPredicate).
xc_indexed_constant(a65b125ca0efb0,x_isa).
xc_indexed_constant(a65b125ca0efb0,x_nuSketchTutorialStepConditions).
xc_indexed_constant(a65b125ca0efb1,x_arity).
xc_indexed_constant(a65b125ca0efb1,x_nuSketchTutorialStepConditions).
xc_indexed_constant(a65b125ca0efb2,x_Integer).
xc_indexed_constant(a65b125ca0efb2,x_arg1Isa).
xc_indexed_constant(a65b125ca0efb2,x_nuSketchTutorialStepConditions).
xc_indexed_constant(a65b125ca0efb3,x_List).
xc_indexed_constant(a65b125ca0efb3,x_arg2Isa).
xc_indexed_constant(a65b125ca0efb3,x_nuSketchTutorialStepConditions).
xc_indexed_constant(a65b125ca0efb4,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efb4,x_nuSketchTutorialStepConditions).
xc_indexed_constant(a65b125ca0efb5,x_UnaryPredicate).
xc_indexed_constant(a65b125ca0efb5,x_glyphCreatedOnTutorialStep).
xc_indexed_constant(a65b125ca0efb5,x_isa).
xc_indexed_constant(a65b125ca0efb6,x_arity).
xc_indexed_constant(a65b125ca0efb6,x_glyphCreatedOnTutorialStep).
xc_indexed_constant(a65b125ca0efb7,x_Entity).
xc_indexed_constant(a65b125ca0efb7,x_arg1Isa).
xc_indexed_constant(a65b125ca0efb7,x_glyphCreatedOnTutorialStep).
xc_indexed_constant(a65b125ca0efb8,x_glyphCreatedOnTutorialStep).
xc_indexed_constant(a65b125ca0efb8,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efb9,x_UnaryPredicate).
xc_indexed_constant(a65b125ca0efb9,x_isa).
xc_indexed_constant(a65b125ca0efb9,x_subsketchCreatedOnTutorialStep).
xc_indexed_constant(a65b125ca0efba,x_arity).
xc_indexed_constant(a65b125ca0efba,x_subsketchCreatedOnTutorialStep).
xc_indexed_constant(a65b125ca0efbb,x_Entity).
xc_indexed_constant(a65b125ca0efbb,x_arg1Isa).
xc_indexed_constant(a65b125ca0efbb,x_subsketchCreatedOnTutorialStep).
xc_indexed_constant(a65b125ca0efbc,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efbc,x_subsketchCreatedOnTutorialStep).
xc_indexed_constant(a65b125ca0efbd,x_UnaryPredicate).
xc_indexed_constant(a65b125ca0efbd,x_isa).
xc_indexed_constant(a65b125ca0efbd,x_sentenceAddedOnTutorialStep).
xc_indexed_constant(a65b125ca0efbe,x_arity).
xc_indexed_constant(a65b125ca0efbe,x_sentenceAddedOnTutorialStep).
xc_indexed_constant(a65b125ca0efbf,x_Entity).
xc_indexed_constant(a65b125ca0efbf,x_arg1Isa).
xc_indexed_constant(a65b125ca0efbf,x_sentenceAddedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc0,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efc0,x_sentenceAddedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc1,x_UnaryPredicate).
xc_indexed_constant(a65b125ca0efc1,x_feedbackRequestedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc1,x_isa).
xc_indexed_constant(a65b125ca0efc2,x_arity).
xc_indexed_constant(a65b125ca0efc2,x_feedbackRequestedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc3,x_Entity).
xc_indexed_constant(a65b125ca0efc3,x_arg1Isa).
xc_indexed_constant(a65b125ca0efc3,x_feedbackRequestedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc4,x_feedbackRequestedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc4,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efc5,x_BinaryPredicate).
xc_indexed_constant(a65b125ca0efc5,x_glyphEditedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc5,x_isa).
xc_indexed_constant(a65b125ca0efc6,x_arity).
xc_indexed_constant(a65b125ca0efc6,x_glyphEditedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc7,x_Thing).
xc_indexed_constant(a65b125ca0efc7,x_arg1Isa).
xc_indexed_constant(a65b125ca0efc7,x_glyphEditedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc8,x_Integer).
xc_indexed_constant(a65b125ca0efc8,x_arg2Isa).
xc_indexed_constant(a65b125ca0efc8,x_glyphEditedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc9,x_glyphEditedOnTutorialStep).
xc_indexed_constant(a65b125ca0efc9,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efca,x_BinaryPredicate).
xc_indexed_constant(a65b125ca0efca,x_glyphSegmentedOnTutorialStep).
xc_indexed_constant(a65b125ca0efca,x_isa).
xc_indexed_constant(a65b125ca0efcb,x_arity).
xc_indexed_constant(a65b125ca0efcb,x_glyphSegmentedOnTutorialStep).
xc_indexed_constant(a65b125ca0efcc,x_Thing).
xc_indexed_constant(a65b125ca0efcc,x_arg1Isa).
xc_indexed_constant(a65b125ca0efcc,x_glyphSegmentedOnTutorialStep).
xc_indexed_constant(a65b125ca0efcd,x_Integer).
xc_indexed_constant(a65b125ca0efcd,x_arg2Isa).
xc_indexed_constant(a65b125ca0efcd,x_glyphSegmentedOnTutorialStep).
xc_indexed_constant(a65b125ca0efce,x_glyphSegmentedOnTutorialStep).
xc_indexed_constant(a65b125ca0efce,x_notForAnalogy).
xc_indexed_constant(a65b125ca0efcf,x_BinaryPredicate).
xc_indexed_constant(a65b125ca0efcf,x_holdsOnTutorialStep).
xc_indexed_constant(a65b125ca0efcf,x_isa).
xc_indexed_constant(a65b125ca0efd0,x_arity).
xc_indexed_constant(a65b125ca0efd0,x_holdsOnTutorialStep).
xc_indexed_constant(a65b125ca0efd1,x_Integer).
xc_indexed_constant(a65b125ca0efd1,x_arg1Isa).
xc_indexed_constant(a65b125ca0efd1,x_holdsOnTutorialStep).
xc_indexed_constant(a65b125ca0efd2,x_CycLSentence).
xc_indexed_constant(a65b125ca0efd2,x_arg2Isa).
xc_indexed_constant(a65b125ca0efd2,x_holdsOnTutorialStep).
xc_indexed_constant(a65b125ca0efd3,x_holdsOnTutorialStep).
xc_indexed_constant(a65b125ca0efd3,x_notForAnalogy).
kb_index_footer(66,'1484e7aa5e8d29a5b0e2dd7936be8c717bd879cf98bf8e6713a7076929eaab3b','39bd5d3c8b25310fdce478685274c4ad00e8b671383310ddadc4d1d3a1f11c34').
