kb_index_header(index_header{count:17,digest:'50d9f9da891ac7d316182bbd4aed1852407560f8603696e56d6cbfa96043c958',normalizedDigest:cfbbd0a5b9ec11698e8dad8833cac03bbc99fce9faf201bf2e283fea91f4dab9,normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',sourceHash:'77552ffa363cb9285f8ae7fec998ae1b28b052e29bc06534fb7815b8c8ec33ca'}).
kb_index_data(index{constants:[-('x_<==',15),-(x_Acceleration,1),-(x_ConsFn,1),-(x_Constant,2),-(x_Decreasing,1),-('x_GreaterThan-UnitValuesFn',1),-(x_Increasing,2),-('x_LessThan-UnitValuesFn',1),-(x_MeasurementAtFn,7),-(x_MetersPerSecondPerSecond,1),-(x_Negative,1),-(x_Positive,1),-(x_Predicate,1),-(x_QPQuantityFn,1),-(x_RestOfListFn,1),-(x_Speed,1),-(x_TestQueryFn,1),-(x_TheClosedRetrievalSetOf,2),-(x_TheList,3),-(x_True,2),-(x_Zero,1),-(x_and,2),-(x_arity,1),-(x_believeInCurrentMt,3),-('x_causes-SitProp',1),-(x_consistent,1),-('x_constantThroughoutEvent-Fluent',1),-('x_decreasesThroughoutEvent-Fluent',1),-(x_elaborateBasicProblemInformation,2),-(x_evaluate,5),-(x_everySatisfies,1),-(x_forEffectOnly,1),-('x_increasesThroughoutEvent-Fluent',1),-(x_isa,1),-(x_lookupOnly,6),-(x_multipleChoiceSingleOptionList,2),-('x_negativeThroughoutEvent-Fluent',1),-(x_numericalAssumptionConsistencyProblem,3),-(x_operatorFormulas,2),-('x_positiveThroughoutEvent-Fluent',1),-(x_qprop,2),-('x_qprop-',2),-('x_qprop-InEquations',1),-(x_qpropInEquations,1),-(x_qualitativeProblem,1),-(x_quantityMentionedInProblem,7),-(x_quantityRelevantForNumericalConsistency,1),-('x_selectMultipleChoiceAnswer-NumericConsistency',2),-(x_solveEquationForNumericalValue,2),-(x_tell,3),-(x_termToSolveFor,1),-(x_uninferredSentence,1),-(x_valueOf,1),-(x_wmOnly,7),-('x_zeroThroughoutEvent-Fluent',1)],entries:[entry(a65b125d9ac6da,signature(x_isa,2),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',17,[x_Predicate,x_isa,x_numericalAssumptionConsistencyProblem]),entry(a65b125d9ac6db,signature(x_arity,2),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',18,[x_arity,x_numericalAssumptionConsistencyProblem]),entry(a65b125d9ac6dc,signature('x_<==',4),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',20,['x_<==',x_TestQueryFn,x_consistent,x_elaborateBasicProblemInformation,x_forEffectOnly,x_numericalAssumptionConsistencyProblem,x_qualitativeProblem,x_tell,x_termToSolveFor,x_valueOf,x_wmOnly]),entry(a65b125d9ac6dd,signature('x_<==',3),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',34,['x_<==',x_believeInCurrentMt,'x_causes-SitProp',x_elaborateBasicProblemInformation]),entry(a65b125d9ac6de,signature('x_<==',4),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',45,['x_<==',x_ConsFn,x_RestOfListFn,x_TheList,x_and,x_believeInCurrentMt,x_evaluate,x_everySatisfies,x_operatorFormulas,x_tell]),entry(a65b125d9ac6df,signature('x_<==',3),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',52,['x_<==',x_and,x_believeInCurrentMt,x_operatorFormulas,x_tell,x_uninferredSentence]),entry(a65b125d9ac6e0,signature('x_<==',3),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',56,['x_<==',x_Acceleration,x_Constant,x_Increasing,x_MeasurementAtFn,x_MetersPerSecondPerSecond,x_QPQuantityFn,x_Speed,x_quantityMentionedInProblem,x_quantityRelevantForNumericalConsistency]),entry(a65b125d9ac6e1,signature('x_<==',2),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',70,['x_<==',x_Increasing,x_MeasurementAtFn,'x_increasesThroughoutEvent-Fluent',x_lookupOnly,x_quantityMentionedInProblem,x_wmOnly]),entry(a65b125d9ac6e2,signature('x_<==',2),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',73,['x_<==',x_Decreasing,x_MeasurementAtFn,'x_decreasesThroughoutEvent-Fluent',x_lookupOnly,x_quantityMentionedInProblem,x_wmOnly]),entry(a65b125d9ac6e3,signature('x_<==',2),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',76,['x_<==',x_Constant,x_MeasurementAtFn,'x_constantThroughoutEvent-Fluent',x_lookupOnly,x_quantityMentionedInProblem,x_wmOnly]),entry(a65b125d9ac6e4,signature('x_<==',2),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',79,['x_<==',x_MeasurementAtFn,x_Zero,x_lookupOnly,x_quantityMentionedInProblem,x_wmOnly,'x_zeroThroughoutEvent-Fluent']),entry(a65b125d9ac6e5,signature('x_<==',2),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',82,['x_<==',x_MeasurementAtFn,x_Positive,x_lookupOnly,'x_positiveThroughoutEvent-Fluent',x_quantityMentionedInProblem,x_wmOnly]),entry(a65b125d9ac6e6,signature('x_<==',2),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',85,['x_<==',x_MeasurementAtFn,x_Negative,x_lookupOnly,'x_negativeThroughoutEvent-Fluent',x_quantityMentionedInProblem,x_wmOnly]),entry(a65b125d9ac6e7,signature('x_<==',4),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',91,['x_<==','x_GreaterThan-UnitValuesFn',x_TheList,x_True,x_evaluate,x_multipleChoiceSingleOptionList,x_qprop,'x_selectMultipleChoiceAnswer-NumericConsistency']),entry(a65b125d9ac6e8,signature('x_<==',4),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',97,['x_<==','x_LessThan-UnitValuesFn',x_TheList,x_True,x_evaluate,x_multipleChoiceSingleOptionList,'x_qprop-','x_selectMultipleChoiceAnswer-NumericConsistency']),entry(a65b125d9ac6e9,signature('x_<==',3),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',104,['x_<==',x_TheClosedRetrievalSetOf,x_evaluate,'x_qprop-','x_qprop-InEquations',x_solveEquationForNumericalValue]),entry(a65b125d9ac6ea,signature('x_<==',3),x_EquationSolvingRulesMt,'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf',110,['x_<==',x_TheClosedRetrievalSetOf,x_evaluate,x_qprop,x_qpropInEquations,x_solveEquationForNumericalValue])],predicates:[-(signature('x_<==',2),6),-(signature('x_<==',3),5),-(signature('x_<==',4),4),-(signature(x_arity,2),1),-(signature(x_isa,2),1)],rankedConstants:[-(15,'x_<=='),-(7,x_wmOnly),-(7,x_quantityMentionedInProblem),-(7,x_MeasurementAtFn),-(6,x_lookupOnly),-(5,x_evaluate),-(3,x_tell),-(3,x_numericalAssumptionConsistencyProblem),-(3,x_believeInCurrentMt),-(3,x_TheList),-(2,x_solveEquationForNumericalValue),-(2,'x_selectMultipleChoiceAnswer-NumericConsistency'),-(2,'x_qprop-'),-(2,x_qprop),-(2,x_operatorFormulas),-(2,x_multipleChoiceSingleOptionList),-(2,x_elaborateBasicProblemInformation),-(2,x_and),-(2,x_True),-(2,x_TheClosedRetrievalSetOf),-(2,x_Increasing),-(2,x_Constant),-(1,'x_zeroThroughoutEvent-Fluent'),-(1,x_valueOf),-(1,x_uninferredSentence),-(1,x_termToSolveFor),-(1,x_quantityRelevantForNumericalConsistency),-(1,x_qualitativeProblem),-(1,x_qpropInEquations),-(1,'x_qprop-InEquations'),-(1,'x_positiveThroughoutEvent-Fluent'),-(1,'x_negativeThroughoutEvent-Fluent'),-(1,x_isa),-(1,'x_increasesThroughoutEvent-Fluent'),-(1,x_forEffectOnly),-(1,x_everySatisfies),-(1,'x_decreasesThroughoutEvent-Fluent'),-(1,'x_constantThroughoutEvent-Fluent'),-(1,x_consistent),-(1,'x_causes-SitProp'),-(1,x_arity),-(1,x_Zero),-(1,x_TestQueryFn),-(1,x_Speed),-(1,x_RestOfListFn),-(1,x_QPQuantityFn),-(1,x_Predicate),-(1,x_Positive),-(1,x_Negative),-(1,x_MetersPerSecondPerSecond),-(1,'x_LessThan-UnitValuesFn'),-(1,'x_GreaterThan-UnitValuesFn'),-(1,x_Decreasing),-(1,x_ConsFn),-(1,x_Acceleration)],rankedPredicates:[-(6,signature('x_<==',2)),-(5,signature('x_<==',3)),-(4,signature('x_<==',4)),-(1,signature(x_isa,2)),-(1,signature(x_arity,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/mechanics/v4/numeric-consistency.krf'}).
xc_indexed_constant(a65b125d9ac6da,x_Predicate).
xc_indexed_constant(a65b125d9ac6da,x_isa).
xc_indexed_constant(a65b125d9ac6da,x_numericalAssumptionConsistencyProblem).
xc_indexed_constant(a65b125d9ac6db,x_arity).
xc_indexed_constant(a65b125d9ac6db,x_numericalAssumptionConsistencyProblem).
xc_indexed_constant(a65b125d9ac6dc,'x_<==').
xc_indexed_constant(a65b125d9ac6dc,x_TestQueryFn).
xc_indexed_constant(a65b125d9ac6dc,x_consistent).
xc_indexed_constant(a65b125d9ac6dc,x_elaborateBasicProblemInformation).
xc_indexed_constant(a65b125d9ac6dc,x_forEffectOnly).
xc_indexed_constant(a65b125d9ac6dc,x_numericalAssumptionConsistencyProblem).
xc_indexed_constant(a65b125d9ac6dc,x_qualitativeProblem).
xc_indexed_constant(a65b125d9ac6dc,x_tell).
xc_indexed_constant(a65b125d9ac6dc,x_termToSolveFor).
xc_indexed_constant(a65b125d9ac6dc,x_valueOf).
xc_indexed_constant(a65b125d9ac6dc,x_wmOnly).
xc_indexed_constant(a65b125d9ac6dd,'x_<==').
xc_indexed_constant(a65b125d9ac6dd,x_believeInCurrentMt).
xc_indexed_constant(a65b125d9ac6dd,'x_causes-SitProp').
xc_indexed_constant(a65b125d9ac6dd,x_elaborateBasicProblemInformation).
xc_indexed_constant(a65b125d9ac6de,'x_<==').
xc_indexed_constant(a65b125d9ac6de,x_ConsFn).
xc_indexed_constant(a65b125d9ac6de,x_RestOfListFn).
xc_indexed_constant(a65b125d9ac6de,x_TheList).
xc_indexed_constant(a65b125d9ac6de,x_and).
xc_indexed_constant(a65b125d9ac6de,x_believeInCurrentMt).
xc_indexed_constant(a65b125d9ac6de,x_evaluate).
xc_indexed_constant(a65b125d9ac6de,x_everySatisfies).
xc_indexed_constant(a65b125d9ac6de,x_operatorFormulas).
xc_indexed_constant(a65b125d9ac6de,x_tell).
xc_indexed_constant(a65b125d9ac6df,'x_<==').
xc_indexed_constant(a65b125d9ac6df,x_and).
xc_indexed_constant(a65b125d9ac6df,x_believeInCurrentMt).
xc_indexed_constant(a65b125d9ac6df,x_operatorFormulas).
xc_indexed_constant(a65b125d9ac6df,x_tell).
xc_indexed_constant(a65b125d9ac6df,x_uninferredSentence).
xc_indexed_constant(a65b125d9ac6e0,'x_<==').
xc_indexed_constant(a65b125d9ac6e0,x_Acceleration).
xc_indexed_constant(a65b125d9ac6e0,x_Constant).
xc_indexed_constant(a65b125d9ac6e0,x_Increasing).
xc_indexed_constant(a65b125d9ac6e0,x_MeasurementAtFn).
xc_indexed_constant(a65b125d9ac6e0,x_MetersPerSecondPerSecond).
xc_indexed_constant(a65b125d9ac6e0,x_QPQuantityFn).
xc_indexed_constant(a65b125d9ac6e0,x_Speed).
xc_indexed_constant(a65b125d9ac6e0,x_quantityMentionedInProblem).
xc_indexed_constant(a65b125d9ac6e0,x_quantityRelevantForNumericalConsistency).
xc_indexed_constant(a65b125d9ac6e1,'x_<==').
xc_indexed_constant(a65b125d9ac6e1,x_Increasing).
xc_indexed_constant(a65b125d9ac6e1,x_MeasurementAtFn).
xc_indexed_constant(a65b125d9ac6e1,'x_increasesThroughoutEvent-Fluent').
xc_indexed_constant(a65b125d9ac6e1,x_lookupOnly).
xc_indexed_constant(a65b125d9ac6e1,x_quantityMentionedInProblem).
xc_indexed_constant(a65b125d9ac6e1,x_wmOnly).
xc_indexed_constant(a65b125d9ac6e2,'x_<==').
xc_indexed_constant(a65b125d9ac6e2,x_Decreasing).
xc_indexed_constant(a65b125d9ac6e2,x_MeasurementAtFn).
xc_indexed_constant(a65b125d9ac6e2,'x_decreasesThroughoutEvent-Fluent').
xc_indexed_constant(a65b125d9ac6e2,x_lookupOnly).
xc_indexed_constant(a65b125d9ac6e2,x_quantityMentionedInProblem).
xc_indexed_constant(a65b125d9ac6e2,x_wmOnly).
xc_indexed_constant(a65b125d9ac6e3,'x_<==').
xc_indexed_constant(a65b125d9ac6e3,x_Constant).
xc_indexed_constant(a65b125d9ac6e3,x_MeasurementAtFn).
xc_indexed_constant(a65b125d9ac6e3,'x_constantThroughoutEvent-Fluent').
xc_indexed_constant(a65b125d9ac6e3,x_lookupOnly).
xc_indexed_constant(a65b125d9ac6e3,x_quantityMentionedInProblem).
xc_indexed_constant(a65b125d9ac6e3,x_wmOnly).
xc_indexed_constant(a65b125d9ac6e4,'x_<==').
xc_indexed_constant(a65b125d9ac6e4,x_MeasurementAtFn).
xc_indexed_constant(a65b125d9ac6e4,x_Zero).
xc_indexed_constant(a65b125d9ac6e4,x_lookupOnly).
xc_indexed_constant(a65b125d9ac6e4,x_quantityMentionedInProblem).
xc_indexed_constant(a65b125d9ac6e4,x_wmOnly).
xc_indexed_constant(a65b125d9ac6e4,'x_zeroThroughoutEvent-Fluent').
xc_indexed_constant(a65b125d9ac6e5,'x_<==').
xc_indexed_constant(a65b125d9ac6e5,x_MeasurementAtFn).
xc_indexed_constant(a65b125d9ac6e5,x_Positive).
xc_indexed_constant(a65b125d9ac6e5,x_lookupOnly).
xc_indexed_constant(a65b125d9ac6e5,'x_positiveThroughoutEvent-Fluent').
xc_indexed_constant(a65b125d9ac6e5,x_quantityMentionedInProblem).
xc_indexed_constant(a65b125d9ac6e5,x_wmOnly).
xc_indexed_constant(a65b125d9ac6e6,'x_<==').
xc_indexed_constant(a65b125d9ac6e6,x_MeasurementAtFn).
xc_indexed_constant(a65b125d9ac6e6,x_Negative).
xc_indexed_constant(a65b125d9ac6e6,x_lookupOnly).
xc_indexed_constant(a65b125d9ac6e6,'x_negativeThroughoutEvent-Fluent').
xc_indexed_constant(a65b125d9ac6e6,x_quantityMentionedInProblem).
xc_indexed_constant(a65b125d9ac6e6,x_wmOnly).
xc_indexed_constant(a65b125d9ac6e7,'x_<==').
xc_indexed_constant(a65b125d9ac6e7,'x_GreaterThan-UnitValuesFn').
xc_indexed_constant(a65b125d9ac6e7,x_TheList).
xc_indexed_constant(a65b125d9ac6e7,x_True).
xc_indexed_constant(a65b125d9ac6e7,x_evaluate).
xc_indexed_constant(a65b125d9ac6e7,x_multipleChoiceSingleOptionList).
xc_indexed_constant(a65b125d9ac6e7,x_qprop).
xc_indexed_constant(a65b125d9ac6e7,'x_selectMultipleChoiceAnswer-NumericConsistency').
xc_indexed_constant(a65b125d9ac6e8,'x_<==').
xc_indexed_constant(a65b125d9ac6e8,'x_LessThan-UnitValuesFn').
xc_indexed_constant(a65b125d9ac6e8,x_TheList).
xc_indexed_constant(a65b125d9ac6e8,x_True).
xc_indexed_constant(a65b125d9ac6e8,x_evaluate).
xc_indexed_constant(a65b125d9ac6e8,x_multipleChoiceSingleOptionList).
xc_indexed_constant(a65b125d9ac6e8,'x_qprop-').
xc_indexed_constant(a65b125d9ac6e8,'x_selectMultipleChoiceAnswer-NumericConsistency').
xc_indexed_constant(a65b125d9ac6e9,'x_<==').
xc_indexed_constant(a65b125d9ac6e9,x_TheClosedRetrievalSetOf).
xc_indexed_constant(a65b125d9ac6e9,x_evaluate).
xc_indexed_constant(a65b125d9ac6e9,'x_qprop-').
xc_indexed_constant(a65b125d9ac6e9,'x_qprop-InEquations').
xc_indexed_constant(a65b125d9ac6e9,x_solveEquationForNumericalValue).
xc_indexed_constant(a65b125d9ac6ea,'x_<==').
xc_indexed_constant(a65b125d9ac6ea,x_TheClosedRetrievalSetOf).
xc_indexed_constant(a65b125d9ac6ea,x_evaluate).
xc_indexed_constant(a65b125d9ac6ea,x_qprop).
xc_indexed_constant(a65b125d9ac6ea,x_qpropInEquations).
xc_indexed_constant(a65b125d9ac6ea,x_solveEquationForNumericalValue).
kb_index_footer(17,'50d9f9da891ac7d316182bbd4aed1852407560f8603696e56d6cbfa96043c958','7bd5495e449301b0af8545ed310b13971bad365bbd5935a8a602b1495f24d0cc').
