kb_index_header(index_header{count:15,digest:f9c63b90b5037baa3af28a459105dace861b756a0b1327cf2ffe389c4e055a40,normalizedDigest:'3c60796784e6d78a719c087f04afc6060e648396dd2aa5556d871b2c9fde1a6b',normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',sourceHash:'406a68124136d9edf787ac5d2efd1e6efb228d036d8554e823801fd031c6dce2'}).
kb_index_data(index{constants:[-('x_Cogsketch-AgentMt',1),-(x_CompanionsMt,1),-(x_CompanionsSketchRolodexMt,2),-(x_ComplexActionPredicate,2),-(x_EverythingPSC,3),-(x_LengthOfListFn,1),-(x_MappingDisplayColor,1),-(x_ModuloFn,1),-(x_NthInListFn,1),-(x_NuSketchMt,1),-(x_NuSketchSketch,3),-(x_PerceptualElement,1),-(x_PlusFn,1),-(x_PositionInListFn,1),-('x_Set-Extensional',1),-(x_SetToListFn,1),-(x_TheClosedRetrievalSetOf,1),-(x_TheList,4),-(x_actionSequence,4),-(x_agentForOpenSketch,3),-(x_and,2),-(x_arg1Isa,2),-(x_arg2Isa,1),-(x_arg3Isa,1),-(x_arity,2),-(x_colorizePerceptualElementsFromCorrespondences,7),-(x_comment,2),-(x_doAnnounce,4),-(x_doForEach,1),-(x_doOpenSketchFile,1),-(x_doSetInkColor,1),-(x_doSynchronousRemotePlan,1),-(x_elementOf,1),-(x_evaluate,1),-(x_genlMt,1),-(x_holdsOnRemoteAgent,1),-(x_isa,3),-('x_ist-Information',4),-(x_methodForAction,4),-(x_nuSketchFileURL,2),-(x_openSketch,7),-(x_preconditionForMethod,4),-(x_unifies,1),-(x_uninferredSentence,2),-(x_wmOnly,2)],entries:[entry(a65b125dc0a8b6,signature(x_genlMt,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',15,['x_Cogsketch-AgentMt',x_CompanionsMt,x_genlMt]),entry(a65b125dc0a8b7,signature(x_isa,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',19,[x_ComplexActionPredicate,x_colorizePerceptualElementsFromCorrespondences,x_isa]),entry(a65b125dc0a8b8,signature(x_arity,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',20,[x_arity,x_colorizePerceptualElementsFromCorrespondences]),entry(a65b125dc0a8b9,signature(x_arg1Isa,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',21,[x_NuSketchSketch,x_arg1Isa,x_colorizePerceptualElementsFromCorrespondences]),entry(a65b125dc0a8ba,signature(x_arg2Isa,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',22,[x_NuSketchSketch,x_arg2Isa,x_colorizePerceptualElementsFromCorrespondences]),entry(a65b125dc0a8bb,signature(x_arg3Isa,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',23,['x_Set-Extensional',x_arg3Isa,x_colorizePerceptualElementsFromCorrespondences]),entry(a65b125dc0a8bc,signature(x_comment,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',24,[x_colorizePerceptualElementsFromCorrespondences,x_comment]),entry(a65b125dc0a8bd,signature(x_isa,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',32,[x_ComplexActionPredicate,x_isa,x_openSketch]),entry(a65b125dc0a8be,signature(x_arity,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',33,[x_arity,x_openSketch]),entry(a65b125dc0a8bf,signature(x_arg1Isa,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',34,[x_NuSketchSketch,x_arg1Isa,x_openSketch]),entry(a65b125dc0a8c0,signature(x_comment,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',35,[x_comment,x_openSketch]),entry(a65b125dc0a8c1,signature(x_preconditionForMethod,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',40,[x_CompanionsSketchRolodexMt,x_EverythingPSC,x_TheList,x_actionSequence,x_agentForOpenSketch,x_and,x_doAnnounce,x_doOpenSketchFile,'x_ist-Information',x_methodForAction,x_nuSketchFileURL,x_openSketch,x_preconditionForMethod,x_uninferredSentence,x_wmOnly]),entry(a65b125dc0a8c2,signature(x_preconditionForMethod,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',54,[x_EverythingPSC,x_TheList,x_actionSequence,x_agentForOpenSketch,x_doAnnounce,'x_ist-Information',x_methodForAction,x_openSketch,x_preconditionForMethod,x_wmOnly]),entry(a65b125dc0a8c3,signature(x_preconditionForMethod,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',64,[x_CompanionsSketchRolodexMt,x_TheList,x_actionSequence,x_doAnnounce,'x_ist-Information',x_methodForAction,x_nuSketchFileURL,x_openSketch,x_preconditionForMethod,x_uninferredSentence]),entry(a65b125dc0a8c4,signature(x_preconditionForMethod,2),'x_Cogsketch-AgentMt','c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf',74,[x_EverythingPSC,x_LengthOfListFn,x_MappingDisplayColor,x_ModuloFn,x_NthInListFn,x_NuSketchMt,x_PerceptualElement,x_PlusFn,x_PositionInListFn,x_SetToListFn,x_TheClosedRetrievalSetOf,x_TheList,x_actionSequence,x_agentForOpenSketch,x_and,x_colorizePerceptualElementsFromCorrespondences,x_doAnnounce,x_doForEach,x_doSetInkColor,x_doSynchronousRemotePlan,x_elementOf,x_evaluate,x_holdsOnRemoteAgent,x_isa,'x_ist-Information',x_methodForAction,x_preconditionForMethod,x_unifies])],predicates:[-(signature(x_arg1Isa,2),2),-(signature(x_arg2Isa,2),1),-(signature(x_arg3Isa,2),1),-(signature(x_arity,2),2),-(signature(x_comment,2),2),-(signature(x_genlMt,2),1),-(signature(x_isa,2),2),-(signature(x_preconditionForMethod,2),4)],rankedConstants:[-(7,x_openSketch),-(7,x_colorizePerceptualElementsFromCorrespondences),-(4,x_preconditionForMethod),-(4,x_methodForAction),-(4,'x_ist-Information'),-(4,x_doAnnounce),-(4,x_actionSequence),-(4,x_TheList),-(3,x_isa),-(3,x_agentForOpenSketch),-(3,x_NuSketchSketch),-(3,x_EverythingPSC),-(2,x_wmOnly),-(2,x_uninferredSentence),-(2,x_nuSketchFileURL),-(2,x_comment),-(2,x_arity),-(2,x_arg1Isa),-(2,x_and),-(2,x_ComplexActionPredicate),-(2,x_CompanionsSketchRolodexMt),-(1,x_unifies),-(1,x_holdsOnRemoteAgent),-(1,x_genlMt),-(1,x_evaluate),-(1,x_elementOf),-(1,x_doSynchronousRemotePlan),-(1,x_doSetInkColor),-(1,x_doOpenSketchFile),-(1,x_doForEach),-(1,x_arg3Isa),-(1,x_arg2Isa),-(1,x_TheClosedRetrievalSetOf),-(1,x_SetToListFn),-(1,'x_Set-Extensional'),-(1,x_PositionInListFn),-(1,x_PlusFn),-(1,x_PerceptualElement),-(1,x_NuSketchMt),-(1,x_NthInListFn),-(1,x_ModuloFn),-(1,x_MappingDisplayColor),-(1,x_LengthOfListFn),-(1,x_CompanionsMt),-(1,'x_Cogsketch-AgentMt')],rankedPredicates:[-(4,signature(x_preconditionForMethod,2)),-(2,signature(x_isa,2)),-(2,signature(x_comment,2)),-(2,signature(x_arity,2)),-(2,signature(x_arg1Isa,2)),-(1,signature(x_genlMt,2)),-(1,signature(x_arg3Isa,2)),-(1,signature(x_arg2Isa,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/companions/v1/flat-files/nusketch-hookup/common-nusketch-hookup-plans.krf'}).
xc_indexed_constant(a65b125dc0a8b6,'x_Cogsketch-AgentMt').
xc_indexed_constant(a65b125dc0a8b6,x_CompanionsMt).
xc_indexed_constant(a65b125dc0a8b6,x_genlMt).
xc_indexed_constant(a65b125dc0a8b7,x_ComplexActionPredicate).
xc_indexed_constant(a65b125dc0a8b7,x_colorizePerceptualElementsFromCorrespondences).
xc_indexed_constant(a65b125dc0a8b7,x_isa).
xc_indexed_constant(a65b125dc0a8b8,x_arity).
xc_indexed_constant(a65b125dc0a8b8,x_colorizePerceptualElementsFromCorrespondences).
xc_indexed_constant(a65b125dc0a8b9,x_NuSketchSketch).
xc_indexed_constant(a65b125dc0a8b9,x_arg1Isa).
xc_indexed_constant(a65b125dc0a8b9,x_colorizePerceptualElementsFromCorrespondences).
xc_indexed_constant(a65b125dc0a8ba,x_NuSketchSketch).
xc_indexed_constant(a65b125dc0a8ba,x_arg2Isa).
xc_indexed_constant(a65b125dc0a8ba,x_colorizePerceptualElementsFromCorrespondences).
xc_indexed_constant(a65b125dc0a8bb,'x_Set-Extensional').
xc_indexed_constant(a65b125dc0a8bb,x_arg3Isa).
xc_indexed_constant(a65b125dc0a8bb,x_colorizePerceptualElementsFromCorrespondences).
xc_indexed_constant(a65b125dc0a8bc,x_colorizePerceptualElementsFromCorrespondences).
xc_indexed_constant(a65b125dc0a8bc,x_comment).
xc_indexed_constant(a65b125dc0a8bd,x_ComplexActionPredicate).
xc_indexed_constant(a65b125dc0a8bd,x_isa).
xc_indexed_constant(a65b125dc0a8bd,x_openSketch).
xc_indexed_constant(a65b125dc0a8be,x_arity).
xc_indexed_constant(a65b125dc0a8be,x_openSketch).
xc_indexed_constant(a65b125dc0a8bf,x_NuSketchSketch).
xc_indexed_constant(a65b125dc0a8bf,x_arg1Isa).
xc_indexed_constant(a65b125dc0a8bf,x_openSketch).
xc_indexed_constant(a65b125dc0a8c0,x_comment).
xc_indexed_constant(a65b125dc0a8c0,x_openSketch).
xc_indexed_constant(a65b125dc0a8c1,x_CompanionsSketchRolodexMt).
xc_indexed_constant(a65b125dc0a8c1,x_EverythingPSC).
xc_indexed_constant(a65b125dc0a8c1,x_TheList).
xc_indexed_constant(a65b125dc0a8c1,x_actionSequence).
xc_indexed_constant(a65b125dc0a8c1,x_agentForOpenSketch).
xc_indexed_constant(a65b125dc0a8c1,x_and).
xc_indexed_constant(a65b125dc0a8c1,x_doAnnounce).
xc_indexed_constant(a65b125dc0a8c1,x_doOpenSketchFile).
xc_indexed_constant(a65b125dc0a8c1,'x_ist-Information').
xc_indexed_constant(a65b125dc0a8c1,x_methodForAction).
xc_indexed_constant(a65b125dc0a8c1,x_nuSketchFileURL).
xc_indexed_constant(a65b125dc0a8c1,x_openSketch).
xc_indexed_constant(a65b125dc0a8c1,x_preconditionForMethod).
xc_indexed_constant(a65b125dc0a8c1,x_uninferredSentence).
xc_indexed_constant(a65b125dc0a8c1,x_wmOnly).
xc_indexed_constant(a65b125dc0a8c2,x_EverythingPSC).
xc_indexed_constant(a65b125dc0a8c2,x_TheList).
xc_indexed_constant(a65b125dc0a8c2,x_actionSequence).
xc_indexed_constant(a65b125dc0a8c2,x_agentForOpenSketch).
xc_indexed_constant(a65b125dc0a8c2,x_doAnnounce).
xc_indexed_constant(a65b125dc0a8c2,'x_ist-Information').
xc_indexed_constant(a65b125dc0a8c2,x_methodForAction).
xc_indexed_constant(a65b125dc0a8c2,x_openSketch).
xc_indexed_constant(a65b125dc0a8c2,x_preconditionForMethod).
xc_indexed_constant(a65b125dc0a8c2,x_wmOnly).
xc_indexed_constant(a65b125dc0a8c3,x_CompanionsSketchRolodexMt).
xc_indexed_constant(a65b125dc0a8c3,x_TheList).
xc_indexed_constant(a65b125dc0a8c3,x_actionSequence).
xc_indexed_constant(a65b125dc0a8c3,x_doAnnounce).
xc_indexed_constant(a65b125dc0a8c3,'x_ist-Information').
xc_indexed_constant(a65b125dc0a8c3,x_methodForAction).
xc_indexed_constant(a65b125dc0a8c3,x_nuSketchFileURL).
xc_indexed_constant(a65b125dc0a8c3,x_openSketch).
xc_indexed_constant(a65b125dc0a8c3,x_preconditionForMethod).
xc_indexed_constant(a65b125dc0a8c3,x_uninferredSentence).
xc_indexed_constant(a65b125dc0a8c4,x_EverythingPSC).
xc_indexed_constant(a65b125dc0a8c4,x_LengthOfListFn).
xc_indexed_constant(a65b125dc0a8c4,x_MappingDisplayColor).
xc_indexed_constant(a65b125dc0a8c4,x_ModuloFn).
xc_indexed_constant(a65b125dc0a8c4,x_NthInListFn).
xc_indexed_constant(a65b125dc0a8c4,x_NuSketchMt).
xc_indexed_constant(a65b125dc0a8c4,x_PerceptualElement).
xc_indexed_constant(a65b125dc0a8c4,x_PlusFn).
xc_indexed_constant(a65b125dc0a8c4,x_PositionInListFn).
xc_indexed_constant(a65b125dc0a8c4,x_SetToListFn).
xc_indexed_constant(a65b125dc0a8c4,x_TheClosedRetrievalSetOf).
xc_indexed_constant(a65b125dc0a8c4,x_TheList).
xc_indexed_constant(a65b125dc0a8c4,x_actionSequence).
xc_indexed_constant(a65b125dc0a8c4,x_agentForOpenSketch).
xc_indexed_constant(a65b125dc0a8c4,x_and).
xc_indexed_constant(a65b125dc0a8c4,x_colorizePerceptualElementsFromCorrespondences).
xc_indexed_constant(a65b125dc0a8c4,x_doAnnounce).
xc_indexed_constant(a65b125dc0a8c4,x_doForEach).
xc_indexed_constant(a65b125dc0a8c4,x_doSetInkColor).
xc_indexed_constant(a65b125dc0a8c4,x_doSynchronousRemotePlan).
xc_indexed_constant(a65b125dc0a8c4,x_elementOf).
xc_indexed_constant(a65b125dc0a8c4,x_evaluate).
xc_indexed_constant(a65b125dc0a8c4,x_holdsOnRemoteAgent).
xc_indexed_constant(a65b125dc0a8c4,x_isa).
xc_indexed_constant(a65b125dc0a8c4,'x_ist-Information').
xc_indexed_constant(a65b125dc0a8c4,x_methodForAction).
xc_indexed_constant(a65b125dc0a8c4,x_preconditionForMethod).
xc_indexed_constant(a65b125dc0a8c4,x_unifies).
kb_index_footer(15,f9c63b90b5037baa3af28a459105dace861b756a0b1327cf2ffe389c4e055a40,'463bede89d630589b1e3a5fa28adb7da9f601879a279ea60b233b07ca69c9523').
