kb_index_header(index_header{count:17,digest:'8f20c1a7060fd670dfa578f2c0a0acc54cd01476506f087679f5debad28aa057',normalizedDigest:'220bbf23d924777fc5160bf0e7eb2e79496a9815e16a692cba6df79ac479b73d',normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',sourceHash:'12d25d1a6bae2daf256acd0cd1c617600d3f4d165c5f0c0961ab52c9466adc7a'}).
kb_index_data(index{constants:[-(x_Case,2),-(x_CollectorMicrotheory,1),-('x_Function-Denotational',1),-(x_Microtheory,1),-(x_NuSketchApplication,1),-(x_NuSketchLayer,1),-(x_NuSketchMt,1),-(x_NuSketchReasoningCollectorMt,1),-(x_ReasonerControlState,1),-('x_SKEA-VisualConceptualMappingsMt',1),-(x_SKEAAnalogyMt,1),-(x_SKEAMt,2),-(x_SKEAReasoningCollectorMt,7),-(x_SkeaLayerCaseFn,6),-(x_arg1Isa,1),-(x_arg2Isa,1),-(x_arity,1),-(x_comment,2),-(x_genlMt,5),-(x_isa,5),-(x_nuSketchAppKBVersion,1),-(x_resultIsa,1),-(x_sKEA,3)],entries:[entry(a65b125cabfbfd,signature(x_genlMt,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',15,[x_NuSketchMt,x_SKEAMt,x_genlMt]),entry(a65b125cabfbfe,signature(x_isa,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',21,[x_NuSketchApplication,x_isa,x_sKEA]),entry(a65b125cabfbff,signature(x_isa,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',22,[x_ReasonerControlState,x_isa,x_sKEA]),entry(a65b125cabfc00,signature(x_nuSketchAppKBVersion,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',24,[x_nuSketchAppKBVersion,x_sKEA]),entry(a65b125cabfc01,signature(x_isa,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',30,['x_Function-Denotational',x_SkeaLayerCaseFn,x_isa]),entry(a65b125cabfc02,signature(x_arity,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',31,[x_SkeaLayerCaseFn,x_arity]),entry(a65b125cabfc03,signature(x_arg1Isa,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',32,[x_Case,x_SkeaLayerCaseFn,x_arg1Isa]),entry(a65b125cabfc04,signature(x_arg2Isa,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',33,[x_NuSketchLayer,x_SkeaLayerCaseFn,x_arg2Isa]),entry(a65b125cabfc05,signature(x_resultIsa,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',34,[x_Case,x_SkeaLayerCaseFn,x_resultIsa]),entry(a65b125cabfc06,signature(x_comment,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',35,[x_SkeaLayerCaseFn,x_comment]),entry(a65b125cabfc07,signature(x_isa,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',44,[x_Microtheory,x_SKEAReasoningCollectorMt,x_isa]),entry(a65b125cabfc08,signature(x_isa,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',45,[x_CollectorMicrotheory,x_SKEAReasoningCollectorMt,x_isa]),entry(a65b125cabfc09,signature(x_genlMt,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',47,[x_SKEAMt,x_SKEAReasoningCollectorMt,x_genlMt]),entry(a65b125cabfc0a,signature(x_genlMt,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',48,[x_NuSketchReasoningCollectorMt,x_SKEAReasoningCollectorMt,x_genlMt]),entry(a65b125cabfc0b,signature(x_genlMt,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',49,[x_SKEAAnalogyMt,x_SKEAReasoningCollectorMt,x_genlMt]),entry(a65b125cabfc0c,signature(x_genlMt,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',50,['x_SKEA-VisualConceptualMappingsMt',x_SKEAReasoningCollectorMt,x_genlMt]),entry(a65b125cabfc0d,signature(x_comment,2),x_SKEAMt,'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf',52,[x_SKEAReasoningCollectorMt,x_comment])],predicates:[-(signature(x_arg1Isa,2),1),-(signature(x_arg2Isa,2),1),-(signature(x_arity,2),1),-(signature(x_comment,2),2),-(signature(x_genlMt,2),5),-(signature(x_isa,2),5),-(signature(x_nuSketchAppKBVersion,2),1),-(signature(x_resultIsa,2),1)],rankedConstants:[-(7,x_SKEAReasoningCollectorMt),-(6,x_SkeaLayerCaseFn),-(5,x_isa),-(5,x_genlMt),-(3,x_sKEA),-(2,x_comment),-(2,x_SKEAMt),-(2,x_Case),-(1,x_resultIsa),-(1,x_nuSketchAppKBVersion),-(1,x_arity),-(1,x_arg2Isa),-(1,x_arg1Isa),-(1,x_SKEAAnalogyMt),-(1,'x_SKEA-VisualConceptualMappingsMt'),-(1,x_ReasonerControlState),-(1,x_NuSketchReasoningCollectorMt),-(1,x_NuSketchMt),-(1,x_NuSketchLayer),-(1,x_NuSketchApplication),-(1,x_Microtheory),-(1,'x_Function-Denotational'),-(1,x_CollectorMicrotheory)],rankedPredicates:[-(5,signature(x_isa,2)),-(5,signature(x_genlMt,2)),-(2,signature(x_comment,2)),-(1,signature(x_resultIsa,2)),-(1,signature(x_nuSketchAppKBVersion,2)),-(1,signature(x_arity,2)),-(1,signature(x_arg2Isa,2)),-(1,signature(x_arg1Isa,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/cogsketch/kb-flat-files/skea/skea.krf'}).
xc_indexed_constant(a65b125cabfbfd,x_NuSketchMt).
xc_indexed_constant(a65b125cabfbfd,x_SKEAMt).
xc_indexed_constant(a65b125cabfbfd,x_genlMt).
xc_indexed_constant(a65b125cabfbfe,x_NuSketchApplication).
xc_indexed_constant(a65b125cabfbfe,x_isa).
xc_indexed_constant(a65b125cabfbfe,x_sKEA).
xc_indexed_constant(a65b125cabfbff,x_ReasonerControlState).
xc_indexed_constant(a65b125cabfbff,x_isa).
xc_indexed_constant(a65b125cabfbff,x_sKEA).
xc_indexed_constant(a65b125cabfc00,x_nuSketchAppKBVersion).
xc_indexed_constant(a65b125cabfc00,x_sKEA).
xc_indexed_constant(a65b125cabfc01,'x_Function-Denotational').
xc_indexed_constant(a65b125cabfc01,x_SkeaLayerCaseFn).
xc_indexed_constant(a65b125cabfc01,x_isa).
xc_indexed_constant(a65b125cabfc02,x_SkeaLayerCaseFn).
xc_indexed_constant(a65b125cabfc02,x_arity).
xc_indexed_constant(a65b125cabfc03,x_Case).
xc_indexed_constant(a65b125cabfc03,x_SkeaLayerCaseFn).
xc_indexed_constant(a65b125cabfc03,x_arg1Isa).
xc_indexed_constant(a65b125cabfc04,x_NuSketchLayer).
xc_indexed_constant(a65b125cabfc04,x_SkeaLayerCaseFn).
xc_indexed_constant(a65b125cabfc04,x_arg2Isa).
xc_indexed_constant(a65b125cabfc05,x_Case).
xc_indexed_constant(a65b125cabfc05,x_SkeaLayerCaseFn).
xc_indexed_constant(a65b125cabfc05,x_resultIsa).
xc_indexed_constant(a65b125cabfc06,x_SkeaLayerCaseFn).
xc_indexed_constant(a65b125cabfc06,x_comment).
xc_indexed_constant(a65b125cabfc07,x_Microtheory).
xc_indexed_constant(a65b125cabfc07,x_SKEAReasoningCollectorMt).
xc_indexed_constant(a65b125cabfc07,x_isa).
xc_indexed_constant(a65b125cabfc08,x_CollectorMicrotheory).
xc_indexed_constant(a65b125cabfc08,x_SKEAReasoningCollectorMt).
xc_indexed_constant(a65b125cabfc08,x_isa).
xc_indexed_constant(a65b125cabfc09,x_SKEAMt).
xc_indexed_constant(a65b125cabfc09,x_SKEAReasoningCollectorMt).
xc_indexed_constant(a65b125cabfc09,x_genlMt).
xc_indexed_constant(a65b125cabfc0a,x_NuSketchReasoningCollectorMt).
xc_indexed_constant(a65b125cabfc0a,x_SKEAReasoningCollectorMt).
xc_indexed_constant(a65b125cabfc0a,x_genlMt).
xc_indexed_constant(a65b125cabfc0b,x_SKEAAnalogyMt).
xc_indexed_constant(a65b125cabfc0b,x_SKEAReasoningCollectorMt).
xc_indexed_constant(a65b125cabfc0b,x_genlMt).
xc_indexed_constant(a65b125cabfc0c,'x_SKEA-VisualConceptualMappingsMt').
xc_indexed_constant(a65b125cabfc0c,x_SKEAReasoningCollectorMt).
xc_indexed_constant(a65b125cabfc0c,x_genlMt).
xc_indexed_constant(a65b125cabfc0d,x_SKEAReasoningCollectorMt).
xc_indexed_constant(a65b125cabfc0d,x_comment).
kb_index_footer(17,'8f20c1a7060fd670dfa578f2c0a0acc54cd01476506f087679f5debad28aa057','8c60535b8507b2c4d66575a31f146e25671388183b22d43f998cf29abc6e7548').
