kb_index_header(index_header{count:28,digest:'46cbe68cb51d7687e39a845335b31fd5b883218e1fa19390e2c36525d542e06a',normalizedDigest:abb489d8cc4f6a756e91f2e0f40aced2c9b1a80e9d37258f8ad36825ad8656c6,normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',sourceHash:'5d33597aae2d0e423a1e33826ce17d55ce16f3764fb9768cfd1c0529057f8db1'}).
kb_index_data(index{constants:[-(x_ActionModelMtFn,1),-(x_CompanionsMt,1),-(x_DirectInfluences,2),-(x_ExecutionTraces,1),-('x_Freeciv-TheGame',18),-('x_Freeciv-defaultMt',3),-(x_FreecivMt,2),-(x_FreecivPlanMt,2),-(x_FreecivPlanningDomain,7),-(x_HTNPlanner,1),-(x_IndirectInfluences,2),-(x_Influences,3),-(x_LanguageMtFn,1),-(x_LearnActionModelFn,2),-(x_LearnQualitativeModelFn,3),-(x_LearnStrategicModelFn,2),-(x_LearnedKnowledgeMtFn,5),-(x_Microtheory,10),-(x_PlayingFn,1),-(x_QPTheoryMt,1),-(x_QualitativeModelMtFn,1),-(x_SpindleMtFn,7),-(x_StrategyModelMtFn,1),-(x_genlMt,12),-(x_isa,10),-(x_learnedKnowledgeMicrotheory,1),-(x_learningGoalForCompanion,3),-(x_subgoalFor,2)],entries:[entry(a65b134dbbb090,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',7,[x_FreecivMt,x_Microtheory,x_isa]),entry(a65b134dbbb091,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',9,['x_Freeciv-TheGame',x_LanguageMtFn,x_Microtheory,x_isa]),entry(a65b134dbbb092,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',12,['x_Freeciv-defaultMt',x_Microtheory,x_isa]),entry(a65b134dbbb093,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',13,['x_Freeciv-defaultMt',x_FreecivMt,x_genlMt]),entry(a65b134dbbb094,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',15,[x_FreecivPlanningDomain,x_Microtheory,x_isa]),entry(a65b134dbbb095,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',16,['x_Freeciv-defaultMt',x_FreecivPlanningDomain,x_genlMt]),entry(a65b134dbbb096,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',17,[x_FreecivPlanningDomain,x_HTNPlanner,x_genlMt]),entry(a65b134dbbb097,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',18,[x_FreecivPlanningDomain,x_QPTheoryMt,x_genlMt]),entry(a65b134dbbb098,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',19,[x_CompanionsMt,x_FreecivPlanningDomain,x_genlMt]),entry(a65b134dbbb099,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',20,['x_Freeciv-TheGame',x_FreecivPlanningDomain,x_LearnedKnowledgeMtFn,x_genlMt]),entry(a65b134dbbb09a,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',22,[x_FreecivPlanMt,x_Microtheory,x_isa]),entry(a65b134dbbb09b,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',23,[x_FreecivPlanMt,x_FreecivPlanningDomain,x_genlMt]),entry(a65b134dbbb09c,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',41,[x_ActionModelMtFn,'x_Freeciv-TheGame',x_LearnedKnowledgeMtFn,x_genlMt]),entry(a65b134dbbb09d,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',42,['x_Freeciv-TheGame',x_LearnedKnowledgeMtFn,x_QualitativeModelMtFn,x_genlMt]),entry(a65b134dbbb09e,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',43,['x_Freeciv-TheGame',x_LearnedKnowledgeMtFn,x_StrategyModelMtFn,x_genlMt]),entry(a65b134dbbb09f,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',45,['x_Freeciv-TheGame',x_Microtheory,x_PlayingFn,x_SpindleMtFn,x_isa]),entry(a65b134dbbb0a0,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',46,[x_DirectInfluences,'x_Freeciv-TheGame',x_Microtheory,x_SpindleMtFn,x_isa]),entry(a65b134dbbb0a1,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',47,['x_Freeciv-TheGame',x_IndirectInfluences,x_Microtheory,x_SpindleMtFn,x_isa]),entry(a65b134dbbb0a2,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',48,[x_ExecutionTraces,'x_Freeciv-TheGame',x_Microtheory,x_SpindleMtFn,x_isa]),entry(a65b134dbbb0a3,signature(x_isa,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',51,['x_Freeciv-TheGame',x_Influences,x_Microtheory,x_SpindleMtFn,x_isa]),entry(a65b134dbbb0a4,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',52,[x_DirectInfluences,'x_Freeciv-TheGame',x_Influences,x_SpindleMtFn,x_genlMt]),entry(a65b134dbbb0a5,signature(x_genlMt,2),x_BaseKB,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',53,['x_Freeciv-TheGame',x_IndirectInfluences,x_Influences,x_SpindleMtFn,x_genlMt]),entry(a65b134dbbb0a6,signature(x_learningGoalForCompanion,1),x_StrategyModelMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',58,['x_Freeciv-TheGame',x_LearnStrategicModelFn,x_learningGoalForCompanion]),entry(a65b134dbbb0a7,signature(x_learningGoalForCompanion,1),x_QualitativeModelMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',67,['x_Freeciv-TheGame',x_LearnQualitativeModelFn,x_learningGoalForCompanion]),entry(a65b134dbbb0a8,signature(x_learningGoalForCompanion,1),x_ActionModelMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',71,['x_Freeciv-TheGame',x_LearnActionModelFn,x_learningGoalForCompanion]),entry(a65b134dbbb0a9,signature(x_subgoalFor,2),x_LearnedKnowledgeMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',78,['x_Freeciv-TheGame',x_LearnActionModelFn,x_LearnQualitativeModelFn,x_subgoalFor]),entry(a65b134dbbb0aa,signature(x_subgoalFor,2),x_LearnedKnowledgeMtFn('x_Freeciv-TheGame'),'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',79,['x_Freeciv-TheGame',x_LearnQualitativeModelFn,x_LearnStrategicModelFn,x_subgoalFor]),entry(a65b134dbbb0ab,signature(x_learnedKnowledgeMicrotheory,2),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf',83,['x_Freeciv-TheGame',x_LearnedKnowledgeMtFn,x_learnedKnowledgeMicrotheory])],predicates:[-(signature(x_genlMt,2),12),-(signature(x_isa,2),10),-(signature(x_learnedKnowledgeMicrotheory,2),1),-(signature(x_learningGoalForCompanion,1),3),-(signature(x_subgoalFor,2),2)],rankedConstants:[-(18,'x_Freeciv-TheGame'),-(12,x_genlMt),-(10,x_isa),-(10,x_Microtheory),-(7,x_SpindleMtFn),-(7,x_FreecivPlanningDomain),-(5,x_LearnedKnowledgeMtFn),-(3,x_learningGoalForCompanion),-(3,x_LearnQualitativeModelFn),-(3,x_Influences),-(3,'x_Freeciv-defaultMt'),-(2,x_subgoalFor),-(2,x_LearnStrategicModelFn),-(2,x_LearnActionModelFn),-(2,x_IndirectInfluences),-(2,x_FreecivPlanMt),-(2,x_FreecivMt),-(2,x_DirectInfluences),-(1,x_learnedKnowledgeMicrotheory),-(1,x_StrategyModelMtFn),-(1,x_QualitativeModelMtFn),-(1,x_QPTheoryMt),-(1,x_PlayingFn),-(1,x_LanguageMtFn),-(1,x_HTNPlanner),-(1,x_ExecutionTraces),-(1,x_CompanionsMt),-(1,x_ActionModelMtFn)],rankedPredicates:[-(12,signature(x_genlMt,2)),-(10,signature(x_isa,2)),-(3,signature(x_learningGoalForCompanion,1)),-(2,signature(x_subgoalFor,2)),-(1,signature(x_learnedKnowledgeMicrotheory,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-microtheories.krf'}).
xc_indexed_constant(a65b134dbbb090,x_FreecivMt).
xc_indexed_constant(a65b134dbbb090,x_Microtheory).
xc_indexed_constant(a65b134dbbb090,x_isa).
xc_indexed_constant(a65b134dbbb091,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb091,x_LanguageMtFn).
xc_indexed_constant(a65b134dbbb091,x_Microtheory).
xc_indexed_constant(a65b134dbbb091,x_isa).
xc_indexed_constant(a65b134dbbb092,'x_Freeciv-defaultMt').
xc_indexed_constant(a65b134dbbb092,x_Microtheory).
xc_indexed_constant(a65b134dbbb092,x_isa).
xc_indexed_constant(a65b134dbbb093,'x_Freeciv-defaultMt').
xc_indexed_constant(a65b134dbbb093,x_FreecivMt).
xc_indexed_constant(a65b134dbbb093,x_genlMt).
xc_indexed_constant(a65b134dbbb094,x_FreecivPlanningDomain).
xc_indexed_constant(a65b134dbbb094,x_Microtheory).
xc_indexed_constant(a65b134dbbb094,x_isa).
xc_indexed_constant(a65b134dbbb095,'x_Freeciv-defaultMt').
xc_indexed_constant(a65b134dbbb095,x_FreecivPlanningDomain).
xc_indexed_constant(a65b134dbbb095,x_genlMt).
xc_indexed_constant(a65b134dbbb096,x_FreecivPlanningDomain).
xc_indexed_constant(a65b134dbbb096,x_HTNPlanner).
xc_indexed_constant(a65b134dbbb096,x_genlMt).
xc_indexed_constant(a65b134dbbb097,x_FreecivPlanningDomain).
xc_indexed_constant(a65b134dbbb097,x_QPTheoryMt).
xc_indexed_constant(a65b134dbbb097,x_genlMt).
xc_indexed_constant(a65b134dbbb098,x_CompanionsMt).
xc_indexed_constant(a65b134dbbb098,x_FreecivPlanningDomain).
xc_indexed_constant(a65b134dbbb098,x_genlMt).
xc_indexed_constant(a65b134dbbb099,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb099,x_FreecivPlanningDomain).
xc_indexed_constant(a65b134dbbb099,x_LearnedKnowledgeMtFn).
xc_indexed_constant(a65b134dbbb099,x_genlMt).
xc_indexed_constant(a65b134dbbb09a,x_FreecivPlanMt).
xc_indexed_constant(a65b134dbbb09a,x_Microtheory).
xc_indexed_constant(a65b134dbbb09a,x_isa).
xc_indexed_constant(a65b134dbbb09b,x_FreecivPlanMt).
xc_indexed_constant(a65b134dbbb09b,x_FreecivPlanningDomain).
xc_indexed_constant(a65b134dbbb09b,x_genlMt).
xc_indexed_constant(a65b134dbbb09c,x_ActionModelMtFn).
xc_indexed_constant(a65b134dbbb09c,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb09c,x_LearnedKnowledgeMtFn).
xc_indexed_constant(a65b134dbbb09c,x_genlMt).
xc_indexed_constant(a65b134dbbb09d,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb09d,x_LearnedKnowledgeMtFn).
xc_indexed_constant(a65b134dbbb09d,x_QualitativeModelMtFn).
xc_indexed_constant(a65b134dbbb09d,x_genlMt).
xc_indexed_constant(a65b134dbbb09e,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb09e,x_LearnedKnowledgeMtFn).
xc_indexed_constant(a65b134dbbb09e,x_StrategyModelMtFn).
xc_indexed_constant(a65b134dbbb09e,x_genlMt).
xc_indexed_constant(a65b134dbbb09f,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb09f,x_Microtheory).
xc_indexed_constant(a65b134dbbb09f,x_PlayingFn).
xc_indexed_constant(a65b134dbbb09f,x_SpindleMtFn).
xc_indexed_constant(a65b134dbbb09f,x_isa).
xc_indexed_constant(a65b134dbbb0a0,x_DirectInfluences).
xc_indexed_constant(a65b134dbbb0a0,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a0,x_Microtheory).
xc_indexed_constant(a65b134dbbb0a0,x_SpindleMtFn).
xc_indexed_constant(a65b134dbbb0a0,x_isa).
xc_indexed_constant(a65b134dbbb0a1,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a1,x_IndirectInfluences).
xc_indexed_constant(a65b134dbbb0a1,x_Microtheory).
xc_indexed_constant(a65b134dbbb0a1,x_SpindleMtFn).
xc_indexed_constant(a65b134dbbb0a1,x_isa).
xc_indexed_constant(a65b134dbbb0a2,x_ExecutionTraces).
xc_indexed_constant(a65b134dbbb0a2,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a2,x_Microtheory).
xc_indexed_constant(a65b134dbbb0a2,x_SpindleMtFn).
xc_indexed_constant(a65b134dbbb0a2,x_isa).
xc_indexed_constant(a65b134dbbb0a3,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a3,x_Influences).
xc_indexed_constant(a65b134dbbb0a3,x_Microtheory).
xc_indexed_constant(a65b134dbbb0a3,x_SpindleMtFn).
xc_indexed_constant(a65b134dbbb0a3,x_isa).
xc_indexed_constant(a65b134dbbb0a4,x_DirectInfluences).
xc_indexed_constant(a65b134dbbb0a4,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a4,x_Influences).
xc_indexed_constant(a65b134dbbb0a4,x_SpindleMtFn).
xc_indexed_constant(a65b134dbbb0a4,x_genlMt).
xc_indexed_constant(a65b134dbbb0a5,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a5,x_IndirectInfluences).
xc_indexed_constant(a65b134dbbb0a5,x_Influences).
xc_indexed_constant(a65b134dbbb0a5,x_SpindleMtFn).
xc_indexed_constant(a65b134dbbb0a5,x_genlMt).
xc_indexed_constant(a65b134dbbb0a6,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a6,x_LearnStrategicModelFn).
xc_indexed_constant(a65b134dbbb0a6,x_learningGoalForCompanion).
xc_indexed_constant(a65b134dbbb0a7,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a7,x_LearnQualitativeModelFn).
xc_indexed_constant(a65b134dbbb0a7,x_learningGoalForCompanion).
xc_indexed_constant(a65b134dbbb0a8,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a8,x_LearnActionModelFn).
xc_indexed_constant(a65b134dbbb0a8,x_learningGoalForCompanion).
xc_indexed_constant(a65b134dbbb0a9,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0a9,x_LearnActionModelFn).
xc_indexed_constant(a65b134dbbb0a9,x_LearnQualitativeModelFn).
xc_indexed_constant(a65b134dbbb0a9,x_subgoalFor).
xc_indexed_constant(a65b134dbbb0aa,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0aa,x_LearnQualitativeModelFn).
xc_indexed_constant(a65b134dbbb0aa,x_LearnStrategicModelFn).
xc_indexed_constant(a65b134dbbb0aa,x_subgoalFor).
xc_indexed_constant(a65b134dbbb0ab,'x_Freeciv-TheGame').
xc_indexed_constant(a65b134dbbb0ab,x_LearnedKnowledgeMtFn).
xc_indexed_constant(a65b134dbbb0ab,x_learnedKnowledgeMicrotheory).
kb_index_footer(28,'46cbe68cb51d7687e39a845335b31fd5b883218e1fa19390e2c36525d542e06a','0d3e2db02ed63c44b422b2b3f4b4e0964e346baf9c828844c1611cff47a102c2').
