kb_index_header(index_header{count:78,digest:'6d7ddf72afd437788c0a62e04b6f0915f021d88ff4d14692b6aebc99f117d492',normalizedDigest:'8fa43de14a70bca57380558a5807fc2a0c103badc276cfcea22eac7606a86dc0',normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',sourceHash:'32454ff30d912ead2079ea4c5cf3c73f9c3444ef4a58dad2888726f587762ddf'}).
kb_index_data(index{constants:[-(x_FoodPoints,9),-('x_FreeCiv-Building',1),-('x_FreeCiv-City',39),-('x_FreeCiv-Player',11),-('x_FreeCiv-TerrainTile',3),-('x_FreeCiv-Unit',14),-('x_FreeCiv-UnitType',7),-(x_FreeCivMoodFn,1),-(x_FreeCivPopulationFn,2),-(x_FreecivCitizenCountFn,9),-(x_FreecivLocation,3),-(x_FreecivStrengthFn,4),-(x_FreecivTileDistance,4),-(x_FreecivUnitCountFn,5),-(x_GoldPoints,8),-(x_HitPoints,5),-(x_LuxuryPoints,1),-(x_MeasurableQuantityFn,78),-(x_MovePoints,1),-(x_Number,1),-(x_PerFn,2),-(x_Percent,5),-(x_PollutionPoints,1),-(x_ProductionPoints,9),-(x_SciencePoints,3),-(x_TradePoints,6),-(x_Turns,5),-(x_VeteranLevel,1),-(x_angryCitizens,1),-(x_cityBuyCost,1),-(x_cityCoinageProduction,1),-(x_cityCorruption,1),-(x_cityFoodProduction,1),-(x_cityFoodReserves,1),-(x_cityFoodSurplus,1),-(x_cityGoldProduction,1),-(x_cityGoldSurplus,1),-(x_cityGranarySize,1),-(x_cityGrowthRate,1),-(x_cityHappiness,1),-(x_cityImprovementsUpkeep,1),-(x_cityLuxuryTotal,1),-(x_cityPollution,1),-(x_cityPopulation,1),-(x_cityScienceTotal,1),-(x_cityShieldProduction,1),-(x_cityShieldReserves,1),-(x_cityShieldSurplus,1),-(x_cityShieldWaste,1),-(x_citySize,1),-(x_cityTradeProduction,1),-(x_cityTradeSurplus,1),-(x_civBulbsPerTurn,1),-(x_civFoodSurplusTotal,1),-(x_civGoldProduction,1),-(x_civPopulation,1),-(x_civProductionTotal,1),-(x_contentCitizens,1),-(x_currentBulbsResearched,1),-(x_currentGold,1),-(x_currentHealth,1),-(x_currentHitpoints,1),-(x_currentLuxuryPercent,1),-(x_currentMovepoints,1),-(x_currentSciencePercent,1),-(x_currentTaxPercent,1),-(x_currentTechsResearched,1),-(x_happyCitizens,1),-(x_numDeployedMilitaryUnits,1),-(x_numEntertainers,1),-(x_numPresentMilitaryUnits,1),-(x_numScientists,1),-(x_numSupportedUnits,1),-(x_numTaxCollectors,1),-(x_numTurnsToBuild,1),-(x_numTurnsToComplete,1),-(x_numTurnsToGrow,1),-(x_numWorkers,1),-(x_objectTypeHasUpkeepGoldCost,1),-(x_quantityPrimitive,78),-(x_supportedUnitsFoodUpkeep,1),-(x_supportedUnitsShieldUpkeep,1),-(x_terrainBaseFoodProduction,1),-(x_terrainBaseShieldProduction,1),-(x_terrainBaseTradeProduction,1),-(x_tileFoodProduction,1),-(x_tileShieldProduction,1),-(x_tileTradeProduction,1),-(x_tradeRouteIncome,1),-(x_unhappyCitizens,1),-(x_unitHasAttackStrength,1),-(x_unitHasDefendStrength,1),-(x_unitHasFirepower,1),-(x_unitHasFoodUpkeep,1),-(x_unitHasFuelCapacity,1),-(x_unitHasHitpoints,1),-(x_unitHasMoveRate,1),-(x_unitHasShieldUpkeep,1),-(x_unitHasTransportCapacity,1),-(x_unitTypeHasAttackStrength,1),-(x_unitTypeHasDefendStrength,1),-(x_unitTypeHasFirepower,1),-(x_unitTypeHasFuelCapacity,1),-(x_unitTypeHasHitpoints,1),-(x_unitTypeHasMoveRate,1),-(x_unitTypeHasTransportCapacity,1),-(x_veteranStatus,1)],entries:[entry(a65b12821fee76,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',32,['x_FreeCiv-Player',x_MeasurableQuantityFn,x_Percent,x_currentTaxPercent,x_quantityPrimitive]),entry(a65b12821fee77,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',33,['x_FreeCiv-Player',x_MeasurableQuantityFn,x_Percent,x_currentSciencePercent,x_quantityPrimitive]),entry(a65b12821fee78,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',34,['x_FreeCiv-Player',x_MeasurableQuantityFn,x_Percent,x_currentLuxuryPercent,x_quantityPrimitive]),entry(a65b12821fee79,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',35,['x_FreeCiv-Player',x_GoldPoints,x_MeasurableQuantityFn,x_currentGold,x_quantityPrimitive]),entry(a65b12821fee7a,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',36,['x_FreeCiv-Player',x_MeasurableQuantityFn,x_SciencePoints,x_currentBulbsResearched,x_quantityPrimitive]),entry(a65b12821fee7b,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',37,['x_FreeCiv-Player',x_MeasurableQuantityFn,x_Number,x_currentTechsResearched,x_quantityPrimitive]),entry(a65b12821fee7c,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',38,['x_FreeCiv-Player',x_FreeCivPopulationFn,x_MeasurableQuantityFn,x_civPopulation,x_quantityPrimitive]),entry(a65b12821fee7d,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',39,[x_FoodPoints,'x_FreeCiv-Player',x_MeasurableQuantityFn,x_civFoodSurplusTotal,x_quantityPrimitive]),entry(a65b12821fee7e,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',40,['x_FreeCiv-Player',x_MeasurableQuantityFn,x_SciencePoints,x_civBulbsPerTurn,x_quantityPrimitive]),entry(a65b12821fee7f,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',41,['x_FreeCiv-Player',x_GoldPoints,x_MeasurableQuantityFn,x_civGoldProduction,x_quantityPrimitive]),entry(a65b12821fee80,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',42,['x_FreeCiv-Player',x_MeasurableQuantityFn,x_ProductionPoints,x_civProductionTotal,x_quantityPrimitive]),entry(a65b12821fee81,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',43,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_citySize,x_quantityPrimitive]),entry(a65b12821fee82,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',44,['x_FreeCiv-City',x_GoldPoints,x_MeasurableQuantityFn,x_cityBuyCost,x_quantityPrimitive]),entry(a65b12821fee83,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',45,[x_FoodPoints,x_FreecivLocation,x_MeasurableQuantityFn,x_quantityPrimitive,x_tileFoodProduction]),entry(a65b12821fee84,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',46,[x_FreecivLocation,x_MeasurableQuantityFn,x_ProductionPoints,x_quantityPrimitive,x_tileShieldProduction]),entry(a65b12821fee85,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',47,[x_FreecivLocation,x_MeasurableQuantityFn,x_TradePoints,x_quantityPrimitive,x_tileTradeProduction]),entry(a65b12821fee86,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',48,[x_FoodPoints,'x_FreeCiv-City',x_MeasurableQuantityFn,x_cityFoodProduction,x_quantityPrimitive]),entry(a65b12821fee87,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',49,['x_FreeCiv-City',x_MeasurableQuantityFn,x_ProductionPoints,x_cityShieldProduction,x_quantityPrimitive]),entry(a65b12821fee88,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',50,['x_FreeCiv-City',x_MeasurableQuantityFn,x_TradePoints,x_cityTradeProduction,x_quantityPrimitive]),entry(a65b12821fee89,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',51,[x_FoodPoints,'x_FreeCiv-City',x_MeasurableQuantityFn,x_cityFoodSurplus,x_quantityPrimitive]),entry(a65b12821fee8a,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',52,['x_FreeCiv-City',x_MeasurableQuantityFn,x_ProductionPoints,x_cityShieldSurplus,x_quantityPrimitive]),entry(a65b12821fee8b,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',53,['x_FreeCiv-City',x_MeasurableQuantityFn,x_TradePoints,x_cityTradeSurplus,x_quantityPrimitive]),entry(a65b12821fee8c,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',54,[x_FoodPoints,'x_FreeCiv-City',x_MeasurableQuantityFn,x_cityFoodReserves,x_quantityPrimitive]),entry(a65b12821fee8d,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',55,['x_FreeCiv-City',x_MeasurableQuantityFn,x_ProductionPoints,x_cityShieldReserves,x_quantityPrimitive]),entry(a65b12821fee8e,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',56,['x_FreeCiv-City',x_GoldPoints,x_MeasurableQuantityFn,x_cityGoldProduction,x_quantityPrimitive]),entry(a65b12821fee8f,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',57,['x_FreeCiv-City',x_GoldPoints,x_MeasurableQuantityFn,x_cityGoldSurplus,x_quantityPrimitive]),entry(a65b12821fee90,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',58,['x_FreeCiv-City',x_MeasurableQuantityFn,x_SciencePoints,x_cityScienceTotal,x_quantityPrimitive]),entry(a65b12821fee91,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',59,['x_FreeCiv-City',x_LuxuryPoints,x_MeasurableQuantityFn,x_cityLuxuryTotal,x_quantityPrimitive]),entry(a65b12821fee92,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',60,['x_FreeCiv-City',x_MeasurableQuantityFn,x_PollutionPoints,x_cityPollution,x_quantityPrimitive]),entry(a65b12821fee93,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',61,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_happyCitizens,x_quantityPrimitive]),entry(a65b12821fee94,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',62,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_contentCitizens,x_quantityPrimitive]),entry(a65b12821fee95,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',63,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_quantityPrimitive,x_unhappyCitizens]),entry(a65b12821fee96,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',64,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_angryCitizens,x_quantityPrimitive]),entry(a65b12821fee97,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',66,['x_FreeCiv-City',x_FreeCivMoodFn,x_MeasurableQuantityFn,x_cityHappiness,x_quantityPrimitive]),entry(a65b12821fee98,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',67,['x_FreeCiv-City',x_MeasurableQuantityFn,x_TradePoints,x_cityCorruption,x_quantityPrimitive]),entry(a65b12821fee99,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',68,['x_FreeCiv-City',x_MeasurableQuantityFn,x_ProductionPoints,x_cityShieldWaste,x_quantityPrimitive]),entry(a65b12821fee9a,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',69,[x_FoodPoints,'x_FreeCiv-City',x_MeasurableQuantityFn,x_cityGranarySize,x_quantityPrimitive]),entry(a65b12821fee9b,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',70,['x_FreeCiv-City',x_MeasurableQuantityFn,x_Percent,x_cityGrowthRate,x_quantityPrimitive]),entry(a65b12821fee9c,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',71,['x_FreeCiv-City',x_MeasurableQuantityFn,x_Turns,x_numTurnsToGrow,x_quantityPrimitive]),entry(a65b12821fee9d,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',72,['x_FreeCiv-City',x_MeasurableQuantityFn,x_Turns,x_numTurnsToBuild,x_quantityPrimitive]),entry(a65b12821fee9e,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',73,['x_FreeCiv-Unit',x_MeasurableQuantityFn,x_Turns,x_numTurnsToComplete,x_quantityPrimitive]),entry(a65b12821fee9f,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',74,['x_FreeCiv-City',x_FreeCivPopulationFn,x_MeasurableQuantityFn,x_cityPopulation,x_quantityPrimitive]),entry(a65b12821feea0,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',75,['x_FreeCiv-City',x_MeasurableQuantityFn,x_ProductionPoints,x_quantityPrimitive,x_supportedUnitsShieldUpkeep]),entry(a65b12821feea1,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',76,[x_FoodPoints,'x_FreeCiv-City',x_MeasurableQuantityFn,x_quantityPrimitive,x_supportedUnitsFoodUpkeep]),entry(a65b12821feea2,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',77,['x_FreeCiv-City',x_GoldPoints,x_MeasurableQuantityFn,x_cityImprovementsUpkeep,x_quantityPrimitive]),entry(a65b12821feea3,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',78,['x_FreeCiv-City',x_GoldPoints,x_MeasurableQuantityFn,x_cityCoinageProduction,x_quantityPrimitive]),entry(a65b12821feea4,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',79,['x_FreeCiv-Building',x_GoldPoints,x_MeasurableQuantityFn,x_objectTypeHasUpkeepGoldCost,x_quantityPrimitive]),entry(a65b12821feea5,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',80,['x_FreeCiv-Unit',x_MeasurableQuantityFn,x_ProductionPoints,x_quantityPrimitive,x_unitHasShieldUpkeep]),entry(a65b12821feea6,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',81,[x_FoodPoints,'x_FreeCiv-Unit',x_MeasurableQuantityFn,x_quantityPrimitive,x_unitHasFoodUpkeep]),entry(a65b12821feea7,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',82,['x_FreeCiv-City',x_MeasurableQuantityFn,x_TradePoints,x_quantityPrimitive,x_tradeRouteIncome]),entry(a65b12821feea8,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',84,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_numTaxCollectors,x_quantityPrimitive]),entry(a65b12821feea9,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',85,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_numScientists,x_quantityPrimitive]),entry(a65b12821feeaa,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',86,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_numEntertainers,x_quantityPrimitive]),entry(a65b12821feeab,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',87,['x_FreeCiv-City',x_FreecivCitizenCountFn,x_MeasurableQuantityFn,x_numWorkers,x_quantityPrimitive]),entry(a65b12821feeac,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',89,['x_FreeCiv-Unit',x_HitPoints,x_MeasurableQuantityFn,x_currentHitpoints,x_quantityPrimitive]),entry(a65b12821feead,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',90,['x_FreeCiv-Unit',x_MeasurableQuantityFn,x_Percent,x_currentHealth,x_quantityPrimitive]),entry(a65b12821feeae,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',91,['x_FreeCiv-Unit',x_MeasurableQuantityFn,x_MovePoints,x_currentMovepoints,x_quantityPrimitive]),entry(a65b12821feeaf,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',92,['x_FreeCiv-Unit',x_MeasurableQuantityFn,x_VeteranLevel,x_quantityPrimitive,x_veteranStatus]),entry(a65b12821feeb0,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',94,[x_FoodPoints,'x_FreeCiv-TerrainTile',x_MeasurableQuantityFn,x_quantityPrimitive,x_terrainBaseFoodProduction]),entry(a65b12821feeb1,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',95,['x_FreeCiv-TerrainTile',x_MeasurableQuantityFn,x_ProductionPoints,x_quantityPrimitive,x_terrainBaseShieldProduction]),entry(a65b12821feeb2,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',96,['x_FreeCiv-TerrainTile',x_MeasurableQuantityFn,x_TradePoints,x_quantityPrimitive,x_terrainBaseTradeProduction]),entry(a65b12821feeb3,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',110,['x_FreeCiv-City',x_FreecivUnitCountFn,x_MeasurableQuantityFn,x_numSupportedUnits,x_quantityPrimitive]),entry(a65b12821feeb4,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',111,['x_FreeCiv-City',x_FreecivUnitCountFn,x_MeasurableQuantityFn,x_numPresentMilitaryUnits,x_quantityPrimitive]),entry(a65b12821feeb5,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',112,['x_FreeCiv-City',x_FreecivUnitCountFn,x_MeasurableQuantityFn,x_numDeployedMilitaryUnits,x_quantityPrimitive]),entry(a65b12821feeb6,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',118,['x_FreeCiv-Unit',x_FreecivStrengthFn,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitHasDefendStrength]),entry(a65b12821feeb7,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',119,['x_FreeCiv-Unit',x_FreecivStrengthFn,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitHasAttackStrength]),entry(a65b12821feeb8,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',120,['x_FreeCiv-Unit',x_FreecivTileDistance,x_MeasurableQuantityFn,x_PerFn,x_Turns,x_quantityPrimitive,x_unitHasMoveRate]),entry(a65b12821feeb9,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',121,['x_FreeCiv-Unit',x_FreecivUnitCountFn,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitHasTransportCapacity]),entry(a65b12821feeba,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',122,['x_FreeCiv-Unit',x_FreecivTileDistance,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitHasFuelCapacity]),entry(a65b12821feebb,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',123,['x_FreeCiv-Unit',x_HitPoints,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitHasHitpoints]),entry(a65b12821feebc,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',124,['x_FreeCiv-Unit',x_HitPoints,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitHasFirepower]),entry(a65b12821feebd,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',126,['x_FreeCiv-UnitType',x_FreecivStrengthFn,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitTypeHasDefendStrength]),entry(a65b12821feebe,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',127,['x_FreeCiv-UnitType',x_FreecivStrengthFn,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitTypeHasAttackStrength]),entry(a65b12821feebf,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',128,['x_FreeCiv-UnitType',x_FreecivTileDistance,x_MeasurableQuantityFn,x_PerFn,x_Turns,x_quantityPrimitive,x_unitTypeHasMoveRate]),entry(a65b12821feec0,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',129,['x_FreeCiv-UnitType',x_FreecivUnitCountFn,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitTypeHasTransportCapacity]),entry(a65b12821feec1,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',130,['x_FreeCiv-UnitType',x_FreecivTileDistance,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitTypeHasFuelCapacity]),entry(a65b12821feec2,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',131,['x_FreeCiv-UnitType',x_HitPoints,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitTypeHasHitpoints]),entry(a65b12821feec3,signature(x_quantityPrimitive,3),x_FreecivMt,'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf',132,['x_FreeCiv-UnitType',x_HitPoints,x_MeasurableQuantityFn,x_quantityPrimitive,x_unitTypeHasFirepower])],predicates:[-(signature(x_quantityPrimitive,3),78)],rankedConstants:[-(78,x_quantityPrimitive),-(78,x_MeasurableQuantityFn),-(39,'x_FreeCiv-City'),-(14,'x_FreeCiv-Unit'),-(11,'x_FreeCiv-Player'),-(9,x_ProductionPoints),-(9,x_FreecivCitizenCountFn),-(9,x_FoodPoints),-(8,x_GoldPoints),-(7,'x_FreeCiv-UnitType'),-(6,x_TradePoints),-(5,x_Turns),-(5,x_Percent),-(5,x_HitPoints),-(5,x_FreecivUnitCountFn),-(4,x_FreecivTileDistance),-(4,x_FreecivStrengthFn),-(3,x_SciencePoints),-(3,x_FreecivLocation),-(3,'x_FreeCiv-TerrainTile'),-(2,x_PerFn),-(2,x_FreeCivPopulationFn),-(1,x_veteranStatus),-(1,x_unitTypeHasTransportCapacity),-(1,x_unitTypeHasMoveRate),-(1,x_unitTypeHasHitpoints),-(1,x_unitTypeHasFuelCapacity),-(1,x_unitTypeHasFirepower),-(1,x_unitTypeHasDefendStrength),-(1,x_unitTypeHasAttackStrength),-(1,x_unitHasTransportCapacity),-(1,x_unitHasShieldUpkeep),-(1,x_unitHasMoveRate),-(1,x_unitHasHitpoints),-(1,x_unitHasFuelCapacity),-(1,x_unitHasFoodUpkeep),-(1,x_unitHasFirepower),-(1,x_unitHasDefendStrength),-(1,x_unitHasAttackStrength),-(1,x_unhappyCitizens),-(1,x_tradeRouteIncome),-(1,x_tileTradeProduction),-(1,x_tileShieldProduction),-(1,x_tileFoodProduction),-(1,x_terrainBaseTradeProduction),-(1,x_terrainBaseShieldProduction),-(1,x_terrainBaseFoodProduction),-(1,x_supportedUnitsShieldUpkeep),-(1,x_supportedUnitsFoodUpkeep),-(1,x_objectTypeHasUpkeepGoldCost),-(1,x_numWorkers),-(1,x_numTurnsToGrow),-(1,x_numTurnsToComplete),-(1,x_numTurnsToBuild),-(1,x_numTaxCollectors),-(1,x_numSupportedUnits),-(1,x_numScientists),-(1,x_numPresentMilitaryUnits),-(1,x_numEntertainers),-(1,x_numDeployedMilitaryUnits),-(1,x_happyCitizens),-(1,x_currentTechsResearched),-(1,x_currentTaxPercent),-(1,x_currentSciencePercent),-(1,x_currentMovepoints),-(1,x_currentLuxuryPercent),-(1,x_currentHitpoints),-(1,x_currentHealth),-(1,x_currentGold),-(1,x_currentBulbsResearched),-(1,x_contentCitizens),-(1,x_civProductionTotal),-(1,x_civPopulation),-(1,x_civGoldProduction),-(1,x_civFoodSurplusTotal),-(1,x_civBulbsPerTurn),-(1,x_cityTradeSurplus),-(1,x_cityTradeProduction),-(1,x_citySize),-(1,x_cityShieldWaste),-(1,x_cityShieldSurplus),-(1,x_cityShieldReserves),-(1,x_cityShieldProduction),-(1,x_cityScienceTotal),-(1,x_cityPopulation),-(1,x_cityPollution),-(1,x_cityLuxuryTotal),-(1,x_cityImprovementsUpkeep),-(1,x_cityHappiness),-(1,x_cityGrowthRate),-(1,x_cityGranarySize),-(1,x_cityGoldSurplus),-(1,x_cityGoldProduction),-(1,x_cityFoodSurplus),-(1,x_cityFoodReserves),-(1,x_cityFoodProduction),-(1,x_cityCorruption),-(1,x_cityCoinageProduction),-(1,x_cityBuyCost),-(1,x_angryCitizens),-(1,x_VeteranLevel),-(1,x_PollutionPoints),-(1,x_Number),-(1,x_MovePoints),-(1,x_LuxuryPoints),-(1,x_FreeCivMoodFn),-(1,'x_FreeCiv-Building')],rankedPredicates:[-(78,signature(x_quantityPrimitive,3))],source:'c:/snet/petta/repos/openworld_dr/KBs/freecivai/flat-files/fc-quantities.krf'}).
xc_indexed_constant(a65b12821fee76,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee76,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee76,x_Percent).
xc_indexed_constant(a65b12821fee76,x_currentTaxPercent).
xc_indexed_constant(a65b12821fee76,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee77,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee77,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee77,x_Percent).
xc_indexed_constant(a65b12821fee77,x_currentSciencePercent).
xc_indexed_constant(a65b12821fee77,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee78,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee78,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee78,x_Percent).
xc_indexed_constant(a65b12821fee78,x_currentLuxuryPercent).
xc_indexed_constant(a65b12821fee78,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee79,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee79,x_GoldPoints).
xc_indexed_constant(a65b12821fee79,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee79,x_currentGold).
xc_indexed_constant(a65b12821fee79,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee7a,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee7a,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee7a,x_SciencePoints).
xc_indexed_constant(a65b12821fee7a,x_currentBulbsResearched).
xc_indexed_constant(a65b12821fee7a,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee7b,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee7b,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee7b,x_Number).
xc_indexed_constant(a65b12821fee7b,x_currentTechsResearched).
xc_indexed_constant(a65b12821fee7b,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee7c,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee7c,x_FreeCivPopulationFn).
xc_indexed_constant(a65b12821fee7c,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee7c,x_civPopulation).
xc_indexed_constant(a65b12821fee7c,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee7d,x_FoodPoints).
xc_indexed_constant(a65b12821fee7d,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee7d,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee7d,x_civFoodSurplusTotal).
xc_indexed_constant(a65b12821fee7d,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee7e,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee7e,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee7e,x_SciencePoints).
xc_indexed_constant(a65b12821fee7e,x_civBulbsPerTurn).
xc_indexed_constant(a65b12821fee7e,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee7f,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee7f,x_GoldPoints).
xc_indexed_constant(a65b12821fee7f,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee7f,x_civGoldProduction).
xc_indexed_constant(a65b12821fee7f,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee80,'x_FreeCiv-Player').
xc_indexed_constant(a65b12821fee80,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee80,x_ProductionPoints).
xc_indexed_constant(a65b12821fee80,x_civProductionTotal).
xc_indexed_constant(a65b12821fee80,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee81,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee81,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821fee81,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee81,x_citySize).
xc_indexed_constant(a65b12821fee81,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee82,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee82,x_GoldPoints).
xc_indexed_constant(a65b12821fee82,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee82,x_cityBuyCost).
xc_indexed_constant(a65b12821fee82,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee83,x_FoodPoints).
xc_indexed_constant(a65b12821fee83,x_FreecivLocation).
xc_indexed_constant(a65b12821fee83,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee83,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee83,x_tileFoodProduction).
xc_indexed_constant(a65b12821fee84,x_FreecivLocation).
xc_indexed_constant(a65b12821fee84,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee84,x_ProductionPoints).
xc_indexed_constant(a65b12821fee84,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee84,x_tileShieldProduction).
xc_indexed_constant(a65b12821fee85,x_FreecivLocation).
xc_indexed_constant(a65b12821fee85,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee85,x_TradePoints).
xc_indexed_constant(a65b12821fee85,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee85,x_tileTradeProduction).
xc_indexed_constant(a65b12821fee86,x_FoodPoints).
xc_indexed_constant(a65b12821fee86,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee86,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee86,x_cityFoodProduction).
xc_indexed_constant(a65b12821fee86,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee87,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee87,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee87,x_ProductionPoints).
xc_indexed_constant(a65b12821fee87,x_cityShieldProduction).
xc_indexed_constant(a65b12821fee87,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee88,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee88,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee88,x_TradePoints).
xc_indexed_constant(a65b12821fee88,x_cityTradeProduction).
xc_indexed_constant(a65b12821fee88,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee89,x_FoodPoints).
xc_indexed_constant(a65b12821fee89,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee89,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee89,x_cityFoodSurplus).
xc_indexed_constant(a65b12821fee89,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee8a,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee8a,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee8a,x_ProductionPoints).
xc_indexed_constant(a65b12821fee8a,x_cityShieldSurplus).
xc_indexed_constant(a65b12821fee8a,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee8b,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee8b,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee8b,x_TradePoints).
xc_indexed_constant(a65b12821fee8b,x_cityTradeSurplus).
xc_indexed_constant(a65b12821fee8b,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee8c,x_FoodPoints).
xc_indexed_constant(a65b12821fee8c,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee8c,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee8c,x_cityFoodReserves).
xc_indexed_constant(a65b12821fee8c,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee8d,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee8d,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee8d,x_ProductionPoints).
xc_indexed_constant(a65b12821fee8d,x_cityShieldReserves).
xc_indexed_constant(a65b12821fee8d,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee8e,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee8e,x_GoldPoints).
xc_indexed_constant(a65b12821fee8e,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee8e,x_cityGoldProduction).
xc_indexed_constant(a65b12821fee8e,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee8f,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee8f,x_GoldPoints).
xc_indexed_constant(a65b12821fee8f,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee8f,x_cityGoldSurplus).
xc_indexed_constant(a65b12821fee8f,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee90,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee90,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee90,x_SciencePoints).
xc_indexed_constant(a65b12821fee90,x_cityScienceTotal).
xc_indexed_constant(a65b12821fee90,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee91,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee91,x_LuxuryPoints).
xc_indexed_constant(a65b12821fee91,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee91,x_cityLuxuryTotal).
xc_indexed_constant(a65b12821fee91,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee92,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee92,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee92,x_PollutionPoints).
xc_indexed_constant(a65b12821fee92,x_cityPollution).
xc_indexed_constant(a65b12821fee92,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee93,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee93,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821fee93,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee93,x_happyCitizens).
xc_indexed_constant(a65b12821fee93,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee94,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee94,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821fee94,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee94,x_contentCitizens).
xc_indexed_constant(a65b12821fee94,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee95,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee95,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821fee95,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee95,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee95,x_unhappyCitizens).
xc_indexed_constant(a65b12821fee96,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee96,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821fee96,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee96,x_angryCitizens).
xc_indexed_constant(a65b12821fee96,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee97,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee97,x_FreeCivMoodFn).
xc_indexed_constant(a65b12821fee97,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee97,x_cityHappiness).
xc_indexed_constant(a65b12821fee97,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee98,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee98,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee98,x_TradePoints).
xc_indexed_constant(a65b12821fee98,x_cityCorruption).
xc_indexed_constant(a65b12821fee98,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee99,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee99,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee99,x_ProductionPoints).
xc_indexed_constant(a65b12821fee99,x_cityShieldWaste).
xc_indexed_constant(a65b12821fee99,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee9a,x_FoodPoints).
xc_indexed_constant(a65b12821fee9a,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee9a,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee9a,x_cityGranarySize).
xc_indexed_constant(a65b12821fee9a,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee9b,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee9b,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee9b,x_Percent).
xc_indexed_constant(a65b12821fee9b,x_cityGrowthRate).
xc_indexed_constant(a65b12821fee9b,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee9c,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee9c,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee9c,x_Turns).
xc_indexed_constant(a65b12821fee9c,x_numTurnsToGrow).
xc_indexed_constant(a65b12821fee9c,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee9d,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee9d,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee9d,x_Turns).
xc_indexed_constant(a65b12821fee9d,x_numTurnsToBuild).
xc_indexed_constant(a65b12821fee9d,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee9e,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821fee9e,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee9e,x_Turns).
xc_indexed_constant(a65b12821fee9e,x_numTurnsToComplete).
xc_indexed_constant(a65b12821fee9e,x_quantityPrimitive).
xc_indexed_constant(a65b12821fee9f,'x_FreeCiv-City').
xc_indexed_constant(a65b12821fee9f,x_FreeCivPopulationFn).
xc_indexed_constant(a65b12821fee9f,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821fee9f,x_cityPopulation).
xc_indexed_constant(a65b12821fee9f,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea0,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feea0,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea0,x_ProductionPoints).
xc_indexed_constant(a65b12821feea0,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea0,x_supportedUnitsShieldUpkeep).
xc_indexed_constant(a65b12821feea1,x_FoodPoints).
xc_indexed_constant(a65b12821feea1,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feea1,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea1,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea1,x_supportedUnitsFoodUpkeep).
xc_indexed_constant(a65b12821feea2,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feea2,x_GoldPoints).
xc_indexed_constant(a65b12821feea2,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea2,x_cityImprovementsUpkeep).
xc_indexed_constant(a65b12821feea2,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea3,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feea3,x_GoldPoints).
xc_indexed_constant(a65b12821feea3,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea3,x_cityCoinageProduction).
xc_indexed_constant(a65b12821feea3,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea4,'x_FreeCiv-Building').
xc_indexed_constant(a65b12821feea4,x_GoldPoints).
xc_indexed_constant(a65b12821feea4,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea4,x_objectTypeHasUpkeepGoldCost).
xc_indexed_constant(a65b12821feea4,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea5,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feea5,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea5,x_ProductionPoints).
xc_indexed_constant(a65b12821feea5,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea5,x_unitHasShieldUpkeep).
xc_indexed_constant(a65b12821feea6,x_FoodPoints).
xc_indexed_constant(a65b12821feea6,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feea6,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea6,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea6,x_unitHasFoodUpkeep).
xc_indexed_constant(a65b12821feea7,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feea7,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea7,x_TradePoints).
xc_indexed_constant(a65b12821feea7,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea7,x_tradeRouteIncome).
xc_indexed_constant(a65b12821feea8,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feea8,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821feea8,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea8,x_numTaxCollectors).
xc_indexed_constant(a65b12821feea8,x_quantityPrimitive).
xc_indexed_constant(a65b12821feea9,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feea9,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821feea9,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feea9,x_numScientists).
xc_indexed_constant(a65b12821feea9,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeaa,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feeaa,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821feeaa,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeaa,x_numEntertainers).
xc_indexed_constant(a65b12821feeaa,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeab,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feeab,x_FreecivCitizenCountFn).
xc_indexed_constant(a65b12821feeab,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeab,x_numWorkers).
xc_indexed_constant(a65b12821feeab,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeac,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feeac,x_HitPoints).
xc_indexed_constant(a65b12821feeac,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeac,x_currentHitpoints).
xc_indexed_constant(a65b12821feeac,x_quantityPrimitive).
xc_indexed_constant(a65b12821feead,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feead,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feead,x_Percent).
xc_indexed_constant(a65b12821feead,x_currentHealth).
xc_indexed_constant(a65b12821feead,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeae,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feeae,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeae,x_MovePoints).
xc_indexed_constant(a65b12821feeae,x_currentMovepoints).
xc_indexed_constant(a65b12821feeae,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeaf,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feeaf,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeaf,x_VeteranLevel).
xc_indexed_constant(a65b12821feeaf,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeaf,x_veteranStatus).
xc_indexed_constant(a65b12821feeb0,x_FoodPoints).
xc_indexed_constant(a65b12821feeb0,'x_FreeCiv-TerrainTile').
xc_indexed_constant(a65b12821feeb0,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb0,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb0,x_terrainBaseFoodProduction).
xc_indexed_constant(a65b12821feeb1,'x_FreeCiv-TerrainTile').
xc_indexed_constant(a65b12821feeb1,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb1,x_ProductionPoints).
xc_indexed_constant(a65b12821feeb1,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb1,x_terrainBaseShieldProduction).
xc_indexed_constant(a65b12821feeb2,'x_FreeCiv-TerrainTile').
xc_indexed_constant(a65b12821feeb2,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb2,x_TradePoints).
xc_indexed_constant(a65b12821feeb2,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb2,x_terrainBaseTradeProduction).
xc_indexed_constant(a65b12821feeb3,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feeb3,x_FreecivUnitCountFn).
xc_indexed_constant(a65b12821feeb3,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb3,x_numSupportedUnits).
xc_indexed_constant(a65b12821feeb3,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb4,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feeb4,x_FreecivUnitCountFn).
xc_indexed_constant(a65b12821feeb4,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb4,x_numPresentMilitaryUnits).
xc_indexed_constant(a65b12821feeb4,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb5,'x_FreeCiv-City').
xc_indexed_constant(a65b12821feeb5,x_FreecivUnitCountFn).
xc_indexed_constant(a65b12821feeb5,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb5,x_numDeployedMilitaryUnits).
xc_indexed_constant(a65b12821feeb5,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb6,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feeb6,x_FreecivStrengthFn).
xc_indexed_constant(a65b12821feeb6,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb6,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb6,x_unitHasDefendStrength).
xc_indexed_constant(a65b12821feeb7,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feeb7,x_FreecivStrengthFn).
xc_indexed_constant(a65b12821feeb7,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb7,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb7,x_unitHasAttackStrength).
xc_indexed_constant(a65b12821feeb8,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feeb8,x_FreecivTileDistance).
xc_indexed_constant(a65b12821feeb8,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb8,x_PerFn).
xc_indexed_constant(a65b12821feeb8,x_Turns).
xc_indexed_constant(a65b12821feeb8,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb8,x_unitHasMoveRate).
xc_indexed_constant(a65b12821feeb9,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feeb9,x_FreecivUnitCountFn).
xc_indexed_constant(a65b12821feeb9,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeb9,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeb9,x_unitHasTransportCapacity).
xc_indexed_constant(a65b12821feeba,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feeba,x_FreecivTileDistance).
xc_indexed_constant(a65b12821feeba,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feeba,x_quantityPrimitive).
xc_indexed_constant(a65b12821feeba,x_unitHasFuelCapacity).
xc_indexed_constant(a65b12821feebb,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feebb,x_HitPoints).
xc_indexed_constant(a65b12821feebb,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feebb,x_quantityPrimitive).
xc_indexed_constant(a65b12821feebb,x_unitHasHitpoints).
xc_indexed_constant(a65b12821feebc,'x_FreeCiv-Unit').
xc_indexed_constant(a65b12821feebc,x_HitPoints).
xc_indexed_constant(a65b12821feebc,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feebc,x_quantityPrimitive).
xc_indexed_constant(a65b12821feebc,x_unitHasFirepower).
xc_indexed_constant(a65b12821feebd,'x_FreeCiv-UnitType').
xc_indexed_constant(a65b12821feebd,x_FreecivStrengthFn).
xc_indexed_constant(a65b12821feebd,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feebd,x_quantityPrimitive).
xc_indexed_constant(a65b12821feebd,x_unitTypeHasDefendStrength).
xc_indexed_constant(a65b12821feebe,'x_FreeCiv-UnitType').
xc_indexed_constant(a65b12821feebe,x_FreecivStrengthFn).
xc_indexed_constant(a65b12821feebe,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feebe,x_quantityPrimitive).
xc_indexed_constant(a65b12821feebe,x_unitTypeHasAttackStrength).
xc_indexed_constant(a65b12821feebf,'x_FreeCiv-UnitType').
xc_indexed_constant(a65b12821feebf,x_FreecivTileDistance).
xc_indexed_constant(a65b12821feebf,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feebf,x_PerFn).
xc_indexed_constant(a65b12821feebf,x_Turns).
xc_indexed_constant(a65b12821feebf,x_quantityPrimitive).
xc_indexed_constant(a65b12821feebf,x_unitTypeHasMoveRate).
xc_indexed_constant(a65b12821feec0,'x_FreeCiv-UnitType').
xc_indexed_constant(a65b12821feec0,x_FreecivUnitCountFn).
xc_indexed_constant(a65b12821feec0,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feec0,x_quantityPrimitive).
xc_indexed_constant(a65b12821feec0,x_unitTypeHasTransportCapacity).
xc_indexed_constant(a65b12821feec1,'x_FreeCiv-UnitType').
xc_indexed_constant(a65b12821feec1,x_FreecivTileDistance).
xc_indexed_constant(a65b12821feec1,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feec1,x_quantityPrimitive).
xc_indexed_constant(a65b12821feec1,x_unitTypeHasFuelCapacity).
xc_indexed_constant(a65b12821feec2,'x_FreeCiv-UnitType').
xc_indexed_constant(a65b12821feec2,x_HitPoints).
xc_indexed_constant(a65b12821feec2,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feec2,x_quantityPrimitive).
xc_indexed_constant(a65b12821feec2,x_unitTypeHasHitpoints).
xc_indexed_constant(a65b12821feec3,'x_FreeCiv-UnitType').
xc_indexed_constant(a65b12821feec3,x_HitPoints).
xc_indexed_constant(a65b12821feec3,x_MeasurableQuantityFn).
xc_indexed_constant(a65b12821feec3,x_quantityPrimitive).
xc_indexed_constant(a65b12821feec3,x_unitTypeHasFirepower).
kb_index_footer(78,'6d7ddf72afd437788c0a62e04b6f0915f021d88ff4d14692b6aebc99f117d492','9a5560c491940dd809b05c597e564e32399b4edcc485b67efb539df4fa3e0e10').
