kb_index_header(index_header{count:20,digest:'979a5e078860d57fa532287d92fe657bf260d66af622c5b4a39a34e21c10961a',normalizedDigest:b48cef207b4e58a4e98d8817708dd2faab24323ac149976cd718a135bc4e0c00,normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',sourceHash:'8a1d6c3cddbb345b7ae76c4222afe067dc3fd998327c436664c4c9a26bc3620f'}).
kb_index_data(index{constants:[-(x_AnimalActivity,1),-('x_CapabilityPredicate-InstanceLevel',1),-(x_HoldingWithHand,1),-(x_HumanActivity,1),-(x_HumanCapabilityType,1),-(x_IntelligentAgentActivity,9),-(x_NonFunctionalObject,1),-(x_PartiallyMentalAnimalActivity,2),-(x_PartiallyMentalHumanActivity,1),-(x_ThingTypeByCapability,1),-(x_TypeCapableFn,2),-(x_TypeIncapableFn,2),-(x_arg2Genl,4),-(x_argGenl,4),-(x_comment,6),-(x_competentAtSkill,1),-(x_expertAtSkill,3),-(x_genls,3),-(x_hasSkill,1),-(x_isa,3),-(x_moreSkilledThan,1),-(x_not,1),-(x_noviceAtSkill,1),-(x_primaryFunction,1),-(x_skillCapableOf,6),-(x_unskilledAtSkill,1)],entries:[entry(a65b1270b3dae3,signature(x_isa,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',3,[x_NonFunctionalObject,x_ThingTypeByCapability,x_isa]),entry(a65b1270b3dae4,signature(x_isa,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',4,[x_HoldingWithHand,x_HumanCapabilityType,x_isa]),entry(a65b1270b3dae5,signature(x_arg2Genl,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',5,[x_IntelligentAgentActivity,x_TypeIncapableFn,x_arg2Genl,x_skillCapableOf]),entry(a65b1270b3dae6,signature(x_argGenl,3),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',6,[x_IntelligentAgentActivity,x_TypeIncapableFn,x_argGenl,x_skillCapableOf]),entry(a65b1270b3dae7,signature(x_arg2Genl,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',7,[x_IntelligentAgentActivity,x_TypeCapableFn,x_arg2Genl,x_skillCapableOf]),entry(a65b1270b3dae8,signature(x_argGenl,3),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',8,[x_IntelligentAgentActivity,x_TypeCapableFn,x_argGenl,x_skillCapableOf]),entry(a65b1270b3dae9,signature(x_argGenl,3),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',9,[x_IntelligentAgentActivity,x_argGenl,x_skillCapableOf]),entry(a65b1270b3daea,signature(x_arg2Genl,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',10,[x_IntelligentAgentActivity,x_arg2Genl,x_skillCapableOf]),entry(a65b1270b3daeb,signature(x_argGenl,3),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',11,[x_IntelligentAgentActivity,x_argGenl,x_expertAtSkill]),entry(a65b1270b3daec,signature(x_arg2Genl,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',12,[x_IntelligentAgentActivity,x_arg2Genl,x_expertAtSkill]),entry(a65b1270b3daed,signature(x_not,1),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',13,['x_CapabilityPredicate-InstanceLevel',x_isa,x_not,x_primaryFunction]),entry(a65b1270b3daee,signature(x_comment,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',14,[x_comment,x_noviceAtSkill]),entry(a65b1270b3daef,signature(x_comment,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',15,[x_comment,x_moreSkilledThan]),entry(a65b1270b3daf0,signature(x_comment,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',16,[x_comment,x_expertAtSkill]),entry(a65b1270b3daf1,signature(x_comment,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',17,[x_comment,x_competentAtSkill]),entry(a65b1270b3daf2,signature(x_comment,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',18,[x_comment,x_unskilledAtSkill]),entry(a65b1270b3daf3,signature(x_comment,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',19,[x_comment,x_hasSkill]),entry(a65b1270b3daf4,signature(x_genls,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',20,[x_AnimalActivity,x_PartiallyMentalAnimalActivity,x_genls]),entry(a65b1270b3daf5,signature(x_genls,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',21,[x_HumanActivity,x_PartiallyMentalHumanActivity,x_genls]),entry(a65b1270b3daf6,signature(x_genls,2),x_CapabilitiesVocabularyMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf',22,[x_IntelligentAgentActivity,x_PartiallyMentalAnimalActivity,x_genls])],predicates:[-(signature(x_arg2Genl,2),4),-(signature(x_argGenl,3),4),-(signature(x_comment,2),6),-(signature(x_genls,2),3),-(signature(x_isa,2),2),-(signature(x_not,1),1)],rankedConstants:[-(9,x_IntelligentAgentActivity),-(6,x_skillCapableOf),-(6,x_comment),-(4,x_argGenl),-(4,x_arg2Genl),-(3,x_isa),-(3,x_genls),-(3,x_expertAtSkill),-(2,x_TypeIncapableFn),-(2,x_TypeCapableFn),-(2,x_PartiallyMentalAnimalActivity),-(1,x_unskilledAtSkill),-(1,x_primaryFunction),-(1,x_noviceAtSkill),-(1,x_not),-(1,x_moreSkilledThan),-(1,x_hasSkill),-(1,x_competentAtSkill),-(1,x_ThingTypeByCapability),-(1,x_PartiallyMentalHumanActivity),-(1,x_NonFunctionalObject),-(1,x_HumanCapabilityType),-(1,x_HumanActivity),-(1,x_HoldingWithHand),-(1,'x_CapabilityPredicate-InstanceLevel'),-(1,x_AnimalActivity)],rankedPredicates:[-(6,signature(x_comment,2)),-(4,signature(x_argGenl,3)),-(4,signature(x_arg2Genl,2)),-(3,signature(x_genls,2)),-(2,signature(x_isa,2)),-(1,signature(x_not,1))],source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/CapabilitiesVocabularyMt.krf'}).
xc_indexed_constant(a65b1270b3dae3,x_NonFunctionalObject).
xc_indexed_constant(a65b1270b3dae3,x_ThingTypeByCapability).
xc_indexed_constant(a65b1270b3dae3,x_isa).
xc_indexed_constant(a65b1270b3dae4,x_HoldingWithHand).
xc_indexed_constant(a65b1270b3dae4,x_HumanCapabilityType).
xc_indexed_constant(a65b1270b3dae4,x_isa).
xc_indexed_constant(a65b1270b3dae5,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3dae5,x_TypeIncapableFn).
xc_indexed_constant(a65b1270b3dae5,x_arg2Genl).
xc_indexed_constant(a65b1270b3dae5,x_skillCapableOf).
xc_indexed_constant(a65b1270b3dae6,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3dae6,x_TypeIncapableFn).
xc_indexed_constant(a65b1270b3dae6,x_argGenl).
xc_indexed_constant(a65b1270b3dae6,x_skillCapableOf).
xc_indexed_constant(a65b1270b3dae7,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3dae7,x_TypeCapableFn).
xc_indexed_constant(a65b1270b3dae7,x_arg2Genl).
xc_indexed_constant(a65b1270b3dae7,x_skillCapableOf).
xc_indexed_constant(a65b1270b3dae8,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3dae8,x_TypeCapableFn).
xc_indexed_constant(a65b1270b3dae8,x_argGenl).
xc_indexed_constant(a65b1270b3dae8,x_skillCapableOf).
xc_indexed_constant(a65b1270b3dae9,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3dae9,x_argGenl).
xc_indexed_constant(a65b1270b3dae9,x_skillCapableOf).
xc_indexed_constant(a65b1270b3daea,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3daea,x_arg2Genl).
xc_indexed_constant(a65b1270b3daea,x_skillCapableOf).
xc_indexed_constant(a65b1270b3daeb,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3daeb,x_argGenl).
xc_indexed_constant(a65b1270b3daeb,x_expertAtSkill).
xc_indexed_constant(a65b1270b3daec,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3daec,x_arg2Genl).
xc_indexed_constant(a65b1270b3daec,x_expertAtSkill).
xc_indexed_constant(a65b1270b3daed,'x_CapabilityPredicate-InstanceLevel').
xc_indexed_constant(a65b1270b3daed,x_isa).
xc_indexed_constant(a65b1270b3daed,x_not).
xc_indexed_constant(a65b1270b3daed,x_primaryFunction).
xc_indexed_constant(a65b1270b3daee,x_comment).
xc_indexed_constant(a65b1270b3daee,x_noviceAtSkill).
xc_indexed_constant(a65b1270b3daef,x_comment).
xc_indexed_constant(a65b1270b3daef,x_moreSkilledThan).
xc_indexed_constant(a65b1270b3daf0,x_comment).
xc_indexed_constant(a65b1270b3daf0,x_expertAtSkill).
xc_indexed_constant(a65b1270b3daf1,x_comment).
xc_indexed_constant(a65b1270b3daf1,x_competentAtSkill).
xc_indexed_constant(a65b1270b3daf2,x_comment).
xc_indexed_constant(a65b1270b3daf2,x_unskilledAtSkill).
xc_indexed_constant(a65b1270b3daf3,x_comment).
xc_indexed_constant(a65b1270b3daf3,x_hasSkill).
xc_indexed_constant(a65b1270b3daf4,x_AnimalActivity).
xc_indexed_constant(a65b1270b3daf4,x_PartiallyMentalAnimalActivity).
xc_indexed_constant(a65b1270b3daf4,x_genls).
xc_indexed_constant(a65b1270b3daf5,x_HumanActivity).
xc_indexed_constant(a65b1270b3daf5,x_PartiallyMentalHumanActivity).
xc_indexed_constant(a65b1270b3daf5,x_genls).
xc_indexed_constant(a65b1270b3daf6,x_IntelligentAgentActivity).
xc_indexed_constant(a65b1270b3daf6,x_PartiallyMentalAnimalActivity).
xc_indexed_constant(a65b1270b3daf6,x_genls).
kb_index_footer(20,'979a5e078860d57fa532287d92fe657bf260d66af622c5b4a39a34e21c10961a','9f866ab6839ba4426fe10de71a58c2beedb4516867ef248a7f2f795cfe22d689').
