kb_index_header(index_header{count:88,digest:e9c6a462e46116e04259b415d2fdba8f1a722280641b76df51b9f67028edbeb9,normalizedDigest:'3ec256aca1f4d9c19db937f92921e445ef5c38f1895c37b6dcebe94d855257b3',normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',sourceHash:aae4fecfac978c7a3c4e6064412a1abf18f12fdde29a508591819633e9e1fefb}).
kb_index_data(index{constants:[-(x_CodeOfConduct,14),-(x_CommonUnaryModalOperator,4),-('x_CycLSentence-Assertible',20),-(x_DeonticAndRelatedModalPredicate,10),-(x_IntelligentAgent,28),-('x_ModalOpSet1-2Fn',4),-(x_ModalOpSetFn,4),-(x_NoteOnDeonticToDoOperators,3),-(x_SetOfTypeFn,8),-(x_SharedNote,1),-(x_UnaryModalOperator,4),-(x_arg1Isa,10),-(x_arg2Isa,5),-(x_arg2QuotedIsa,5),-(x_arg3QuotedIsa,5),-(x_argIsa,15),-(x_argQuotedIsa,10),-(x_comment,12),-(x_forbiddenToDo,8),-('x_forbiddenToDo-WRT',9),-(x_genlPreds,3),-(x_isa,18),-(x_negationPreds,3),-('x_ought-c',9),-('x_ought-c-Dual',9),-('x_ought-cc',11),-('x_ought-cc-Dual',11),-(x_oughtToDo,8),-('x_oughtToDo-WRT',9),-(x_permittedToDo,7),-('x_permittedToDo-WRT',10),-('x_permittedToDoSit-WRT',1),-(x_quotedIsa,1),-(x_sharedNotes,1)],entries:[entry(a65b127182fca9,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',3,[x_DeonticAndRelatedModalPredicate,x_isa,'x_ought-cc-Dual']),entry(a65b127182fcaa,signature(x_arg2QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',4,['x_CycLSentence-Assertible',x_arg2QuotedIsa,x_forbiddenToDo]),entry(a65b127182fcab,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',5,[x_comment,x_oughtToDo]),entry(a65b127182fcac,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',50,[x_CodeOfConduct,x_argIsa,'x_ought-cc']),entry(a65b127182fcad,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',51,[x_IntelligentAgent,x_ModalOpSetFn,x_SetOfTypeFn,x_UnaryModalOperator,x_isa,'x_ought-c']),entry(a65b127182fcae,signature(x_negationPreds,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',53,[x_forbiddenToDo,x_negationPreds,x_oughtToDo]),entry(a65b127182fcaf,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',54,[x_comment,x_permittedToDo]),entry(a65b127182fcb0,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',89,[x_IntelligentAgent,x_argIsa,'x_ought-cc-Dual']),entry(a65b127182fcb1,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',90,[x_NoteOnDeonticToDoOperators,x_comment]),entry(a65b127182fcb2,signature(x_arg2QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',131,['x_CycLSentence-Assertible',x_arg2QuotedIsa,'x_ought-c-Dual']),entry(a65b127182fcb3,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',132,[x_IntelligentAgent,x_arg1Isa,x_forbiddenToDo]),entry(a65b127182fcb4,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',133,['x_CycLSentence-Assertible',x_argQuotedIsa,x_oughtToDo]),entry(a65b127182fcb5,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',134,[x_comment,'x_forbiddenToDo-WRT']),entry(a65b127182fcb6,signature(x_genlPreds,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',163,[x_genlPreds,'x_ought-c','x_ought-c-Dual']),entry(a65b127182fcb7,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',164,[x_CodeOfConduct,x_CommonUnaryModalOperator,x_IntelligentAgent,'x_ModalOpSet1-2Fn',x_SetOfTypeFn,x_isa,'x_ought-cc-Dual']),entry(a65b127182fcb8,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',166,[x_CodeOfConduct,x_CommonUnaryModalOperator,x_IntelligentAgent,'x_ModalOpSet1-2Fn',x_SetOfTypeFn,x_isa,'x_ought-cc']),entry(a65b127182fcb9,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',168,[x_CodeOfConduct,x_argIsa,'x_forbiddenToDo-WRT']),entry(a65b127182fcba,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',169,[x_DeonticAndRelatedModalPredicate,x_isa,'x_ought-c']),entry(a65b127182fcbb,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',170,[x_IntelligentAgent,x_argIsa,'x_permittedToDo-WRT']),entry(a65b127182fcbc,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',171,[x_CommonUnaryModalOperator,x_IntelligentAgent,x_ModalOpSetFn,x_SetOfTypeFn,x_isa,'x_ought-c-Dual']),entry(a65b127182fcbd,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',173,['x_CycLSentence-Assertible',x_argQuotedIsa,'x_permittedToDo-WRT']),entry(a65b127182fcbe,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',174,['x_CycLSentence-Assertible',x_argQuotedIsa,x_permittedToDo]),entry(a65b127182fcbf,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',175,[x_IntelligentAgent,x_arg1Isa,'x_ought-c']),entry(a65b127182fcc0,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',176,[x_DeonticAndRelatedModalPredicate,x_isa,x_oughtToDo]),entry(a65b127182fcc1,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',177,[x_CodeOfConduct,x_argIsa,'x_oughtToDo-WRT']),entry(a65b127182fcc2,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',178,[x_CodeOfConduct,x_arg1Isa,'x_ought-cc']),entry(a65b127182fcc3,signature(x_arg2QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',179,['x_CycLSentence-Assertible',x_arg2QuotedIsa,x_permittedToDo]),entry(a65b127182fcc4,signature(x_arg2Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',180,[x_IntelligentAgent,x_arg2Isa,'x_ought-cc-Dual']),entry(a65b127182fcc5,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',181,[x_DeonticAndRelatedModalPredicate,x_isa,'x_ought-c-Dual']),entry(a65b127182fcc6,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',182,[x_IntelligentAgent,x_arg1Isa,x_permittedToDo]),entry(a65b127182fcc7,signature(x_arg2Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',183,[x_IntelligentAgent,x_arg2Isa,'x_forbiddenToDo-WRT']),entry(a65b127182fcc8,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',184,[x_IntelligentAgent,x_argIsa,'x_ought-cc']),entry(a65b127182fcc9,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',185,[x_IntelligentAgent,x_argIsa,'x_oughtToDo-WRT']),entry(a65b127182fcca,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',186,[x_CodeOfConduct,x_arg1Isa,'x_permittedToDo-WRT']),entry(a65b127182fccb,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',187,[x_DeonticAndRelatedModalPredicate,x_isa,'x_ought-cc']),entry(a65b127182fccc,signature(x_arg3QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',188,['x_CycLSentence-Assertible',x_arg3QuotedIsa,'x_ought-cc-Dual']),entry(a65b127182fccd,signature(x_arg2Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',189,[x_IntelligentAgent,x_arg2Isa,'x_ought-cc']),entry(a65b127182fcce,signature(x_arg2Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',190,[x_IntelligentAgent,x_arg2Isa,'x_oughtToDo-WRT']),entry(a65b127182fccf,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',191,[x_CodeOfConduct,x_arg1Isa,'x_oughtToDo-WRT']),entry(a65b127182fcd0,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',192,[x_CodeOfConduct,x_argIsa,'x_ought-cc-Dual']),entry(a65b127182fcd1,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',193,[x_DeonticAndRelatedModalPredicate,x_forbiddenToDo,x_isa]),entry(a65b127182fcd2,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',194,[x_comment,'x_oughtToDo-WRT']),entry(a65b127182fcd3,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',232,['x_CycLSentence-Assertible',x_argQuotedIsa,'x_ought-c-Dual']),entry(a65b127182fcd4,signature(x_arg3QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',233,['x_CycLSentence-Assertible',x_arg3QuotedIsa,'x_oughtToDo-WRT']),entry(a65b127182fcd5,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',234,[x_DeonticAndRelatedModalPredicate,x_isa,'x_permittedToDo-WRT']),entry(a65b127182fcd6,signature(x_arg3QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',235,['x_CycLSentence-Assertible',x_arg3QuotedIsa,'x_ought-cc']),entry(a65b127182fcd7,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',236,[x_IntelligentAgent,x_arg1Isa,'x_ought-c-Dual']),entry(a65b127182fcd8,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',237,[x_IntelligentAgent,x_argIsa,'x_ought-c-Dual']),entry(a65b127182fcd9,signature(x_genlPreds,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',238,[x_genlPreds,'x_oughtToDo-WRT','x_permittedToDo-WRT']),entry(a65b127182fcda,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',239,[x_DeonticAndRelatedModalPredicate,'x_forbiddenToDo-WRT',x_isa]),entry(a65b127182fcdb,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',240,[x_comment,'x_ought-c']),entry(a65b127182fcdc,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',253,[x_comment,'x_permittedToDo-WRT']),entry(a65b127182fcdd,signature(x_negationPreds,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',275,['x_forbiddenToDo-WRT',x_negationPreds,'x_permittedToDo-WRT']),entry(a65b127182fcde,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',276,[x_DeonticAndRelatedModalPredicate,x_isa,x_permittedToDo]),entry(a65b127182fcdf,signature(x_arg3QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',277,['x_CycLSentence-Assertible',x_arg3QuotedIsa,'x_forbiddenToDo-WRT']),entry(a65b127182fce0,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',278,[x_DeonticAndRelatedModalPredicate,x_isa,'x_oughtToDo-WRT']),entry(a65b127182fce1,signature(x_arg2QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',279,['x_CycLSentence-Assertible',x_arg2QuotedIsa,'x_ought-c']),entry(a65b127182fce2,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',280,['x_CycLSentence-Assertible',x_argQuotedIsa,'x_ought-cc-Dual']),entry(a65b127182fce3,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',281,[x_IntelligentAgent,x_argIsa,'x_forbiddenToDo-WRT']),entry(a65b127182fce4,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',282,[x_comment,'x_ought-cc']),entry(a65b127182fce5,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',297,[x_IntelligentAgent,x_ModalOpSetFn,x_SetOfTypeFn,x_UnaryModalOperator,x_isa,'x_ought-c-Dual']),entry(a65b127182fce6,signature(x_sharedNotes,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',299,[x_NoteOnDeonticToDoOperators,x_oughtToDo,x_sharedNotes]),entry(a65b127182fce7,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',300,[x_IntelligentAgent,x_arg1Isa,x_oughtToDo]),entry(a65b127182fce8,signature(x_genlPreds,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',301,[x_genlPreds,'x_ought-cc','x_ought-cc-Dual']),entry(a65b127182fce9,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',302,[x_CommonUnaryModalOperator,x_IntelligentAgent,x_ModalOpSetFn,x_SetOfTypeFn,x_isa,'x_ought-c']),entry(a65b127182fcea,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',304,[x_CodeOfConduct,x_arg1Isa,'x_forbiddenToDo-WRT']),entry(a65b127182fceb,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',305,[x_comment,'x_permittedToDoSit-WRT']),entry(a65b127182fcec,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',307,['x_CycLSentence-Assertible',x_argQuotedIsa,x_forbiddenToDo]),entry(a65b127182fced,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',308,['x_CycLSentence-Assertible',x_argQuotedIsa,'x_forbiddenToDo-WRT']),entry(a65b127182fcee,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',309,[x_IntelligentAgent,x_argIsa,x_forbiddenToDo]),entry(a65b127182fcef,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',310,['x_CycLSentence-Assertible',x_argQuotedIsa,'x_ought-c']),entry(a65b127182fcf0,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',311,['x_CycLSentence-Assertible',x_argQuotedIsa,'x_ought-cc']),entry(a65b127182fcf1,signature(x_quotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',312,[x_NoteOnDeonticToDoOperators,x_SharedNote,x_quotedIsa]),entry(a65b127182fcf2,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',313,[x_CodeOfConduct,x_IntelligentAgent,'x_ModalOpSet1-2Fn',x_SetOfTypeFn,x_UnaryModalOperator,x_isa,'x_ought-cc-Dual']),entry(a65b127182fcf3,signature(x_arg1Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',315,[x_CodeOfConduct,x_arg1Isa,'x_ought-cc-Dual']),entry(a65b127182fcf4,signature(x_arg2Isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',316,[x_IntelligentAgent,x_arg2Isa,'x_permittedToDo-WRT']),entry(a65b127182fcf5,signature(x_negationPreds,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',317,[x_forbiddenToDo,x_negationPreds,x_permittedToDo]),entry(a65b127182fcf6,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',318,[x_CodeOfConduct,x_argIsa,'x_permittedToDo-WRT']),entry(a65b127182fcf7,signature(x_isa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',319,[x_CodeOfConduct,x_IntelligentAgent,'x_ModalOpSet1-2Fn',x_SetOfTypeFn,x_UnaryModalOperator,x_isa,'x_ought-cc']),entry(a65b127182fcf8,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',321,[x_comment,'x_ought-cc-Dual']),entry(a65b127182fcf9,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',325,[x_IntelligentAgent,x_argIsa,x_oughtToDo]),entry(a65b127182fcfa,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',326,[x_IntelligentAgent,x_argIsa,x_permittedToDo]),entry(a65b127182fcfb,signature(x_arg3QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',327,['x_CycLSentence-Assertible',x_arg3QuotedIsa,'x_permittedToDo-WRT']),entry(a65b127182fcfc,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',328,[x_comment,'x_ought-c-Dual']),entry(a65b127182fcfd,signature(x_argIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',332,[x_IntelligentAgent,x_argIsa,'x_ought-c']),entry(a65b127182fcfe,signature(x_comment,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',333,[x_comment,x_forbiddenToDo]),entry(a65b127182fcff,signature(x_arg2QuotedIsa,2),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',362,['x_CycLSentence-Assertible',x_arg2QuotedIsa,x_oughtToDo]),entry(a65b127182fd00,signature(x_argQuotedIsa,3),'x_DeonticReasoningWithMultiFuture-LogicMt','c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf',363,['x_CycLSentence-Assertible',x_argQuotedIsa,'x_oughtToDo-WRT'])],predicates:[-(signature(x_arg1Isa,2),10),-(signature(x_arg2Isa,2),5),-(signature(x_arg2QuotedIsa,2),5),-(signature(x_arg3QuotedIsa,2),5),-(signature(x_argIsa,3),15),-(signature(x_argQuotedIsa,3),10),-(signature(x_comment,2),12),-(signature(x_genlPreds,2),3),-(signature(x_isa,2),18),-(signature(x_negationPreds,2),3),-(signature(x_quotedIsa,2),1),-(signature(x_sharedNotes,2),1)],rankedConstants:[-(28,x_IntelligentAgent),-(20,'x_CycLSentence-Assertible'),-(18,x_isa),-(15,x_argIsa),-(14,x_CodeOfConduct),-(12,x_comment),-(11,'x_ought-cc-Dual'),-(11,'x_ought-cc'),-(10,'x_permittedToDo-WRT'),-(10,x_argQuotedIsa),-(10,x_arg1Isa),-(10,x_DeonticAndRelatedModalPredicate),-(9,'x_oughtToDo-WRT'),-(9,'x_ought-c-Dual'),-(9,'x_ought-c'),-(9,'x_forbiddenToDo-WRT'),-(8,x_oughtToDo),-(8,x_forbiddenToDo),-(8,x_SetOfTypeFn),-(7,x_permittedToDo),-(5,x_arg3QuotedIsa),-(5,x_arg2QuotedIsa),-(5,x_arg2Isa),-(4,x_UnaryModalOperator),-(4,x_ModalOpSetFn),-(4,'x_ModalOpSet1-2Fn'),-(4,x_CommonUnaryModalOperator),-(3,x_negationPreds),-(3,x_genlPreds),-(3,x_NoteOnDeonticToDoOperators),-(1,x_sharedNotes),-(1,x_quotedIsa),-(1,'x_permittedToDoSit-WRT'),-(1,x_SharedNote)],rankedPredicates:[-(18,signature(x_isa,2)),-(15,signature(x_argIsa,3)),-(12,signature(x_comment,2)),-(10,signature(x_argQuotedIsa,3)),-(10,signature(x_arg1Isa,2)),-(5,signature(x_arg3QuotedIsa,2)),-(5,signature(x_arg2QuotedIsa,2)),-(5,signature(x_arg2Isa,2)),-(3,signature(x_negationPreds,2)),-(3,signature(x_genlPreds,2)),-(1,signature(x_sharedNotes,2)),-(1,signature(x_quotedIsa,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/DeonticReasoningWithMultiFuture-LogicMt.krf'}).
xc_indexed_constant(a65b127182fca9,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fca9,x_isa).
xc_indexed_constant(a65b127182fca9,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fcaa,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcaa,x_arg2QuotedIsa).
xc_indexed_constant(a65b127182fcaa,x_forbiddenToDo).
xc_indexed_constant(a65b127182fcab,x_comment).
xc_indexed_constant(a65b127182fcab,x_oughtToDo).
xc_indexed_constant(a65b127182fcac,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcac,x_argIsa).
xc_indexed_constant(a65b127182fcac,'x_ought-cc').
xc_indexed_constant(a65b127182fcad,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcad,x_ModalOpSetFn).
xc_indexed_constant(a65b127182fcad,x_SetOfTypeFn).
xc_indexed_constant(a65b127182fcad,x_UnaryModalOperator).
xc_indexed_constant(a65b127182fcad,x_isa).
xc_indexed_constant(a65b127182fcad,'x_ought-c').
xc_indexed_constant(a65b127182fcae,x_forbiddenToDo).
xc_indexed_constant(a65b127182fcae,x_negationPreds).
xc_indexed_constant(a65b127182fcae,x_oughtToDo).
xc_indexed_constant(a65b127182fcaf,x_comment).
xc_indexed_constant(a65b127182fcaf,x_permittedToDo).
xc_indexed_constant(a65b127182fcb0,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcb0,x_argIsa).
xc_indexed_constant(a65b127182fcb0,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fcb1,x_NoteOnDeonticToDoOperators).
xc_indexed_constant(a65b127182fcb1,x_comment).
xc_indexed_constant(a65b127182fcb2,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcb2,x_arg2QuotedIsa).
xc_indexed_constant(a65b127182fcb2,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fcb3,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcb3,x_arg1Isa).
xc_indexed_constant(a65b127182fcb3,x_forbiddenToDo).
xc_indexed_constant(a65b127182fcb4,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcb4,x_argQuotedIsa).
xc_indexed_constant(a65b127182fcb4,x_oughtToDo).
xc_indexed_constant(a65b127182fcb5,x_comment).
xc_indexed_constant(a65b127182fcb5,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fcb6,x_genlPreds).
xc_indexed_constant(a65b127182fcb6,'x_ought-c').
xc_indexed_constant(a65b127182fcb6,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fcb7,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcb7,x_CommonUnaryModalOperator).
xc_indexed_constant(a65b127182fcb7,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcb7,'x_ModalOpSet1-2Fn').
xc_indexed_constant(a65b127182fcb7,x_SetOfTypeFn).
xc_indexed_constant(a65b127182fcb7,x_isa).
xc_indexed_constant(a65b127182fcb7,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fcb8,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcb8,x_CommonUnaryModalOperator).
xc_indexed_constant(a65b127182fcb8,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcb8,'x_ModalOpSet1-2Fn').
xc_indexed_constant(a65b127182fcb8,x_SetOfTypeFn).
xc_indexed_constant(a65b127182fcb8,x_isa).
xc_indexed_constant(a65b127182fcb8,'x_ought-cc').
xc_indexed_constant(a65b127182fcb9,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcb9,x_argIsa).
xc_indexed_constant(a65b127182fcb9,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fcba,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fcba,x_isa).
xc_indexed_constant(a65b127182fcba,'x_ought-c').
xc_indexed_constant(a65b127182fcbb,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcbb,x_argIsa).
xc_indexed_constant(a65b127182fcbb,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcbc,x_CommonUnaryModalOperator).
xc_indexed_constant(a65b127182fcbc,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcbc,x_ModalOpSetFn).
xc_indexed_constant(a65b127182fcbc,x_SetOfTypeFn).
xc_indexed_constant(a65b127182fcbc,x_isa).
xc_indexed_constant(a65b127182fcbc,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fcbd,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcbd,x_argQuotedIsa).
xc_indexed_constant(a65b127182fcbd,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcbe,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcbe,x_argQuotedIsa).
xc_indexed_constant(a65b127182fcbe,x_permittedToDo).
xc_indexed_constant(a65b127182fcbf,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcbf,x_arg1Isa).
xc_indexed_constant(a65b127182fcbf,'x_ought-c').
xc_indexed_constant(a65b127182fcc0,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fcc0,x_isa).
xc_indexed_constant(a65b127182fcc0,x_oughtToDo).
xc_indexed_constant(a65b127182fcc1,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcc1,x_argIsa).
xc_indexed_constant(a65b127182fcc1,'x_oughtToDo-WRT').
xc_indexed_constant(a65b127182fcc2,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcc2,x_arg1Isa).
xc_indexed_constant(a65b127182fcc2,'x_ought-cc').
xc_indexed_constant(a65b127182fcc3,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcc3,x_arg2QuotedIsa).
xc_indexed_constant(a65b127182fcc3,x_permittedToDo).
xc_indexed_constant(a65b127182fcc4,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcc4,x_arg2Isa).
xc_indexed_constant(a65b127182fcc4,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fcc5,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fcc5,x_isa).
xc_indexed_constant(a65b127182fcc5,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fcc6,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcc6,x_arg1Isa).
xc_indexed_constant(a65b127182fcc6,x_permittedToDo).
xc_indexed_constant(a65b127182fcc7,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcc7,x_arg2Isa).
xc_indexed_constant(a65b127182fcc7,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fcc8,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcc8,x_argIsa).
xc_indexed_constant(a65b127182fcc8,'x_ought-cc').
xc_indexed_constant(a65b127182fcc9,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcc9,x_argIsa).
xc_indexed_constant(a65b127182fcc9,'x_oughtToDo-WRT').
xc_indexed_constant(a65b127182fcca,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcca,x_arg1Isa).
xc_indexed_constant(a65b127182fcca,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fccb,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fccb,x_isa).
xc_indexed_constant(a65b127182fccb,'x_ought-cc').
xc_indexed_constant(a65b127182fccc,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fccc,x_arg3QuotedIsa).
xc_indexed_constant(a65b127182fccc,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fccd,x_IntelligentAgent).
xc_indexed_constant(a65b127182fccd,x_arg2Isa).
xc_indexed_constant(a65b127182fccd,'x_ought-cc').
xc_indexed_constant(a65b127182fcce,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcce,x_arg2Isa).
xc_indexed_constant(a65b127182fcce,'x_oughtToDo-WRT').
xc_indexed_constant(a65b127182fccf,x_CodeOfConduct).
xc_indexed_constant(a65b127182fccf,x_arg1Isa).
xc_indexed_constant(a65b127182fccf,'x_oughtToDo-WRT').
xc_indexed_constant(a65b127182fcd0,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcd0,x_argIsa).
xc_indexed_constant(a65b127182fcd0,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fcd1,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fcd1,x_forbiddenToDo).
xc_indexed_constant(a65b127182fcd1,x_isa).
xc_indexed_constant(a65b127182fcd2,x_comment).
xc_indexed_constant(a65b127182fcd2,'x_oughtToDo-WRT').
xc_indexed_constant(a65b127182fcd3,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcd3,x_argQuotedIsa).
xc_indexed_constant(a65b127182fcd3,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fcd4,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcd4,x_arg3QuotedIsa).
xc_indexed_constant(a65b127182fcd4,'x_oughtToDo-WRT').
xc_indexed_constant(a65b127182fcd5,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fcd5,x_isa).
xc_indexed_constant(a65b127182fcd5,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcd6,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcd6,x_arg3QuotedIsa).
xc_indexed_constant(a65b127182fcd6,'x_ought-cc').
xc_indexed_constant(a65b127182fcd7,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcd7,x_arg1Isa).
xc_indexed_constant(a65b127182fcd7,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fcd8,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcd8,x_argIsa).
xc_indexed_constant(a65b127182fcd8,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fcd9,x_genlPreds).
xc_indexed_constant(a65b127182fcd9,'x_oughtToDo-WRT').
xc_indexed_constant(a65b127182fcd9,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcda,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fcda,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fcda,x_isa).
xc_indexed_constant(a65b127182fcdb,x_comment).
xc_indexed_constant(a65b127182fcdb,'x_ought-c').
xc_indexed_constant(a65b127182fcdc,x_comment).
xc_indexed_constant(a65b127182fcdc,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcdd,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fcdd,x_negationPreds).
xc_indexed_constant(a65b127182fcdd,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcde,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fcde,x_isa).
xc_indexed_constant(a65b127182fcde,x_permittedToDo).
xc_indexed_constant(a65b127182fcdf,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcdf,x_arg3QuotedIsa).
xc_indexed_constant(a65b127182fcdf,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fce0,x_DeonticAndRelatedModalPredicate).
xc_indexed_constant(a65b127182fce0,x_isa).
xc_indexed_constant(a65b127182fce0,'x_oughtToDo-WRT').
xc_indexed_constant(a65b127182fce1,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fce1,x_arg2QuotedIsa).
xc_indexed_constant(a65b127182fce1,'x_ought-c').
xc_indexed_constant(a65b127182fce2,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fce2,x_argQuotedIsa).
xc_indexed_constant(a65b127182fce2,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fce3,x_IntelligentAgent).
xc_indexed_constant(a65b127182fce3,x_argIsa).
xc_indexed_constant(a65b127182fce3,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fce4,x_comment).
xc_indexed_constant(a65b127182fce4,'x_ought-cc').
xc_indexed_constant(a65b127182fce5,x_IntelligentAgent).
xc_indexed_constant(a65b127182fce5,x_ModalOpSetFn).
xc_indexed_constant(a65b127182fce5,x_SetOfTypeFn).
xc_indexed_constant(a65b127182fce5,x_UnaryModalOperator).
xc_indexed_constant(a65b127182fce5,x_isa).
xc_indexed_constant(a65b127182fce5,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fce6,x_NoteOnDeonticToDoOperators).
xc_indexed_constant(a65b127182fce6,x_oughtToDo).
xc_indexed_constant(a65b127182fce6,x_sharedNotes).
xc_indexed_constant(a65b127182fce7,x_IntelligentAgent).
xc_indexed_constant(a65b127182fce7,x_arg1Isa).
xc_indexed_constant(a65b127182fce7,x_oughtToDo).
xc_indexed_constant(a65b127182fce8,x_genlPreds).
xc_indexed_constant(a65b127182fce8,'x_ought-cc').
xc_indexed_constant(a65b127182fce8,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fce9,x_CommonUnaryModalOperator).
xc_indexed_constant(a65b127182fce9,x_IntelligentAgent).
xc_indexed_constant(a65b127182fce9,x_ModalOpSetFn).
xc_indexed_constant(a65b127182fce9,x_SetOfTypeFn).
xc_indexed_constant(a65b127182fce9,x_isa).
xc_indexed_constant(a65b127182fce9,'x_ought-c').
xc_indexed_constant(a65b127182fcea,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcea,x_arg1Isa).
xc_indexed_constant(a65b127182fcea,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fceb,x_comment).
xc_indexed_constant(a65b127182fceb,'x_permittedToDoSit-WRT').
xc_indexed_constant(a65b127182fcec,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcec,x_argQuotedIsa).
xc_indexed_constant(a65b127182fcec,x_forbiddenToDo).
xc_indexed_constant(a65b127182fced,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fced,x_argQuotedIsa).
xc_indexed_constant(a65b127182fced,'x_forbiddenToDo-WRT').
xc_indexed_constant(a65b127182fcee,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcee,x_argIsa).
xc_indexed_constant(a65b127182fcee,x_forbiddenToDo).
xc_indexed_constant(a65b127182fcef,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcef,x_argQuotedIsa).
xc_indexed_constant(a65b127182fcef,'x_ought-c').
xc_indexed_constant(a65b127182fcf0,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcf0,x_argQuotedIsa).
xc_indexed_constant(a65b127182fcf0,'x_ought-cc').
xc_indexed_constant(a65b127182fcf1,x_NoteOnDeonticToDoOperators).
xc_indexed_constant(a65b127182fcf1,x_SharedNote).
xc_indexed_constant(a65b127182fcf1,x_quotedIsa).
xc_indexed_constant(a65b127182fcf2,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcf2,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcf2,'x_ModalOpSet1-2Fn').
xc_indexed_constant(a65b127182fcf2,x_SetOfTypeFn).
xc_indexed_constant(a65b127182fcf2,x_UnaryModalOperator).
xc_indexed_constant(a65b127182fcf2,x_isa).
xc_indexed_constant(a65b127182fcf2,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fcf3,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcf3,x_arg1Isa).
xc_indexed_constant(a65b127182fcf3,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fcf4,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcf4,x_arg2Isa).
xc_indexed_constant(a65b127182fcf4,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcf5,x_forbiddenToDo).
xc_indexed_constant(a65b127182fcf5,x_negationPreds).
xc_indexed_constant(a65b127182fcf5,x_permittedToDo).
xc_indexed_constant(a65b127182fcf6,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcf6,x_argIsa).
xc_indexed_constant(a65b127182fcf6,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcf7,x_CodeOfConduct).
xc_indexed_constant(a65b127182fcf7,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcf7,'x_ModalOpSet1-2Fn').
xc_indexed_constant(a65b127182fcf7,x_SetOfTypeFn).
xc_indexed_constant(a65b127182fcf7,x_UnaryModalOperator).
xc_indexed_constant(a65b127182fcf7,x_isa).
xc_indexed_constant(a65b127182fcf7,'x_ought-cc').
xc_indexed_constant(a65b127182fcf8,x_comment).
xc_indexed_constant(a65b127182fcf8,'x_ought-cc-Dual').
xc_indexed_constant(a65b127182fcf9,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcf9,x_argIsa).
xc_indexed_constant(a65b127182fcf9,x_oughtToDo).
xc_indexed_constant(a65b127182fcfa,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcfa,x_argIsa).
xc_indexed_constant(a65b127182fcfa,x_permittedToDo).
xc_indexed_constant(a65b127182fcfb,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcfb,x_arg3QuotedIsa).
xc_indexed_constant(a65b127182fcfb,'x_permittedToDo-WRT').
xc_indexed_constant(a65b127182fcfc,x_comment).
xc_indexed_constant(a65b127182fcfc,'x_ought-c-Dual').
xc_indexed_constant(a65b127182fcfd,x_IntelligentAgent).
xc_indexed_constant(a65b127182fcfd,x_argIsa).
xc_indexed_constant(a65b127182fcfd,'x_ought-c').
xc_indexed_constant(a65b127182fcfe,x_comment).
xc_indexed_constant(a65b127182fcfe,x_forbiddenToDo).
xc_indexed_constant(a65b127182fcff,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fcff,x_arg2QuotedIsa).
xc_indexed_constant(a65b127182fcff,x_oughtToDo).
xc_indexed_constant(a65b127182fd00,'x_CycLSentence-Assertible').
xc_indexed_constant(a65b127182fd00,x_argQuotedIsa).
xc_indexed_constant(a65b127182fd00,'x_oughtToDo-WRT').
kb_index_footer(88,e9c6a462e46116e04259b415d2fdba8f1a722280641b76df51b9f67028edbeb9,d861db521c3d3a131ec287e06a6b5521e812a3695320a5ec19ac9619f7b2f403).
