kb_index_header(index_header{count:30,digest:e1e41daca69210f1f837b47019b75a5d874dc89b07e75b9de705c5722bcd4312,normalizedDigest:d76c06057d37a2f778b7b997c95392df6f9e2c5d20c33e98ebb1e4f629f0a1b0,normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',sourceHash:'6d72f096faf53122761a87749ba59a0ff035a4ff152afb408485f0a0ce505f56'}).
kb_index_data(index{constants:[-(x_Collection,7),-(x_CycLExpression,2),-(x_CycLReifiableNonAtomicTerm,4),-(x_CycLSubLSymbol,1),-(x_CycLTerm,4),-(x_EscapeQuote,2),-(x_FixedArityRelation,1),-(x_FixedAritySkolemFunction,4),-('x_Function-Denotational',2),-(x_LogicalTruthImplementationMt,1),-(x_Microtheory,1),-(x_Predicate,2),-(x_QuasiQuote,1),-(x_Quote,2),-('x_QuoteFn-Reifiable',1),-(x_ReifiableFunction,4),-(x_SkolemFunction,4),-(x_SubLSymbol,2),-(x_UnreifiableFunction,5),-(x_VariableArityRelation,1),-(x_VariableAritySkolemFunction,4),-(x_arg2QuotedIsa,1),-(x_argQuotedIsa,5),-(x_defnIff,2),-(x_disjointWith,2),-(x_genls,9),-(x_isa,12),-(x_resultQuotedIsa,1),-(x_termOfUnit,3)],entries:[entry(a65b1274abec63,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',3,[x_LogicalTruthImplementationMt,x_Microtheory,x_isa]),entry(a65b1274abec64,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',4,[x_EscapeQuote,x_UnreifiableFunction,x_isa]),entry(a65b1274abec65,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',5,[x_Quote,x_UnreifiableFunction,x_isa]),entry(a65b1274abec66,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',6,[x_Collection,x_UnreifiableFunction,x_isa]),entry(a65b1274abec67,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',7,[x_Collection,x_VariableAritySkolemFunction,x_isa]),entry(a65b1274abec68,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',8,[x_Collection,x_SkolemFunction,x_isa]),entry(a65b1274abec69,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',9,[x_Predicate,x_isa,x_termOfUnit]),entry(a65b1274abec6a,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',10,[x_Predicate,x_defnIff,x_isa]),entry(a65b1274abec6b,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',11,[x_Collection,x_CycLReifiableNonAtomicTerm,x_isa]),entry(a65b1274abec6c,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',12,[x_Collection,x_FixedAritySkolemFunction,x_isa]),entry(a65b1274abec6d,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',13,[x_Collection,x_ReifiableFunction,x_isa]),entry(a65b1274abec6e,signature(x_isa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',14,[x_Collection,x_SubLSymbol,x_isa]),entry(a65b1274abec6f,signature(x_resultQuotedIsa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',15,[x_CycLTerm,'x_QuoteFn-Reifiable',x_resultQuotedIsa]),entry(a65b1274abec70,signature(x_argQuotedIsa,3),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',16,[x_CycLTerm,x_Quote,x_argQuotedIsa]),entry(a65b1274abec71,signature(x_argQuotedIsa,3),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',17,[x_CycLTerm,x_EscapeQuote,x_argQuotedIsa]),entry(a65b1274abec72,signature(x_argQuotedIsa,3),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',18,[x_CycLTerm,x_QuasiQuote,x_argQuotedIsa]),entry(a65b1274abec73,signature(x_argQuotedIsa,3),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',19,[x_CycLReifiableNonAtomicTerm,x_argQuotedIsa,x_termOfUnit]),entry(a65b1274abec74,signature(x_arg2QuotedIsa,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',20,[x_CycLReifiableNonAtomicTerm,x_arg2QuotedIsa,x_termOfUnit]),entry(a65b1274abec75,signature(x_argQuotedIsa,3),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',21,[x_CycLSubLSymbol,x_argQuotedIsa,x_defnIff]),entry(a65b1274abec76,signature(x_disjointWith,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',22,[x_FixedAritySkolemFunction,x_VariableAritySkolemFunction,x_disjointWith]),entry(a65b1274abec77,signature(x_disjointWith,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',23,[x_ReifiableFunction,x_UnreifiableFunction,x_disjointWith]),entry(a65b1274abec78,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',24,['x_Function-Denotational',x_ReifiableFunction,x_genls]),entry(a65b1274abec79,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',25,[x_FixedArityRelation,x_FixedAritySkolemFunction,x_genls]),entry(a65b1274abec7a,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',26,[x_ReifiableFunction,x_SkolemFunction,x_genls]),entry(a65b1274abec7b,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',27,[x_FixedAritySkolemFunction,x_SkolemFunction,x_genls]),entry(a65b1274abec7c,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',28,[x_VariableArityRelation,x_VariableAritySkolemFunction,x_genls]),entry(a65b1274abec7d,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',29,[x_SkolemFunction,x_VariableAritySkolemFunction,x_genls]),entry(a65b1274abec7e,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',30,['x_Function-Denotational',x_UnreifiableFunction,x_genls]),entry(a65b1274abec7f,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',31,[x_CycLExpression,x_CycLReifiableNonAtomicTerm,x_genls]),entry(a65b1274abec80,signature(x_genls,2),x_LogicalTruthImplementationMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf',32,[x_CycLExpression,x_SubLSymbol,x_genls])],predicates:[-(signature(x_arg2QuotedIsa,2),1),-(signature(x_argQuotedIsa,3),5),-(signature(x_disjointWith,2),2),-(signature(x_genls,2),9),-(signature(x_isa,2),12),-(signature(x_resultQuotedIsa,2),1)],rankedConstants:[-(12,x_isa),-(9,x_genls),-(7,x_Collection),-(5,x_argQuotedIsa),-(5,x_UnreifiableFunction),-(4,x_VariableAritySkolemFunction),-(4,x_SkolemFunction),-(4,x_ReifiableFunction),-(4,x_FixedAritySkolemFunction),-(4,x_CycLTerm),-(4,x_CycLReifiableNonAtomicTerm),-(3,x_termOfUnit),-(2,x_disjointWith),-(2,x_defnIff),-(2,x_SubLSymbol),-(2,x_Quote),-(2,x_Predicate),-(2,'x_Function-Denotational'),-(2,x_EscapeQuote),-(2,x_CycLExpression),-(1,x_resultQuotedIsa),-(1,x_arg2QuotedIsa),-(1,x_VariableArityRelation),-(1,'x_QuoteFn-Reifiable'),-(1,x_QuasiQuote),-(1,x_Microtheory),-(1,x_LogicalTruthImplementationMt),-(1,x_FixedArityRelation),-(1,x_CycLSubLSymbol)],rankedPredicates:[-(12,signature(x_isa,2)),-(9,signature(x_genls,2)),-(5,signature(x_argQuotedIsa,3)),-(2,signature(x_disjointWith,2)),-(1,signature(x_resultQuotedIsa,2)),-(1,signature(x_arg2QuotedIsa,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/LogicalTruthImplementationMt.krf'}).
xc_indexed_constant(a65b1274abec63,x_LogicalTruthImplementationMt).
xc_indexed_constant(a65b1274abec63,x_Microtheory).
xc_indexed_constant(a65b1274abec63,x_isa).
xc_indexed_constant(a65b1274abec64,x_EscapeQuote).
xc_indexed_constant(a65b1274abec64,x_UnreifiableFunction).
xc_indexed_constant(a65b1274abec64,x_isa).
xc_indexed_constant(a65b1274abec65,x_Quote).
xc_indexed_constant(a65b1274abec65,x_UnreifiableFunction).
xc_indexed_constant(a65b1274abec65,x_isa).
xc_indexed_constant(a65b1274abec66,x_Collection).
xc_indexed_constant(a65b1274abec66,x_UnreifiableFunction).
xc_indexed_constant(a65b1274abec66,x_isa).
xc_indexed_constant(a65b1274abec67,x_Collection).
xc_indexed_constant(a65b1274abec67,x_VariableAritySkolemFunction).
xc_indexed_constant(a65b1274abec67,x_isa).
xc_indexed_constant(a65b1274abec68,x_Collection).
xc_indexed_constant(a65b1274abec68,x_SkolemFunction).
xc_indexed_constant(a65b1274abec68,x_isa).
xc_indexed_constant(a65b1274abec69,x_Predicate).
xc_indexed_constant(a65b1274abec69,x_isa).
xc_indexed_constant(a65b1274abec69,x_termOfUnit).
xc_indexed_constant(a65b1274abec6a,x_Predicate).
xc_indexed_constant(a65b1274abec6a,x_defnIff).
xc_indexed_constant(a65b1274abec6a,x_isa).
xc_indexed_constant(a65b1274abec6b,x_Collection).
xc_indexed_constant(a65b1274abec6b,x_CycLReifiableNonAtomicTerm).
xc_indexed_constant(a65b1274abec6b,x_isa).
xc_indexed_constant(a65b1274abec6c,x_Collection).
xc_indexed_constant(a65b1274abec6c,x_FixedAritySkolemFunction).
xc_indexed_constant(a65b1274abec6c,x_isa).
xc_indexed_constant(a65b1274abec6d,x_Collection).
xc_indexed_constant(a65b1274abec6d,x_ReifiableFunction).
xc_indexed_constant(a65b1274abec6d,x_isa).
xc_indexed_constant(a65b1274abec6e,x_Collection).
xc_indexed_constant(a65b1274abec6e,x_SubLSymbol).
xc_indexed_constant(a65b1274abec6e,x_isa).
xc_indexed_constant(a65b1274abec6f,x_CycLTerm).
xc_indexed_constant(a65b1274abec6f,'x_QuoteFn-Reifiable').
xc_indexed_constant(a65b1274abec6f,x_resultQuotedIsa).
xc_indexed_constant(a65b1274abec70,x_CycLTerm).
xc_indexed_constant(a65b1274abec70,x_Quote).
xc_indexed_constant(a65b1274abec70,x_argQuotedIsa).
xc_indexed_constant(a65b1274abec71,x_CycLTerm).
xc_indexed_constant(a65b1274abec71,x_EscapeQuote).
xc_indexed_constant(a65b1274abec71,x_argQuotedIsa).
xc_indexed_constant(a65b1274abec72,x_CycLTerm).
xc_indexed_constant(a65b1274abec72,x_QuasiQuote).
xc_indexed_constant(a65b1274abec72,x_argQuotedIsa).
xc_indexed_constant(a65b1274abec73,x_CycLReifiableNonAtomicTerm).
xc_indexed_constant(a65b1274abec73,x_argQuotedIsa).
xc_indexed_constant(a65b1274abec73,x_termOfUnit).
xc_indexed_constant(a65b1274abec74,x_CycLReifiableNonAtomicTerm).
xc_indexed_constant(a65b1274abec74,x_arg2QuotedIsa).
xc_indexed_constant(a65b1274abec74,x_termOfUnit).
xc_indexed_constant(a65b1274abec75,x_CycLSubLSymbol).
xc_indexed_constant(a65b1274abec75,x_argQuotedIsa).
xc_indexed_constant(a65b1274abec75,x_defnIff).
xc_indexed_constant(a65b1274abec76,x_FixedAritySkolemFunction).
xc_indexed_constant(a65b1274abec76,x_VariableAritySkolemFunction).
xc_indexed_constant(a65b1274abec76,x_disjointWith).
xc_indexed_constant(a65b1274abec77,x_ReifiableFunction).
xc_indexed_constant(a65b1274abec77,x_UnreifiableFunction).
xc_indexed_constant(a65b1274abec77,x_disjointWith).
xc_indexed_constant(a65b1274abec78,'x_Function-Denotational').
xc_indexed_constant(a65b1274abec78,x_ReifiableFunction).
xc_indexed_constant(a65b1274abec78,x_genls).
xc_indexed_constant(a65b1274abec79,x_FixedArityRelation).
xc_indexed_constant(a65b1274abec79,x_FixedAritySkolemFunction).
xc_indexed_constant(a65b1274abec79,x_genls).
xc_indexed_constant(a65b1274abec7a,x_ReifiableFunction).
xc_indexed_constant(a65b1274abec7a,x_SkolemFunction).
xc_indexed_constant(a65b1274abec7a,x_genls).
xc_indexed_constant(a65b1274abec7b,x_FixedAritySkolemFunction).
xc_indexed_constant(a65b1274abec7b,x_SkolemFunction).
xc_indexed_constant(a65b1274abec7b,x_genls).
xc_indexed_constant(a65b1274abec7c,x_VariableArityRelation).
xc_indexed_constant(a65b1274abec7c,x_VariableAritySkolemFunction).
xc_indexed_constant(a65b1274abec7c,x_genls).
xc_indexed_constant(a65b1274abec7d,x_SkolemFunction).
xc_indexed_constant(a65b1274abec7d,x_VariableAritySkolemFunction).
xc_indexed_constant(a65b1274abec7d,x_genls).
xc_indexed_constant(a65b1274abec7e,'x_Function-Denotational').
xc_indexed_constant(a65b1274abec7e,x_UnreifiableFunction).
xc_indexed_constant(a65b1274abec7e,x_genls).
xc_indexed_constant(a65b1274abec7f,x_CycLExpression).
xc_indexed_constant(a65b1274abec7f,x_CycLReifiableNonAtomicTerm).
xc_indexed_constant(a65b1274abec7f,x_genls).
xc_indexed_constant(a65b1274abec80,x_CycLExpression).
xc_indexed_constant(a65b1274abec80,x_SubLSymbol).
xc_indexed_constant(a65b1274abec80,x_genls).
kb_index_footer(30,e1e41daca69210f1f837b47019b75a5d874dc89b07e75b9de705c5722bcd4312,'4a303f4a2349965bb8c2782bde17ca15c577d28f3a8b4060a60d15e0aa86c8ad').
