kb_index_header(index_header{count:35,digest:'6b1a500326413fa8e8f297dcebcccea9517b3acd1ffd8105aef73157a029218f',normalizedDigest:'90196e952e59bc60efe10e9e210e1cb428a587e479e2927253b3397fe631f7c6',normalizedFile:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf.pl',schema:logos_index_v1,source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',sourceHash:d299cb12949954c71b77a25bd19d6ed988d31cbe470241594f48ca8841b047be}).
kb_index_data(index{constants:[-('x_AcidicSolution-Liquid',2),-(x_AdministeringADrug,1),-('x_Alcohol-Compound',3),-(x_AnthraxInfection,7),-(x_Attempting,6),-(x_AttemptingFn,6),-(x_Bradycardia,1),-(x_CollectionIntersection2Fn,3),-('x_DrugPrescription-Specification',2),-(x_DrugTestWithBlood,1),-(x_DrugTherapy,1),-(x_DrugTreatment,1),-(x_ExclusiveTreatmentType,1),-(x_ExtendedReleaseDrugDeliveryProduct,1),-(x_FirstOrderCollection,2),-(x_Headache,1),-(x_HomoSapiens,6),-(x_Hypotension,1),-(x_ImmediateReleaseDrugDeliveryProduct,1),-(x_ImmersionOfInFn,2),-(x_KEClarifyingCollectionType,1),-(x_KillingByOrganism,3),-(x_KillingThroughEventTypeFn,5),-('x_Licensed-ProductType',2),-(x_LicensedHumanAnthraxVaccine,4),-('x_MedicalPrescription-Specification',2),-(x_MedicalTreatmentEvent,1),-(x_Nausea,1),-(x_Nesiritide,4),-(x_Person,3),-(x_Poisoning,2),-(x_PoisoningViaSubstanceFn,6),-(x_RadioactiveStuff,3),-(x_SetTheFormat,2),-(x_SideEffectsOfUsingDrugTypeFn,4),-(x_SomethingExisting,2),-(x_SpatiallyDisjointObjectType,1),-(x_SpecsFn,2),-(x_SubcollectionOfWithRelationFromTypeFn,3),-(x_SubcollectionOfWithRelationToTypeFn,1),-(x_VaccinationEvent,1),-(x_VaccineForAgainstFn,6),-(x_VaccineForFn,3),-(x_VaccineForHumans,3),-(x_argFormat,2),-('x_beneficiary-Generic',1),-(x_comment,1),-(x_disjointWith,1),-(x_drugAdministrationSubEvents,1),-(x_genls,15),-(x_isa,8),-(x_numberOfDoses,1),-(x_prescribedDrugType,1),-(x_prescriptionForPatient,1),-(x_prescriptionFromPrescriber,1),-(x_requiredArg1Pred,5),-(x_rewriteOf,2),-(x_subEvents,3),-(x_transitiveViaArgInverse,1),-(x_typeGenls,1),-(x_vaccinatedAgainst,3)],entries:[entry(a65b1276adfce1,signature(x_isa,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',3,[x_Bradycardia,x_Nesiritide,x_SideEffectsOfUsingDrugTypeFn,x_isa]),entry(a65b1276adfce2,signature(x_isa,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',4,[x_Hypotension,x_Nesiritide,x_SideEffectsOfUsingDrugTypeFn,x_isa]),entry(a65b1276adfce3,signature(x_isa,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',5,[x_Headache,x_Nesiritide,x_SideEffectsOfUsingDrugTypeFn,x_isa]),entry(a65b1276adfce4,signature(x_isa,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',6,[x_Nausea,x_Nesiritide,x_SideEffectsOfUsingDrugTypeFn,x_isa]),entry(a65b1276adfce5,signature(x_isa,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',7,[x_AnthraxInfection,x_HomoSapiens,x_SpatiallyDisjointObjectType,x_VaccineForAgainstFn,x_isa]),entry(a65b1276adfce6,signature(x_isa,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',8,[x_DrugTestWithBlood,x_KEClarifyingCollectionType,x_isa]),entry(a65b1276adfce7,signature(x_isa,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',9,[x_FirstOrderCollection,x_Person,x_SubcollectionOfWithRelationToTypeFn,x_VaccinationEvent,'x_beneficiary-Generic',x_isa]),entry(a65b1276adfce8,signature(x_isa,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',10,[x_AnthraxInfection,x_CollectionIntersection2Fn,x_FirstOrderCollection,x_VaccineForFn,x_VaccineForHumans,x_isa]),entry(a65b1276adfce9,signature(x_requiredArg1Pred,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',11,['x_DrugPrescription-Specification',x_numberOfDoses,x_requiredArg1Pred]),entry(a65b1276adfcea,signature(x_requiredArg1Pred,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',12,['x_MedicalPrescription-Specification',x_prescriptionFromPrescriber,x_requiredArg1Pred]),entry(a65b1276adfceb,signature(x_requiredArg1Pred,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',13,['x_DrugPrescription-Specification',x_prescribedDrugType,x_requiredArg1Pred]),entry(a65b1276adfcec,signature(x_requiredArg1Pred,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',14,['x_MedicalPrescription-Specification',x_prescriptionForPatient,x_requiredArg1Pred]),entry(a65b1276adfced,signature(x_requiredArg1Pred,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',15,[x_DrugTreatment,x_drugAdministrationSubEvents,x_requiredArg1Pred]),entry(a65b1276adfcee,signature(x_rewriteOf,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',16,[x_AnthraxInfection,x_CollectionIntersection2Fn,x_HomoSapiens,'x_Licensed-ProductType',x_LicensedHumanAnthraxVaccine,x_SpecsFn,x_VaccineForAgainstFn,x_rewriteOf]),entry(a65b1276adfcef,signature(x_rewriteOf,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',17,[x_AnthraxInfection,x_CollectionIntersection2Fn,x_HomoSapiens,x_VaccineForAgainstFn,x_VaccineForFn,x_VaccineForHumans,x_rewriteOf]),entry(a65b1276adfcf0,signature(x_argFormat,3),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',18,[x_SetTheFormat,x_argFormat,x_vaccinatedAgainst]),entry(a65b1276adfcf1,signature(x_argFormat,3),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',19,[x_SetTheFormat,x_argFormat,x_vaccinatedAgainst]),entry(a65b1276adfcf2,signature(x_transitiveViaArgInverse,3),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',20,[x_genls,x_transitiveViaArgInverse,x_vaccinatedAgainst]),entry(a65b1276adfcf3,signature(x_typeGenls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',21,[x_ExclusiveTreatmentType,x_MedicalTreatmentEvent,x_typeGenls]),entry(a65b1276adfcf4,signature(x_comment,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',22,[x_LicensedHumanAnthraxVaccine,x_comment]),entry(a65b1276adfcf5,signature(x_disjointWith,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',23,[x_AdministeringADrug,x_DrugTherapy,x_disjointWith]),entry(a65b1276adfcf6,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',24,['x_Alcohol-Compound',x_KillingThroughEventTypeFn,x_Poisoning,x_PoisoningViaSubstanceFn,x_genls]),entry(a65b1276adfcf7,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',25,[x_KillingThroughEventTypeFn,x_Poisoning,x_PoisoningViaSubstanceFn,x_RadioactiveStuff,x_genls]),entry(a65b1276adfcf8,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',26,['x_Alcohol-Compound',x_Attempting,x_AttemptingFn,x_KillingThroughEventTypeFn,x_PoisoningViaSubstanceFn,x_genls]),entry(a65b1276adfcf9,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',27,[x_Attempting,x_AttemptingFn,x_KillingThroughEventTypeFn,x_PoisoningViaSubstanceFn,x_RadioactiveStuff,x_genls]),entry(a65b1276adfcfa,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',28,[x_Attempting,x_AttemptingFn,x_KillingByOrganism,x_PoisoningViaSubstanceFn,x_RadioactiveStuff,x_SubcollectionOfWithRelationFromTypeFn,x_genls,x_subEvents]),entry(a65b1276adfcfb,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',29,['x_Alcohol-Compound',x_Attempting,x_AttemptingFn,x_KillingByOrganism,x_PoisoningViaSubstanceFn,x_SubcollectionOfWithRelationFromTypeFn,x_genls,x_subEvents]),entry(a65b1276adfcfc,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',30,['x_AcidicSolution-Liquid',x_Attempting,x_AttemptingFn,x_ImmersionOfInFn,x_KillingThroughEventTypeFn,x_Person,x_genls]),entry(a65b1276adfcfd,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',31,['x_AcidicSolution-Liquid',x_Attempting,x_AttemptingFn,x_ImmersionOfInFn,x_KillingByOrganism,x_Person,x_SubcollectionOfWithRelationFromTypeFn,x_genls,x_subEvents]),entry(a65b1276adfcfe,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',32,['x_Licensed-ProductType',x_LicensedHumanAnthraxVaccine,x_genls]),entry(a65b1276adfcff,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',33,[x_AnthraxInfection,x_HomoSapiens,x_LicensedHumanAnthraxVaccine,x_SpecsFn,x_VaccineForAgainstFn,x_genls]),entry(a65b1276adfd00,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',34,[x_AnthraxInfection,x_HomoSapiens,x_VaccineForAgainstFn,x_VaccineForFn,x_genls]),entry(a65b1276adfd01,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',35,[x_AnthraxInfection,x_HomoSapiens,x_VaccineForAgainstFn,x_VaccineForHumans,x_genls]),entry(a65b1276adfd02,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',36,[x_ImmediateReleaseDrugDeliveryProduct,x_SomethingExisting,x_genls]),entry(a65b1276adfd03,signature(x_genls,2),x_PharmaceuticalUseMt,'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf',37,[x_ExtendedReleaseDrugDeliveryProduct,x_SomethingExisting,x_genls])],predicates:[-(signature(x_argFormat,3),2),-(signature(x_comment,2),1),-(signature(x_disjointWith,2),1),-(signature(x_genls,2),14),-(signature(x_isa,2),8),-(signature(x_requiredArg1Pred,2),5),-(signature(x_rewriteOf,2),2),-(signature(x_transitiveViaArgInverse,3),1),-(signature(x_typeGenls,2),1)],rankedConstants:[-(15,x_genls),-(8,x_isa),-(7,x_AnthraxInfection),-(6,x_VaccineForAgainstFn),-(6,x_PoisoningViaSubstanceFn),-(6,x_HomoSapiens),-(6,x_AttemptingFn),-(6,x_Attempting),-(5,x_requiredArg1Pred),-(5,x_KillingThroughEventTypeFn),-(4,x_SideEffectsOfUsingDrugTypeFn),-(4,x_Nesiritide),-(4,x_LicensedHumanAnthraxVaccine),-(3,x_vaccinatedAgainst),-(3,x_subEvents),-(3,x_VaccineForHumans),-(3,x_VaccineForFn),-(3,x_SubcollectionOfWithRelationFromTypeFn),-(3,x_RadioactiveStuff),-(3,x_Person),-(3,x_KillingByOrganism),-(3,x_CollectionIntersection2Fn),-(3,'x_Alcohol-Compound'),-(2,x_rewriteOf),-(2,x_argFormat),-(2,x_SpecsFn),-(2,x_SomethingExisting),-(2,x_SetTheFormat),-(2,x_Poisoning),-(2,'x_MedicalPrescription-Specification'),-(2,'x_Licensed-ProductType'),-(2,x_ImmersionOfInFn),-(2,x_FirstOrderCollection),-(2,'x_DrugPrescription-Specification'),-(2,'x_AcidicSolution-Liquid'),-(1,x_typeGenls),-(1,x_transitiveViaArgInverse),-(1,x_prescriptionFromPrescriber),-(1,x_prescriptionForPatient),-(1,x_prescribedDrugType),-(1,x_numberOfDoses),-(1,x_drugAdministrationSubEvents),-(1,x_disjointWith),-(1,x_comment),-(1,'x_beneficiary-Generic'),-(1,x_VaccinationEvent),-(1,x_SubcollectionOfWithRelationToTypeFn),-(1,x_SpatiallyDisjointObjectType),-(1,x_Nausea),-(1,x_MedicalTreatmentEvent),-(1,x_KEClarifyingCollectionType),-(1,x_ImmediateReleaseDrugDeliveryProduct),-(1,x_Hypotension),-(1,x_Headache),-(1,x_ExtendedReleaseDrugDeliveryProduct),-(1,x_ExclusiveTreatmentType),-(1,x_DrugTreatment),-(1,x_DrugTherapy),-(1,x_DrugTestWithBlood),-(1,x_Bradycardia),-(1,x_AdministeringADrug)],rankedPredicates:[-(14,signature(x_genls,2)),-(8,signature(x_isa,2)),-(5,signature(x_requiredArg1Pred,2)),-(2,signature(x_rewriteOf,2)),-(2,signature(x_argFormat,3)),-(1,signature(x_typeGenls,2)),-(1,signature(x_transitiveViaArgInverse,3)),-(1,signature(x_disjointWith,2)),-(1,signature(x_comment,2))],source:'c:/snet/petta/repos/openworld_dr/KBs/fire/flat-files/nextkb/PharmaceuticalUseMt.krf'}).
xc_indexed_constant(a65b1276adfce1,x_Bradycardia).
xc_indexed_constant(a65b1276adfce1,x_Nesiritide).
xc_indexed_constant(a65b1276adfce1,x_SideEffectsOfUsingDrugTypeFn).
xc_indexed_constant(a65b1276adfce1,x_isa).
xc_indexed_constant(a65b1276adfce2,x_Hypotension).
xc_indexed_constant(a65b1276adfce2,x_Nesiritide).
xc_indexed_constant(a65b1276adfce2,x_SideEffectsOfUsingDrugTypeFn).
xc_indexed_constant(a65b1276adfce2,x_isa).
xc_indexed_constant(a65b1276adfce3,x_Headache).
xc_indexed_constant(a65b1276adfce3,x_Nesiritide).
xc_indexed_constant(a65b1276adfce3,x_SideEffectsOfUsingDrugTypeFn).
xc_indexed_constant(a65b1276adfce3,x_isa).
xc_indexed_constant(a65b1276adfce4,x_Nausea).
xc_indexed_constant(a65b1276adfce4,x_Nesiritide).
xc_indexed_constant(a65b1276adfce4,x_SideEffectsOfUsingDrugTypeFn).
xc_indexed_constant(a65b1276adfce4,x_isa).
xc_indexed_constant(a65b1276adfce5,x_AnthraxInfection).
xc_indexed_constant(a65b1276adfce5,x_HomoSapiens).
xc_indexed_constant(a65b1276adfce5,x_SpatiallyDisjointObjectType).
xc_indexed_constant(a65b1276adfce5,x_VaccineForAgainstFn).
xc_indexed_constant(a65b1276adfce5,x_isa).
xc_indexed_constant(a65b1276adfce6,x_DrugTestWithBlood).
xc_indexed_constant(a65b1276adfce6,x_KEClarifyingCollectionType).
xc_indexed_constant(a65b1276adfce6,x_isa).
xc_indexed_constant(a65b1276adfce7,x_FirstOrderCollection).
xc_indexed_constant(a65b1276adfce7,x_Person).
xc_indexed_constant(a65b1276adfce7,x_SubcollectionOfWithRelationToTypeFn).
xc_indexed_constant(a65b1276adfce7,x_VaccinationEvent).
xc_indexed_constant(a65b1276adfce7,'x_beneficiary-Generic').
xc_indexed_constant(a65b1276adfce7,x_isa).
xc_indexed_constant(a65b1276adfce8,x_AnthraxInfection).
xc_indexed_constant(a65b1276adfce8,x_CollectionIntersection2Fn).
xc_indexed_constant(a65b1276adfce8,x_FirstOrderCollection).
xc_indexed_constant(a65b1276adfce8,x_VaccineForFn).
xc_indexed_constant(a65b1276adfce8,x_VaccineForHumans).
xc_indexed_constant(a65b1276adfce8,x_isa).
xc_indexed_constant(a65b1276adfce9,'x_DrugPrescription-Specification').
xc_indexed_constant(a65b1276adfce9,x_numberOfDoses).
xc_indexed_constant(a65b1276adfce9,x_requiredArg1Pred).
xc_indexed_constant(a65b1276adfcea,'x_MedicalPrescription-Specification').
xc_indexed_constant(a65b1276adfcea,x_prescriptionFromPrescriber).
xc_indexed_constant(a65b1276adfcea,x_requiredArg1Pred).
xc_indexed_constant(a65b1276adfceb,'x_DrugPrescription-Specification').
xc_indexed_constant(a65b1276adfceb,x_prescribedDrugType).
xc_indexed_constant(a65b1276adfceb,x_requiredArg1Pred).
xc_indexed_constant(a65b1276adfcec,'x_MedicalPrescription-Specification').
xc_indexed_constant(a65b1276adfcec,x_prescriptionForPatient).
xc_indexed_constant(a65b1276adfcec,x_requiredArg1Pred).
xc_indexed_constant(a65b1276adfced,x_DrugTreatment).
xc_indexed_constant(a65b1276adfced,x_drugAdministrationSubEvents).
xc_indexed_constant(a65b1276adfced,x_requiredArg1Pred).
xc_indexed_constant(a65b1276adfcee,x_AnthraxInfection).
xc_indexed_constant(a65b1276adfcee,x_CollectionIntersection2Fn).
xc_indexed_constant(a65b1276adfcee,x_HomoSapiens).
xc_indexed_constant(a65b1276adfcee,'x_Licensed-ProductType').
xc_indexed_constant(a65b1276adfcee,x_LicensedHumanAnthraxVaccine).
xc_indexed_constant(a65b1276adfcee,x_SpecsFn).
xc_indexed_constant(a65b1276adfcee,x_VaccineForAgainstFn).
xc_indexed_constant(a65b1276adfcee,x_rewriteOf).
xc_indexed_constant(a65b1276adfcef,x_AnthraxInfection).
xc_indexed_constant(a65b1276adfcef,x_CollectionIntersection2Fn).
xc_indexed_constant(a65b1276adfcef,x_HomoSapiens).
xc_indexed_constant(a65b1276adfcef,x_VaccineForAgainstFn).
xc_indexed_constant(a65b1276adfcef,x_VaccineForFn).
xc_indexed_constant(a65b1276adfcef,x_VaccineForHumans).
xc_indexed_constant(a65b1276adfcef,x_rewriteOf).
xc_indexed_constant(a65b1276adfcf0,x_SetTheFormat).
xc_indexed_constant(a65b1276adfcf0,x_argFormat).
xc_indexed_constant(a65b1276adfcf0,x_vaccinatedAgainst).
xc_indexed_constant(a65b1276adfcf1,x_SetTheFormat).
xc_indexed_constant(a65b1276adfcf1,x_argFormat).
xc_indexed_constant(a65b1276adfcf1,x_vaccinatedAgainst).
xc_indexed_constant(a65b1276adfcf2,x_genls).
xc_indexed_constant(a65b1276adfcf2,x_transitiveViaArgInverse).
xc_indexed_constant(a65b1276adfcf2,x_vaccinatedAgainst).
xc_indexed_constant(a65b1276adfcf3,x_ExclusiveTreatmentType).
xc_indexed_constant(a65b1276adfcf3,x_MedicalTreatmentEvent).
xc_indexed_constant(a65b1276adfcf3,x_typeGenls).
xc_indexed_constant(a65b1276adfcf4,x_LicensedHumanAnthraxVaccine).
xc_indexed_constant(a65b1276adfcf4,x_comment).
xc_indexed_constant(a65b1276adfcf5,x_AdministeringADrug).
xc_indexed_constant(a65b1276adfcf5,x_DrugTherapy).
xc_indexed_constant(a65b1276adfcf5,x_disjointWith).
xc_indexed_constant(a65b1276adfcf6,'x_Alcohol-Compound').
xc_indexed_constant(a65b1276adfcf6,x_KillingThroughEventTypeFn).
xc_indexed_constant(a65b1276adfcf6,x_Poisoning).
xc_indexed_constant(a65b1276adfcf6,x_PoisoningViaSubstanceFn).
xc_indexed_constant(a65b1276adfcf6,x_genls).
xc_indexed_constant(a65b1276adfcf7,x_KillingThroughEventTypeFn).
xc_indexed_constant(a65b1276adfcf7,x_Poisoning).
xc_indexed_constant(a65b1276adfcf7,x_PoisoningViaSubstanceFn).
xc_indexed_constant(a65b1276adfcf7,x_RadioactiveStuff).
xc_indexed_constant(a65b1276adfcf7,x_genls).
xc_indexed_constant(a65b1276adfcf8,'x_Alcohol-Compound').
xc_indexed_constant(a65b1276adfcf8,x_Attempting).
xc_indexed_constant(a65b1276adfcf8,x_AttemptingFn).
xc_indexed_constant(a65b1276adfcf8,x_KillingThroughEventTypeFn).
xc_indexed_constant(a65b1276adfcf8,x_PoisoningViaSubstanceFn).
xc_indexed_constant(a65b1276adfcf8,x_genls).
xc_indexed_constant(a65b1276adfcf9,x_Attempting).
xc_indexed_constant(a65b1276adfcf9,x_AttemptingFn).
xc_indexed_constant(a65b1276adfcf9,x_KillingThroughEventTypeFn).
xc_indexed_constant(a65b1276adfcf9,x_PoisoningViaSubstanceFn).
xc_indexed_constant(a65b1276adfcf9,x_RadioactiveStuff).
xc_indexed_constant(a65b1276adfcf9,x_genls).
xc_indexed_constant(a65b1276adfcfa,x_Attempting).
xc_indexed_constant(a65b1276adfcfa,x_AttemptingFn).
xc_indexed_constant(a65b1276adfcfa,x_KillingByOrganism).
xc_indexed_constant(a65b1276adfcfa,x_PoisoningViaSubstanceFn).
xc_indexed_constant(a65b1276adfcfa,x_RadioactiveStuff).
xc_indexed_constant(a65b1276adfcfa,x_SubcollectionOfWithRelationFromTypeFn).
xc_indexed_constant(a65b1276adfcfa,x_genls).
xc_indexed_constant(a65b1276adfcfa,x_subEvents).
xc_indexed_constant(a65b1276adfcfb,'x_Alcohol-Compound').
xc_indexed_constant(a65b1276adfcfb,x_Attempting).
xc_indexed_constant(a65b1276adfcfb,x_AttemptingFn).
xc_indexed_constant(a65b1276adfcfb,x_KillingByOrganism).
xc_indexed_constant(a65b1276adfcfb,x_PoisoningViaSubstanceFn).
xc_indexed_constant(a65b1276adfcfb,x_SubcollectionOfWithRelationFromTypeFn).
xc_indexed_constant(a65b1276adfcfb,x_genls).
xc_indexed_constant(a65b1276adfcfb,x_subEvents).
xc_indexed_constant(a65b1276adfcfc,'x_AcidicSolution-Liquid').
xc_indexed_constant(a65b1276adfcfc,x_Attempting).
xc_indexed_constant(a65b1276adfcfc,x_AttemptingFn).
xc_indexed_constant(a65b1276adfcfc,x_ImmersionOfInFn).
xc_indexed_constant(a65b1276adfcfc,x_KillingThroughEventTypeFn).
xc_indexed_constant(a65b1276adfcfc,x_Person).
xc_indexed_constant(a65b1276adfcfc,x_genls).
xc_indexed_constant(a65b1276adfcfd,'x_AcidicSolution-Liquid').
xc_indexed_constant(a65b1276adfcfd,x_Attempting).
xc_indexed_constant(a65b1276adfcfd,x_AttemptingFn).
xc_indexed_constant(a65b1276adfcfd,x_ImmersionOfInFn).
xc_indexed_constant(a65b1276adfcfd,x_KillingByOrganism).
xc_indexed_constant(a65b1276adfcfd,x_Person).
xc_indexed_constant(a65b1276adfcfd,x_SubcollectionOfWithRelationFromTypeFn).
xc_indexed_constant(a65b1276adfcfd,x_genls).
xc_indexed_constant(a65b1276adfcfd,x_subEvents).
xc_indexed_constant(a65b1276adfcfe,'x_Licensed-ProductType').
xc_indexed_constant(a65b1276adfcfe,x_LicensedHumanAnthraxVaccine).
xc_indexed_constant(a65b1276adfcfe,x_genls).
xc_indexed_constant(a65b1276adfcff,x_AnthraxInfection).
xc_indexed_constant(a65b1276adfcff,x_HomoSapiens).
xc_indexed_constant(a65b1276adfcff,x_LicensedHumanAnthraxVaccine).
xc_indexed_constant(a65b1276adfcff,x_SpecsFn).
xc_indexed_constant(a65b1276adfcff,x_VaccineForAgainstFn).
xc_indexed_constant(a65b1276adfcff,x_genls).
xc_indexed_constant(a65b1276adfd00,x_AnthraxInfection).
xc_indexed_constant(a65b1276adfd00,x_HomoSapiens).
xc_indexed_constant(a65b1276adfd00,x_VaccineForAgainstFn).
xc_indexed_constant(a65b1276adfd00,x_VaccineForFn).
xc_indexed_constant(a65b1276adfd00,x_genls).
xc_indexed_constant(a65b1276adfd01,x_AnthraxInfection).
xc_indexed_constant(a65b1276adfd01,x_HomoSapiens).
xc_indexed_constant(a65b1276adfd01,x_VaccineForAgainstFn).
xc_indexed_constant(a65b1276adfd01,x_VaccineForHumans).
xc_indexed_constant(a65b1276adfd01,x_genls).
xc_indexed_constant(a65b1276adfd02,x_ImmediateReleaseDrugDeliveryProduct).
xc_indexed_constant(a65b1276adfd02,x_SomethingExisting).
xc_indexed_constant(a65b1276adfd02,x_genls).
xc_indexed_constant(a65b1276adfd03,x_ExtendedReleaseDrugDeliveryProduct).
xc_indexed_constant(a65b1276adfd03,x_SomethingExisting).
xc_indexed_constant(a65b1276adfd03,x_genls).
kb_index_footer(35,'6b1a500326413fa8e8f297dcebcccea9517b3acd1ffd8105aef73157a029218f',a176187e1f6d0ae5a4f75f7c5dccfbaa5e05b06ab7be5cc9e97a63f4fba7613f).
